package de.tum.cit.aet.artemis.core.service.feature;

public enum CommunicationFeature implements AbstractFeature {

    // Messaging Features
    SEND_MESSAGES, RECEIVE_MESSAGES, REACT_TO_MESSAGES, REPLY_IN_THREAD, COPY_TEXT, PIN_MESSAGES, DELETE_MESSAGE, EDIT_MESSAGE, SAVE_MESSAGE_FOR_LATER, FORWARD_MESSAGES,
    RESOLVE_MESSAGES, POST_ACTION_BAR,

    // Formatting and Tagging
    TAG_OTHER_USERS, REFERENCE_CHANNELS_LECTURES_EXERCISES, BASIC_FORMATTING, STRIKETHROUGH_FORMATTING, PREVIEW, CODE_BLOCK_INLINE_CODE, REFERENCE_FORMATTING, LINK_FORMATTING,

    // Message Rendering
    PROFILE_PICTURES, SHOW_EDITED_RESOLVED_PINNED, RENDER_LINKS_WITH_ICONS, RENDER_FAQ_LINKS, MARK_UNREAD_MESSAGES, RENDER_IMAGES, RENDER_UPLOADED_FILES,

    // Message Management
    FILTER_MESSAGES, SORT_MESSAGES, SEARCH_MESSAGES_IN_CHAT, SEARCH_MESSAGES_ACROSS_CHATS,

    // User Interactions
    OPEN_PROFILE_INFO, START_CONVERSATION_FROM_PROFILE,

    // Link & Attachment Handling
    OPEN_CORRECT_VIEW_FOR_LINKS, OPEN_IMAGES_FULLSCREEN, DOWNLOAD_SENT_IMAGES, VIEW_DOWNLOAD_ATTACHMENTS,

    // Chat Management
    SEARCH_FOR_CHATS, FILTER_CHATS, MARK_UNREAD_CHATS, MUTE_HIDE_FAVORITE_CHAT, EDIT_CHAT_INFORMATION, ARCHIVE_CHAT, DELETE_CHAT,

    // Member Management
    VIEW_MEMBERS, SEARCH_MEMBERS, FILTER_MEMBERS, ADD_MEMBERS_TO_CHAT, FILTER_MEMBERS_WHILE_ADDING, ADD_WHOLE_GROUPS, GRANT_REVOKE_MODERATOR_ROLES,

    // Channel & Group Management
    CREATE_DIRECT_CHAT, CREATE_CHANNEL, UPDATE_CHANNEL_INFORMATION, CREATE_GROUP_CHAT, REMOVE_USERS_FROM_GROUP_CHAT, BROWSE_CHANNELS, SHOW_CHAT_INFO, LEAVE_CHAT, DELETE_CHANNEL,
    ARCHIVE_CHANNEL,

    // Notifications
    NOTIFICATION_OVERVIEW, NOTIFICATION_SETTINGS;

    public CommunicationFeature[] getAllFeatures() {
        return CommunicationFeature.values();
    }

    public static CommunicationFeature[] getConfigurableFeatures() {
        return new CommunicationFeature[] { NOTIFICATION_SETTINGS, NOTIFICATION_OVERVIEW, MARK_UNREAD_CHATS };
    }
}
