package ${packageName};

import static org.junit.Assert.fail;

import java.lang.reflect.Type;
import java.lang.annotation.Annotation;
import java.lang.reflect.*;
import java.util.*;

import org.json.*;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

/**
 * @author Stephan Krusche (krusche@in.tum.de)
 * @version 3.0 (25.09.2019)
 * <br><br>
 * This test evaluates if the specified attributes in the structure oracle are correctly implemented with the expected type, visibility modifiers and annotations,
 * based on its definition in the structure oracle (test.json).
 */
@RunWith(Parameterized.class)
public class AttributeTest extends StructuralTest {

    public AttributeTest(String expectedClassName, String expectedPackageName, JSONObject expectedClassJSON) {
        super(expectedClassName, expectedPackageName, expectedClassJSON);
    }

    /**
     * This method collects the classes in the structure oracle file for which attributes are specified.
     * These classes are packed into a list, which represents the test data.
     * @return A list of arrays containing each class' name, package and the respective JSON object defined in the structure oracle.
     */
    @Parameterized.Parameters(name = "{0}")
    public static Collection<Object[]> findClasses() {
        List<Object[]> testData = new ArrayList<Object[]>();

        if (structureOracleJSON == null) {
            fail("The AttributeTest test can only run if the structural oracle (test.json) is present. If you do not provide it, delete AttributeTest.java!");
        }

        for (int i = 0; i < structureOracleJSON.length(); i++) {
            JSONObject expectedClassJSON = structureOracleJSON.getJSONObject(i);

            // Only test the classes that have attributes defined in the oracle.
            if(expectedClassJSON.has(JSON_PROPERTY_CLASS) && (expectedClassJSON.has(JSON_PROPERTY_ATTRIBUTES) || expectedClassJSON.has("enumValues"))) {
                JSONObject expectedClassPropertiesJSON = expectedClassJSON.getJSONObject(JSON_PROPERTY_CLASS);
                String expectedClassName = expectedClassPropertiesJSON.getString(JSON_PROPERTY_NAME);
                String expectedPackageName = expectedClassPropertiesJSON.getString(JSON_PROPERTY_PACKAGE);
                testData.add(new Object[]{ expectedClassName, expectedPackageName, expectedClassJSON });
            }
        }
        if (testData.size() == 0) {
            fail("No tests for attributes available in the structural oracle (test.json). Either provide attributes information or delete AttributeTest.java!");
        }
        return testData;
    }

    /**
     * This test loops over the list of the test data generated by the method findClasses(), checks if each class is found
     * at all in the assignment and then proceeds to check its attributes.
     */
    @Test(timeout = 1000)
    public void testAttributes() {
        Class<?> observedClass = findClassForTestType("attribute");

        if(expectedClassJSON.has(JSON_PROPERTY_ATTRIBUTES)) {
            JSONArray expectedAttributes = expectedClassJSON.getJSONArray(JSON_PROPERTY_ATTRIBUTES);
            checkAttributes(observedClass, expectedAttributes);
        }
        if(expectedClassJSON.has("enumValues")) {
            JSONArray expectedEnumValues = expectedClassJSON.getJSONArray("enumValues");
            checkEnumValues(observedClass, expectedEnumValues);
        }
    }

    /**
     * This method checks if a observed class' attributes match the expected ones defined in the structure oracle.
     * @param observedClass: The class that needs to be checked as a Class object.
     * @param expectedAttributes: The information on the expected attributes contained in a JSON array. This information consists
     * of the name, the type and the visibility modifiers of each attribute.
     */
    private void checkAttributes(Class<?> observedClass, JSONArray expectedAttributes) {
        for(int i = 0; i < expectedAttributes.length(); i++) {
            JSONObject expectedAttribute = expectedAttributes.getJSONObject(i);
            String expectedName = expectedAttribute.getString(JSON_PROPERTY_NAME);
            String expectedTypeName = expectedAttribute.getString(JSON_PROPERTY_TYPE);
            JSONArray expectedModifiers = expectedAttribute.has(JSON_PROPERTY_MODIFIERS) ? expectedAttribute.getJSONArray(JSON_PROPERTY_MODIFIERS) : new JSONArray();
            JSONArray expectedAnnotations = expectedAttribute.has(JSON_PROPERTY_ANNOTATIONS) ? expectedAttribute.getJSONArray(JSON_PROPERTY_ANNOTATIONS) : new JSONArray();

            // We check for each expected attribute if the name and the type is right.
            boolean nameIsRight = false;
            boolean typeIsRight = false;
            boolean modifiersAreRight = false;
            boolean annotationsAreRight = false;

            for(Field observedAttribute : observedClass.getDeclaredFields()) {
                String observedName = observedAttribute.getName();
                String[] observedModifiers = Modifier.toString(observedAttribute.getModifiers()).split(" ");
                Annotation[] observedAnnotations = observedAttribute.getAnnotations();

                // If the names don't match, then proceed to the next observed attribute
                if(!expectedName.equals(observedName)) {
                    //TODO: we should also take wrong case and typos into account
                    continue;
                } else {
                    nameIsRight = true;
                }

                typeIsRight = checkType(observedAttribute, expectedTypeName);
                modifiersAreRight = checkModifiers(observedModifiers, expectedModifiers);
                annotationsAreRight = checkAnnotations(observedAnnotations, expectedAnnotations);

                // If all are correct, then we found our attribute and we can break the loop
                if(nameIsRight && typeIsRight && modifiersAreRight && annotationsAreRight) {
                    break;
                }
            }

            String expectedAttributeInformation = "the expected attribute '" + expectedName + "' of the class '" + expectedClassName + "'";

            if (!nameIsRight) {
                fail("The name of " + expectedAttributeInformation + " is not implemented as expected.");
            }
            if (!typeIsRight) {
                fail("The type of " + expectedAttributeInformation + " is not implemented as expected.");
            }
            if (!modifiersAreRight) {
                fail("The modifier(s) (access type, abstract, etc.) of " + expectedAttributeInformation + " are not implemented as expected.");
            }
            if (!annotationsAreRight) {
                fail("The annotation(s) of " + expectedAttributeInformation + " are not implemented as expected.");
            }
        }
    }

    /**
     * This method checks if the observed enum values match the expected ones defined in the structure oracle.
     * @param observedClass: The enum that needs to be checked as a Class object.
     * @param expectedEnumValues: The information on the expected enum values contained in a JSON array. This information consists
     * of the name of each enum value.
     */
    private void checkEnumValues(Class<?> observedClass, JSONArray expectedEnumValues) {
        Object[] observedEnumValues = observedClass.getEnumConstants();

        if (observedEnumValues == null) {
            fail("The enum '" + expectedClassName + "' does not contain any enum constants. Make sure to implement them.");
        }
        if (expectedEnumValues.length() != observedEnumValues.length) {
            fail("The enum '" + expectedClassName + "' does not contain all the expected enum values. Make sure to implement the missing enums.");
        }

        for(int i = 0; i < expectedEnumValues.length(); i++) {
            String expectedEnumValue = expectedEnumValues.getString(i);

            boolean enumValueExists = false;
            for(Object observedEnumValue : observedEnumValues) {

                if(expectedEnumValue.equals(observedEnumValue.toString())) {
                    enumValueExists = true;
                    break;
                }
            }
            if(!enumValueExists) {
                fail("The class '" + expectedClassName + "' does not include the enum value: " + expectedEnumValue
                    + ". Make sure to implement it as expected.");
            }
        }
    }

    /**
     * This method checks if the type of an observed attribute matches the expected one.
     * It first checks if the type of the attribute is a generic one or not.
     * In the first case, it sees if the main and the generic types match, otherwise
     * it only looks up the simple name of the attribute.
     * @param observedAttribute: The observed attribute we need to check.
     * @param expectedTypeName: The name of the expected type.
     * @return True, if the types match, false otherwise.
     */
    protected boolean checkType(Field observedAttribute, String expectedTypeName) {
        boolean expectedTypeIsGeneric = expectedTypeName.contains("<") && expectedTypeName.contains(">");

        if(expectedTypeIsGeneric) {
            boolean mainTypeIsRight = false;
            boolean genericTypeIsRight = false;

            String expectedMainTypeName = expectedTypeName.split("<")[0];
            String observedMainTypeName = observedAttribute.getType().getSimpleName();
            mainTypeIsRight = expectedMainTypeName.equals(observedMainTypeName);

            String expectedGenericTypeName = expectedTypeName.split("<")[1].replace(">", "");
            if(observedAttribute.getGenericType() instanceof ParameterizedType) {
                Type observedGenericType = ((ParameterizedType) observedAttribute.getGenericType()).getActualTypeArguments()[0];
                String observedGenericTypeName = observedGenericType.toString().substring(observedGenericType.toString().lastIndexOf(".") + 1);
                genericTypeIsRight = expectedGenericTypeName.equals(observedGenericTypeName);
            }

            return mainTypeIsRight && genericTypeIsRight;
        } else {
            String observedTypeName = observedAttribute.getType().getSimpleName();
            return expectedTypeName.equals(observedTypeName);
        }
    }
}
