'' Basically using the default theme, but we add the modifications from the templates here

skinparam ArrowFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
    FontSize 20
    BackgroundColor white
    AttributeFontSize 16
	BorderColor black
	ArrowColor black
}