!$THEME = "artemisdark2"

!$BGCOLOR = "transparent"

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false

!$PRIMARY_FONT = "#FFFFFF"
!$ARROW = "#FFFFFF"
!$BORDER_COLOR = "#CCC"
!$HEADER = "#303030"
!$BACKGROUND = "transparent"

skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5
skinparam ArrowColor            $ARROW


!procedure $primary_scheme()
	FontColor $PRIMARY_FONT
	BorderColor $BORDER_COLOR
	BackgroundColor $BACKGROUND
	HeaderBackgroundColor $HEADER
!endprocedure

skinparam class {
	$primary_scheme()
	BorderThickness 1
	AttributeFontSize 11
}