package de.tum.in.www1.artemis.domain.enumeration;

public enum NotificationType {
    ATTACHMENT_CHANGE, EXERCISE_CREATED, EXERCISE_PRACTICE, QUIZ_EXERCISE_STARTED, EXERCISE_UPDATED, NEW_ANSWER_FOR_EXERCISE, NEW_ANSWER_FOR_LECTURE, NEW_QUESTION_FOR_EXERCISE,
    NEW_QUESTION_FOR_LECTURE, COURSE_ARCHIVE_STARTED, COURSE_ARCHIVE_FINISHED, COURSE_ARCHIVE_FAILED, DUPLICATE_TEST_CASE, EXAM_ARCHIVE_STARTED, EXAM_ARCHIVE_FINISHED,
    EXAM_ARCHIVE_FAILED, ILLEGAL_SUBMISSION
}
