before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    yarn: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
jobs:
    include:
      - stage: Build
        name: "Java"
        language: java
        jdk: openjdk12
        install: skip
        script: ./gradlew -Pprod compileJava
      - stage: Build
        name: "TypeScript"
        language: node_js
        node_js: 12.8.0
        install: yarn install
        script: yarn build
      - stage: Test
        name: "Java"
        language: java
        jdk: openjdk12
        install: skip
        script: ./gradlew executeTests
      - stage: Test
        name: "TypeScript"
        language: node_js
        node_js: 12.8.0
        install: yarn install
        script: yarn test
      - stage: Lint
        name: "Java Code Style"
        language: java
        jdk: openjdk12
        install: skip
        script: ./gradlew spotlessCheck
      - stage: Lint
        name: "Java Documentation"
        language: java
        jdk: openjdk12
        install: skip
        script: ./gradlew checkstyleMain -x yarn_install -x webpackBuildDev -x webpack
      - stage: Lint
        name: "TypeScript Formatting"
        language: node_js
        node_js: 12.8.0
        install: yarn install
        script: yarn prettier:check
      - stage: Lint
        name: "TypeScript Code Style"
        language: node_js
        node_js: 12.8.0
        install: yarn install
        script: yarn lint
      - stage: Lint
        name: "TypeScript Documentation"
        language: node_js
        node_js: 12.8.0
        install: yarn install
        script: yarn lint:doc
    allow_failures:
      - script: yarn lint:doc
