export * from './text-exercise.model';
export * from './text-exercise-update.component';
export * from './text-exercise-popup.service';
export * from './text-exercise.service';
export * from './text-exercise-dialog.component';
export * from './text-exercise-delete-dialog.component';
export * from './text-exercise-detail.component';
export * from './text-exercise.component';
export * from './text-exercise.route';
