package de.tum.cit.aet.artemis.core;

public enum FilePathType {
    LECTURE_ATTACHMENT, SLIDE, TEMPORARY, DRAG_AND_DROP_BACKGROUND, DRAG_ITEM, PROFILE_PICTURE, COURSE_ICON, EXAM_USER_SIGNATURE, STUDENT_IMAGE, STUDENT_VERSION_SLIDES,
    FILE_UPLOAD_EXERCISE, ATTACHMENT_UNIT

}
