# ===================================================================
# Artemis specific properties
# ===================================================================

artemis:
    repo-clone-path: ./repos/
    repo-download-clone-path: ./repos-download/
    encryption-password: <encrypt-password>     # arbitrary password for encrypting database values
    ldap:
        url: <url>
        user-dn: <user-dn>
        password: <password>
        base: <base>
    jira:
        url: https://jira.ase.in.tum.de
        user: <username>    # e.g. ga12abc
        password: <password>
        admin-group-name: tumuser
    version-control:
        url: https://bitbucket.ase.in.tum.de
        user: <username>    # e.g. ga12abc
        secret: <password>
    bamboo:
        url: https://bamboobruegge.in.tum.de
        user: <username>    # e.g. ga12abc
        password: <password>
        vcs-application-link-name: LS1 Bitbucket Server
        empty-commit-necessary: true
        authentication-token: <secrettoken>
    lti:
        id: artemis_lti
        oauth-key: artemis_lti_key
        oauth-secret: <secret>    # only important for online courses on the edX platform, can typically be ignored
        user-prefix_edx: edx_
        user-prefix_u4i: u4i_
        user-group-name_edx: edx
        user-group-name_u4i: u4i
    git:
        name: Artemis
        email: artemis@in.tum.de
    automatic-text:
        embedding-url: http://localhost:8000/embed
        embedding-chunk-size: 50
        clustering-url: http://localhost:8000/cluster
        segmentation-url: http://localhost:8080/segment
        secret: null
