- name: compile
  script: |-
    cd "${testWorkingDirectory}"

    # Artemis replaces the variable on the right hand side with a concrete value
    export studentParentWorkingDirectoryName="${studentParentWorkingDirectoryName}"
    export solutionWorkingDirectory="${solutionWorkingDirectory}"
    export testWorkingDirectory="${testWorkingDirectory}"

    chmod +x run.sh
    ./run.sh -s --only compile
- name: test
  script: |-
    cd "${testWorkingDirectory}"

    # Artemis replaces the variable on the right hand side with a concrete value
    export studentParentWorkingDirectoryName="${studentParentWorkingDirectoryName}"
    export solutionWorkingDirectory="${solutionWorkingDirectory}"
    export testWorkingDirectory="${testWorkingDirectory}"

    ./run.sh -s --only test
- name: junit
  script: '#empty script action, just for the results'
  forceRun: true
  resultPaths:
    - 'test-reports/*.xml'
