package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** Parses and validates problem-statement {@code [task][title](testName)} bindings and detects grader-internal prose leaks. */
final class ProblemStatementBindingChecker {

    /**
     * Matches a problem-statement task binding and captures its parenthesised, comma-separated test names: {@code [task][Some title](testA,testB)}. The capture is greedy (up to
     * the last {@code )} on the line) because a test identifier can itself contain parentheses. Matching stays production-exact: {@code testFoo} and {@code testFoo()} are
     * different names unless the production task extractor also maps them.
     */
    private static final Pattern TASK_BINDING = Pattern.compile("\\[task\\]\\[[^\\]]*\\]\\((.*)\\)");

    /**
     * A line shaped exactly like a task binding {@code [keyword][title](names)} (captures the keyword) so a near-miss such as {@code [tasks]} or {@code [Task]} is caught: only the
     * literal lowercase {@code [task]} binds tests; any other keyword renders as plain text and binds nothing, silently dropping a graded requirement and leaking the raw test
     * name.
     */
    private static final Pattern TASK_LIKE_BINDING = Pattern.compile("\\[(\\w+)\\]\\[[^\\]]*\\]\\([^)]*\\)");

    /**
     * A bare {@code [task]}/{@code [tasks]} marker not in binding position (negative lookahead excludes a real {@code [task][Title](test)} binding) — a prose leak.
     */
    private static final Pattern BARE_TASK_KEYWORD = Pattern.compile("\\[tasks?\\](?!\\s*\\[[^\\]]*\\]\\s*\\()", Pattern.CASE_INSENSITIVE);

    /**
     * Grader-mechanics phrasings that must not reach a student; each is specific enough to be a leak rather than legitimate prose. Matched case-insensitively as substrings.
     * <p>
     * Only high-precision grader-internal phrasings are matched ({@code NotImplementedError}, {@code todo!()}, "exact test name", "reported by the test runner", "generated by the
     * test suite/runner"); each names a grader/runner internal a student-facing statement has no business exposing. Generic instructor prose like "complete the method in the
     * template file" or "unimplemented stubs make the tests fail" is legitimate and not matched — matching it would false-reject valid problem statements.
     */
    private static final List<Pattern> PROSE_MECHANICS_LEAKS = List.of(Pattern.compile("notimplementederror", Pattern.CASE_INSENSITIVE), Pattern.compile("todo!\\(\\)"),
            Pattern.compile("exact test name", Pattern.CASE_INSENSITIVE), Pattern.compile("reported by the test runner", Pattern.CASE_INSENSITIVE),
            Pattern.compile("generated by the test (?:suite|runner)", Pattern.CASE_INSENSITIVE), Pattern.compile("adjust accordingly in tests", Pattern.CASE_INSENSITIVE));

    private ProblemStatementBindingChecker() {
    }

    /** Whether the problem statement carries at least one {@code [task][Title](testName)} binding (the presence gate: a statement with none shows students no task checklist). */
    /** Third-person authoring voice about "students"; the statement must address the reader directly (observed live twice: "Students will implement", "Students must define"). */
    private static final Pattern THIRD_PERSON_STUDENTS = Pattern.compile("(?i)\\bstudents?\\s+(will|must|should|shall|need to|are required)\\b");

    /** Matches a {@code [task][Title](...)} line's title. */
    private static final Pattern TASK_TITLE = Pattern.compile("\\[task\\]\\[([^\\]]+)\\]");

    /** Matches every {@code testsColor(NAME)} occurrence (member and edge form); a trailing {@code ()} on the name is tolerated. */
    private static final Pattern TESTS_COLOR_NAME = Pattern.compile("testsColor\\(([^)]+?)(?:\\(\\))?\\)");

    /** Whether the statement writes ABOUT students in the third person instead of addressing the reader. */
    static boolean writesAboutStudentsInThirdPerson(String problemStatement) {
        return THIRD_PERSON_STUDENTS.matcher(problemStatement).find();
    }

    /** Every [task] title that appears more than once — a title names one seam, so a repeat means tests were split 1:1 instead of grouped. */
    static List<String> duplicateTaskTitles(String problemStatement) {
        return TASK_TITLE.matcher(problemStatement).results().map(match -> match.group(1).strip()).collect(java.util.stream.Collectors.groupingBy(title -> title)).entrySet()
                .stream().filter(entry -> entry.getValue().size() > 1).map(java.util.Map.Entry::getKey).sorted().toList();
    }

    /** Every distinct {@code testsColor} name that matches none of the known test names — a silently dead interactive diagram link. */
    static List<String> unresolvedTestsColorNames(String problemStatement, List<String> actualTestNames, Set<String> seededStructuralTestNames) {
        Set<String> known = new java.util.HashSet<>(actualTestNames);
        known.addAll(seededStructuralTestNames);
        return TESTS_COLOR_NAME.matcher(problemStatement).results().map(match -> match.group(1).strip()).distinct().filter(name -> !known.contains(name)).sorted().toList();
    }

    /** Whether a PlantUML rendering directive appears outside every {@code @startuml}...{@code @enduml} block — Artemis renders such a line as stray statement text. */
    static boolean hasStrayPlantUmlDirectives(String problemStatement) {
        boolean insideDiagram = false;
        for (String line : problemStatement.lines().map(String::strip).toList()) {
            if (line.startsWith("@startuml")) {
                insideDiagram = true;
            }
            else if (line.startsWith("@enduml")) {
                insideDiagram = false;
            }
            else if (!insideDiagram && (line.startsWith("hide empty") || line.startsWith("skinparam "))) {
                return true;
            }
        }
        return false;
    }

    /** Whether DESIGN.md's {@code ## Diagram} section starts with "yes" (the agent's own declared decision; kept current per the design-update rule). */
    static boolean designSaysDiagramYes(String designDocument) {
        int index = designDocument.indexOf("## Diagram");
        if (index < 0) {
            return false;
        }
        String section = designDocument.substring(index + "## Diagram".length()).strip();
        return section.regionMatches(true, 0, "yes", 0, 3);
    }

    /** Every markdown heading line that appears more than once verbatim. */
    static List<String> duplicateHeadings(String problemStatement) {
        return problemStatement.lines().map(String::strip).filter(line -> line.startsWith("#")).collect(java.util.stream.Collectors.groupingBy(line -> line)).entrySet().stream()
                .filter(entry -> entry.getValue().size() > 1).map(java.util.Map.Entry::getKey).sorted().toList();
    }

    static boolean hasTaskBindings(String problemStatement) {
        return TASK_BINDING.matcher(problemStatement).find();
    }

    /**
     * The trimmed, non-empty test names bound by every {@code [task][Title](names)} line, in encounter order and preserving duplicates.
     */
    static List<String> boundTestNames(String problemStatement) {
        List<String> names = new ArrayList<>();
        Matcher matcher = TASK_BINDING.matcher(problemStatement);
        while (matcher.find()) {
            for (String rawName : matcher.group(1).split(",")) {
                String name = rawName.trim();
                if (!name.isEmpty()) {
                    names.add(name);
                }
            }
        }
        return names;
    }

    static List<List<String>> boundTestGroups(String problemStatement) {
        List<List<String>> groups = new ArrayList<>();
        Matcher matcher = TASK_BINDING.matcher(problemStatement);
        while (matcher.find()) {
            List<String> names = new ArrayList<>();
            for (String rawName : matcher.group(1).split(",")) {
                String name = rawName.trim();
                if (!name.isEmpty()) {
                    names.add(name);
                }
            }
            if (!names.isEmpty()) {
                groups.add(List.copyOf(names));
            }
        }
        return groups;
    }

    /** The distinct non-{@code [task]} keywords used on task-binding-shaped lines; empty when every such line uses {@code [task]}. See {@link #TASK_LIKE_BINDING}. */
    static List<String> malformedTaskKeywords(String problemStatement) {
        Matcher matcher = TASK_LIKE_BINDING.matcher(problemStatement);
        List<String> wrongKeywords = new ArrayList<>();
        while (matcher.find()) {
            String keyword = matcher.group(1);
            if (!"task".equals(keyword) && !wrongKeywords.contains(keyword)) {
                wrongKeywords.add(keyword);
            }
        }
        return wrongKeywords;
    }

    /**
     * The {@code [task]}-bound names that resolve to no real test, so the verifier can reject a checklist that binds to nothing. Fails open when the extracted name set is missing
     * or shorter than the test count.
     * <p>
     * Structural-test exemption: only names in the authoritative seeded set are treated as resolved without appearing in the current build report. A merely structural-shaped name
     * is not trusted; otherwise a problem statement could invent a fake non-grading structural task.
     */
    static List<String> unresolvedTaskBindings(String problemStatement, List<String> actualTestNames, int testCount, Set<String> seededStructuralTestNames) {
        if (actualTestNames.isEmpty() || actualTestNames.size() < testCount) {
            return List.of();
        }
        Set<String> actual = actualTestNames.stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        Set<String> seededStructural = seededStructuralTestNames == null ? Set.of()
                : seededStructuralTestNames.stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        List<String> unresolved = new ArrayList<>();
        for (String name : boundTestNames(problemStatement)) {
            String normalized = normalizeTestName(name);
            if (actual.contains(normalized) || seededStructural.contains(normalized)) {
                continue;
            }
            if (!unresolved.contains(name)) {
                unresolved.add(name);
            }
        }
        return unresolved;
    }

    /** The normalized test names bound more than once by {@code [task]} entries. */
    static List<String> duplicateTaskBindings(String problemStatement) {
        Set<String> seen = new java.util.LinkedHashSet<>();
        List<String> duplicates = new ArrayList<>();
        for (String name : boundTestNames(problemStatement)) {
            String normalized = normalizeTestName(name);
            if (!seen.add(normalized) && !duplicates.contains(normalized)) {
                duplicates.add(normalized);
            }
        }
        return duplicates;
    }

    /** Real gradable tests that production will grade but the problem statement does not expose via any {@code [task]} binding. */
    static List<String> unboundGradableTestNames(String problemStatement, List<String> actualTestNames, int testCount) {
        if (actualTestNames.isEmpty() || actualTestNames.size() < testCount) {
            return List.of();
        }
        Set<String> bound = boundTestNames(problemStatement).stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        List<String> unbound = new ArrayList<>();
        for (String rawName : actualTestNames) {
            String normalized = normalizeTestName(rawName);
            if (BuildGateTestNames.isBuildGate(normalized) || bound.contains(normalized)) {
                continue;
            }
            if (!unbound.contains(normalized)) {
                unbound.add(normalized);
            }
        }
        return unbound;
    }

    /**
     * The distinct student-facing prose-hygiene leaks in the problem statement: bare {@code [task]}/{@code [tasks]} markers not in binding position, plus high-precision
     * grader-mechanics phrasings. Empty when the prose is clean. Surfaced verbatim to the agent so a retry can excise the exact offending text. See {@link #BARE_TASK_KEYWORD} and
     * {@link #PROSE_MECHANICS_LEAKS}.
     */
    static List<String> proseHygieneLeaks(String problemStatement) {
        List<String> leaks = new ArrayList<>();
        if (BARE_TASK_KEYWORD.matcher(problemStatement).find()) {
            leaks.add("a bare [task]/[tasks] marker outside a [task][Title](testName) binding");
        }
        for (Pattern pattern : PROSE_MECHANICS_LEAKS) {
            Matcher matcher = pattern.matcher(problemStatement);
            if (matcher.find()) {
                String matched = '"' + matcher.group() + '"';
                if (!leaks.contains(matched)) {
                    leaks.add(matched);
                }
            }
        }
        return leaks;
    }

    /** Normalises only surrounding whitespace; production task extraction matches test names exactly after trimming the comma-separated binding entries. */
    static String normalizeTestName(String name) {
        return name.trim();
    }
}
