package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** Parses and validates problem-statement {@code [task][title](testName)} bindings and detects grader-internal prose leaks. */
final class ProblemStatementBindingChecker {

    /**
     * Captures a task binding's parenthesised, comma-separated test names: {@code [task][Some title](testA,testB)}. The capture is greedy (up to the line's last {@code )})
     * because a test identifier can itself contain parentheses. Matching stays production-exact: {@code testFoo} and {@code testFoo()} are different names unless the production
     * task extractor maps them.
     */
    private static final Pattern TASK_BINDING = Pattern.compile("\\[task\\]\\[[^\\]]*\\]\\((.*)\\)");

    /** Production rendering masks code before expanding task bindings, so code examples must not count as executable Artemis tasks here either. */
    private static final Pattern MARKDOWN_CODE = Pattern.compile("```[\\s\\S]*?```|`[^`\\n]+`");

    /**
     * A line shaped like a task binding, capturing its keyword so a near-miss such as {@code [tasks]} or {@code [Task]} is caught: only the literal lowercase {@code [task]} binds
     * tests, and any other keyword renders as plain text, silently dropping a graded requirement while leaking the raw test name.
     */
    private static final Pattern TASK_LIKE_BINDING = Pattern.compile("\\[(\\w+)\\]\\[[^\\]]*\\]\\([^)]*\\)");

    /** A bare {@code [task]}/{@code [tasks]} marker outside binding position, which is a prose leak. */
    private static final Pattern BARE_TASK_KEYWORD = Pattern.compile("\\[tasks?\\](?!\\s*\\[[^\\]]*\\]\\s*\\()", Pattern.CASE_INSENSITIVE);

    /**
     * Grader-mechanics phrasings that must not reach a student, each naming a grader or runner internal a student-facing statement has no business exposing. They must stay
     * high-precision: generic instructor prose like "complete the method in the template file" is legitimate, and matching it would false-reject valid problem statements.
     */
    private static final List<Pattern> PROSE_MECHANICS_LEAKS = List.of(Pattern.compile("notimplementederror", Pattern.CASE_INSENSITIVE), Pattern.compile("todo!\\(\\)"),
            Pattern.compile("exact test name", Pattern.CASE_INSENSITIVE), Pattern.compile("reported by the test runner", Pattern.CASE_INSENSITIVE),
            Pattern.compile("generated by the test (?:suite|runner)", Pattern.CASE_INSENSITIVE), Pattern.compile("adjust accordingly in tests", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bSPEC\\.md\\b", Pattern.CASE_INSENSITIVE), Pattern.compile("\\btest-plan\\.json\\b", Pattern.CASE_INSENSITIVE),
            Pattern.compile("(?<![\\w.])/workspace(?:/|\\b)", Pattern.CASE_INSENSITIVE), Pattern.compile("\\breference/", Pattern.CASE_INSENSITIVE),
            // The tests as an ACTIVE subject reaching into the student's code ("Tests may replace this field via reflection"). Requiring "tests" to precede "reflection" as the
            // acting subject keeps legitimate requirements ("must provide a no-argument constructor so it can be instantiated via reflection in the tests") out of the match.
            Pattern.compile("\\btests?\\s+(?:may|might|will|can)\\s+(?:\\w+\\s+){0,6}\\breflection\\b", Pattern.CASE_INSENSITIVE));

    private ProblemStatementBindingChecker() {
    }

    /** Third-person authoring voice about "students"; the statement must address the reader directly. */
    private static final Pattern THIRD_PERSON_STUDENTS = Pattern.compile("(?i)\\bstudents?\\s+(will|must|should|shall|need to|are required)\\b");

    /** Matches a {@code [task][Title](...)} line's title. */
    private static final Pattern TASK_TITLE = Pattern.compile("\\[task\\]\\[([^\\]]+)\\]");

    /** Matches every {@code testsColor(NAME)} occurrence (member and edge form); a trailing {@code ()} on the name is tolerated. */
    private static final Pattern TESTS_COLOR_NAME = Pattern.compile("testsColor\\(([^)]+?)(?:\\(\\))?\\)");

    static boolean writesAboutStudentsInThirdPerson(String problemStatement) {
        return THIRD_PERSON_STUDENTS.matcher(problemStatement).find();
    }

    /** A title names one seam, so a repeat means tests were split one-per-task instead of grouped. */
    static List<String> duplicateTaskTitles(String problemStatement) {
        return TASK_TITLE.matcher(withoutMarkdownCode(problemStatement)).results().map(match -> match.group(1).strip()).collect(Collectors.groupingBy(title -> title)).entrySet()
                .stream().filter(entry -> entry.getValue().size() > 1).map(Map.Entry::getKey).sorted().toList();
    }

    /** A {@code testsColor} name matching no test is a silently dead interactive diagram link. */
    static List<String> unresolvedTestsColorNames(String problemStatement, List<String> actualTestNames, Set<String> seededStructuralTestNames) {
        Set<String> known = new HashSet<>(actualTestNames);
        known.addAll(seededStructuralTestNames);
        return TESTS_COLOR_NAME.matcher(problemStatement).results().map(match -> match.group(1).strip()).distinct().filter(name -> !known.contains(name)).sorted().toList();
    }

    /** Artemis renders a directive outside every {@code @startuml}...{@code @enduml} block as stray statement text. */
    static boolean hasStrayPlantUmlDirectives(String problemStatement) {
        boolean insideDiagram = false;
        for (String line : problemStatement.lines().map(String::strip).toList()) {
            if (line.startsWith("@startuml")) {
                insideDiagram = true;
            }
            else if (line.startsWith("@enduml")) {
                insideDiagram = false;
            }
            else if (!insideDiagram && (line.startsWith("hide empty") || line.startsWith("skinparam "))) {
                return true;
            }
        }
        return false;
    }

    /** Whether the first non-blank line of the specification's bounded {@code ## Diagram} section declares "yes". */
    static boolean specPromisesDiagram(String spec) {
        int index = spec.indexOf("## Diagram");
        if (index < 0) {
            return false;
        }
        String section = spec.substring(index + "## Diagram".length());
        int nextHeading = section.indexOf("## ");
        if (nextHeading >= 0) {
            section = section.substring(0, nextHeading);
        }
        String decision = section.lines().map(String::strip).filter(line -> !line.isBlank()).findFirst().orElse("").replaceFirst("^[-*+]\\s+", "").replace("*", "").replace("_", "")
                .strip();
        return decision.matches("(?i)^yes(?:$|\\s|[—–:-]).*");
    }

    /** Task bindings followed only by another task, a heading, or the end of the statement, with no instruction in between. */
    static List<String> tasksWithoutInstruction(String problemStatement) {
        List<String> lines = problemStatement.lines().toList();
        List<String> bareTasks = new ArrayList<>();
        for (int index = 0; index < lines.size(); index++) {
            String task = lines.get(index).strip();
            if (!TASK_BINDING.matcher(task).find()) {
                continue;
            }
            boolean hasInstruction = false;
            for (int following = index + 1; following < lines.size(); following++) {
                String candidate = lines.get(following).strip();
                if (TASK_BINDING.matcher(candidate).find() || candidate.startsWith("#")) {
                    break;
                }
                if (!candidate.isBlank() && !candidate.startsWith("```") && !candidate.startsWith("@startuml") && !candidate.startsWith("@enduml")) {
                    hasInstruction = true;
                    break;
                }
            }
            if (!hasInstruction) {
                bareTasks.add(task);
            }
        }
        return List.copyOf(bareTasks);
    }

    /**
     * The instruction-body analogue of {@link #duplicateHeadings}. Structural lines (headings, task bindings, table rows, list markers) are excluded because other checks own
     * them, and the 60-character floor keeps legitimately repeated short lines (separators, one-word bullets, closing fences) out of the match.
     */
    static List<String> duplicateInstructionLines(String problemStatement) {
        List<String> prose = new ArrayList<>();
        boolean insideBlock = false;
        for (String rawLine : problemStatement.lines().toList()) {
            String line = rawLine.strip();
            if (line.startsWith("```")) {
                insideBlock = !insideBlock;
                continue;
            }
            if (line.startsWith("@startuml")) {
                insideBlock = true;
                continue;
            }
            if (line.startsWith("@enduml")) {
                insideBlock = false;
                continue;
            }
            if (insideBlock || line.length() < 60 || line.startsWith("#") || line.startsWith("|") || line.startsWith("-") || line.startsWith("*")
                    || TASK_LIKE_BINDING.matcher(line).find()) {
                continue;
            }
            prose.add(line);
        }
        return prose.stream().collect(Collectors.groupingBy(line -> line)).entrySet().stream().filter(entry -> entry.getValue().size() > 1).map(Map.Entry::getKey).sorted()
                .toList();
    }

    /** Every markdown heading line that appears more than once verbatim. */
    static List<String> duplicateHeadings(String problemStatement) {
        return problemStatement.lines().map(String::strip).filter(line -> line.startsWith("#")).collect(Collectors.groupingBy(line -> line)).entrySet().stream()
                .filter(entry -> entry.getValue().size() > 1).map(Map.Entry::getKey).sorted().toList();
    }

    static boolean hasTaskBindings(String problemStatement) {
        return TASK_BINDING.matcher(withoutMarkdownCode(problemStatement)).find();
    }

    /** Artemis masks Markdown code before expanding task bindings, so a syntactically correct marker inside code is still inert student-facing text. */
    static boolean hasTaskBindingInsideMarkdownCode(String problemStatement) {
        Matcher code = MARKDOWN_CODE.matcher(problemStatement);
        while (code.find()) {
            if (TASK_BINDING.matcher(code.group()).find()) {
                return true;
            }
        }
        return false;
    }

    /** In encounter order, preserving duplicates so the duplicate-binding gate can see them. */
    static List<String> boundTestNames(String problemStatement) {
        List<String> names = new ArrayList<>();
        Matcher matcher = TASK_BINDING.matcher(withoutMarkdownCode(problemStatement));
        while (matcher.find()) {
            for (String rawName : matcher.group(1).split(",")) {
                String name = rawName.trim();
                if (!name.isEmpty()) {
                    names.add(name);
                }
            }
        }
        return names;
    }

    static List<List<String>> boundTestGroups(String problemStatement) {
        List<List<String>> groups = new ArrayList<>();
        Matcher matcher = TASK_BINDING.matcher(withoutMarkdownCode(problemStatement));
        while (matcher.find()) {
            List<String> names = new ArrayList<>();
            for (String rawName : matcher.group(1).split(",")) {
                String name = rawName.trim();
                if (!name.isEmpty()) {
                    names.add(name);
                }
            }
            if (!names.isEmpty()) {
                groups.add(List.copyOf(names));
            }
        }
        return groups;
    }

    /**
     * Checks that task lines preserve the grading plan's student-work seams: every visible test for one seam belongs to one task, and one task never mixes seams. Hidden tests
     * are ignored because they must not occur in the statement at all. Traceability only: it says nothing about whether the seams themselves are pedagogically meaningful.
     */
    static List<String> seamTaskGroupingReasons(String problemStatement, GeneratedTestPlan plan) {
        List<GeneratedTestPlan.Entry> visible = plan.visibleEntries();
        List<String> missingSeams = visible.stream().filter(entry -> entry.seam().isBlank()).map(GeneratedTestPlan.Entry::name).toList();
        if (!missingSeams.isEmpty()) {
            return List.of("these visible tests have no seam in test-plan.json: " + missingSeams + ". Assign each one the stable S1/S2/... ID from SPEC.md.");
        }

        Map<String, List<String>> visibleTestsBySeam = visible.stream().collect(Collectors.groupingBy(GeneratedTestPlan.Entry::seam, LinkedHashMap::new,
                Collectors.mapping(GeneratedTestPlan.Entry::name, Collectors.toCollection(ArrayList::new))));
        Map<String, String> seamByTest = visible.stream()
                .collect(Collectors.toMap(entry -> normalizeTestName(entry.name()), GeneratedTestPlan.Entry::seam, (first, ignored) -> first, LinkedHashMap::new));
        Set<String> boundNames = boundTestNames(problemStatement).stream().map(ProblemStatementBindingChecker::normalizeTestName)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        Map<String, Set<Integer>> taskGroupsBySeam = new LinkedHashMap<>();
        List<String> reasons = new ArrayList<>();
        List<List<String>> groups = boundTestGroups(problemStatement);
        for (int index = 0; index < groups.size(); index++) {
            Set<String> seams = groups.get(index).stream().map(ProblemStatementBindingChecker::normalizeTestName).map(seamByTest::get).filter(Objects::nonNull)
                    .collect(Collectors.toCollection(LinkedHashSet::new));
            if (seams.size() > 1) {
                reasons.add("task " + (index + 1) + " mixes tests from unrelated seams " + seams + "; use one task per seam. Expected visible groups: "
                        + expectedGroups(seams, visibleTestsBySeam) + ".");
            }
            for (String seam : seams) {
                taskGroupsBySeam.computeIfAbsent(seam, ignored -> new LinkedHashSet<>()).add(index);
            }
        }
        for (String seam : visible.stream().map(GeneratedTestPlan.Entry::seam).distinct().toList()) {
            Set<Integer> taskGroups = taskGroupsBySeam.getOrDefault(seam, Set.of());
            List<String> expectedTests = visibleTestsBySeam.getOrDefault(seam, List.of());
            if (taskGroups.isEmpty()) {
                reasons.add("seam " + seam + " has visible tests but no [task] group; add one task binding exactly " + expectedTests + ".");
            }
            else if (taskGroups.size() > 1) {
                reasons.add("seam " + seam + " is split across " + taskGroups.size() + " [task] lines; merge them into one student task binding exactly " + expectedTests + ".");
            }
            else {
                List<String> omittedTests = visible.stream().filter(entry -> seam.equals(entry.seam())).filter(entry -> !boundNames.contains(normalizeTestName(entry.name())))
                        .map(GeneratedTestPlan.Entry::name).toList();
                if (!omittedTests.isEmpty()) {
                    reasons.add("seam " + seam + "'s [task] group omits visible tests " + omittedTests + "; its one task must bind exactly " + expectedTests + ".");
                }
            }
        }
        return List.copyOf(reasons);
    }

    private static String expectedGroups(Set<String> seams, Map<String, List<String>> visibleTestsBySeam) {
        return seams.stream().map(seam -> seam + "=" + visibleTestsBySeam.getOrDefault(seam, List.of())).collect(Collectors.joining(", "));
    }

    static List<String> malformedTaskKeywords(String problemStatement) {
        Matcher matcher = TASK_LIKE_BINDING.matcher(withoutMarkdownCode(problemStatement));
        List<String> wrongKeywords = new ArrayList<>();
        while (matcher.find()) {
            String keyword = matcher.group(1);
            if (!"task".equals(keyword) && !wrongKeywords.contains(keyword)) {
                wrongKeywords.add(keyword);
            }
        }
        return wrongKeywords;
    }

    /**
     * The {@code [task]}-bound names resolving to no real test, so a checklist that binds to nothing can be rejected. Fails open when the extracted name set is missing or
     * shorter than the test count. Only names in the authoritative seeded set count as resolved without appearing in the build report: trusting a merely structural-SHAPED name
     * would let a statement invent a fake non-grading structural task.
     */
    static List<String> unresolvedTaskBindings(String problemStatement, List<String> actualTestNames, int testCount, Set<String> seededStructuralTestNames) {
        if (actualTestNames.isEmpty() || actualTestNames.size() < testCount) {
            return List.of();
        }
        Set<String> actual = actualTestNames.stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        Set<String> seededStructural = seededStructuralTestNames == null ? Set.of()
                : seededStructuralTestNames.stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        List<String> unresolved = new ArrayList<>();
        for (String name : boundTestNames(problemStatement)) {
            String normalized = normalizeTestName(name);
            if (actual.contains(normalized) || seededStructural.contains(normalized)) {
                continue;
            }
            if (!unresolved.contains(name)) {
                unresolved.add(name);
            }
        }
        return unresolved;
    }

    static List<String> duplicateTaskBindings(String problemStatement) {
        Set<String> seen = new LinkedHashSet<>();
        List<String> duplicates = new ArrayList<>();
        for (String name : boundTestNames(problemStatement)) {
            String normalized = normalizeTestName(name);
            if (!seen.add(normalized) && !duplicates.contains(normalized)) {
                duplicates.add(normalized);
            }
        }
        return duplicates;
    }

    static List<String> unboundGradableTestNames(String problemStatement, List<String> actualTestNames, int testCount) {
        return unboundGradableTestNames(problemStatement, actualTestNames, testCount, Set.of());
    }

    /**
     * Real gradable tests production will grade but no {@code [task]} binding exposes, EXCLUDING the ones the grading plan hides until the due date. A hidden test must stay
     * unbound: binding it would render a checkbox that cannot turn green before the deadline while advertising the overfit probe. The exemption must move together with the ban on
     * mentioning hidden tests, or the two rules are jointly unsatisfiable. Empty {@code hiddenTestNames} (no readable plan) is fail-open.
     */
    static List<String> unboundGradableTestNames(String problemStatement, List<String> actualTestNames, int testCount, Set<String> hiddenTestNames) {
        if (actualTestNames.isEmpty() || actualTestNames.size() < testCount) {
            return List.of();
        }
        Set<String> bound = boundTestNames(problemStatement).stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        List<String> unbound = new ArrayList<>();
        for (String rawName : actualTestNames) {
            String normalized = normalizeTestName(rawName);
            if (bound.contains(normalized) || hiddenTestNames.contains(normalized)) {
                continue;
            }
            if (!unbound.contains(normalized)) {
                unbound.add(normalized);
            }
        }
        return unbound;
    }

    /** Real tests except build gates and tests hidden until the due date, de-duplicated in report order. */
    static List<String> bindableTestNames(List<String> actualTestNames, Set<String> hiddenTestNames) {
        Set<String> hidden = hiddenTestNames.stream().map(ProblemStatementBindingChecker::normalizeTestName).collect(Collectors.toSet());
        Set<String> bindable = new LinkedHashSet<>();
        for (String rawName : actualTestNames) {
            String normalized = normalizeTestName(rawName);
            if (!normalized.isEmpty() && !hidden.contains(normalized)) {
                bindable.add(normalized);
            }
        }
        return List.copyOf(bindable);
    }

    /** Shared by the stage gate and the acceptance oracle, so the two can never word this rule differently. */
    static String hiddenTestMentionsRejection(List<String> hiddenMentions) {
        return "The problem statement exposes tests the grading plan hides until the due date: " + hiddenMentions
                + ". A hidden test is the overfit probe: its name must not appear in tasks, diagrams, prose, or appendices, and it must stay unbound. Remove every occurrence; "
                + "describe only the public behaviour students need to implement.";
    }

    static List<String> hiddenTestMentions(String problemStatement, Set<String> hiddenTestNames) {
        if (hiddenTestNames.isEmpty()) {
            return List.of();
        }
        List<String> offenders = new ArrayList<>();
        for (String hiddenName : hiddenTestNames) {
            if (problemStatement.contains(hiddenName) && !offenders.contains(hiddenName)) {
                offenders.add(hiddenName);
            }
        }
        return offenders;
    }

    /** Opening of {@link #proseHygieneRejection}, so a caller can recognise that rejection among untyped reason strings. */
    static final String PROSE_HYGIENE_REJECTION_PREFIX = "The problem statement leaks grader internals or stray task markers into student-facing prose: ";

    /** Shared by the stage gate and the acceptance oracle, so the two can never word this rule differently. */
    static String proseHygieneRejection(List<String> leaks) {
        return PROSE_HYGIENE_REJECTION_PREFIX + leaks
                + ". Rewrite it as a student would read it — describe the required behaviour and edge cases, never how the exercise is built, tested or graded, and bind tasks "
                + "only via [task][Title](testName) lines.";
    }

    /** Surfaced verbatim to the agent so a retry can excise the exact offending text. See {@link #BARE_TASK_KEYWORD} and {@link #PROSE_MECHANICS_LEAKS}. */
    static List<String> proseHygieneLeaks(String problemStatement) {
        List<String> leaks = new ArrayList<>();
        if (BARE_TASK_KEYWORD.matcher(problemStatement).find()) {
            leaks.add("a bare [task]/[tasks] marker outside a [task][Title](testName) binding");
        }
        for (Pattern pattern : PROSE_MECHANICS_LEAKS) {
            Matcher matcher = pattern.matcher(problemStatement);
            if (matcher.find()) {
                String matched = '"' + matcher.group() + '"';
                if (!leaks.contains(matched)) {
                    leaks.add(matched);
                }
            }
        }
        return leaks;
    }

    /** Whitespace only: production task extraction matches test names exactly after trimming the comma-separated binding entries. */
    static String normalizeTestName(String name) {
        return name.trim();
    }

    private static String withoutMarkdownCode(String problemStatement) {
        return MARKDOWN_CODE.matcher(problemStatement).replaceAll("");
    }
}
