package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Conditional;
import org.springframework.context.annotation.Lazy;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import de.tum.cit.aet.artemis.buildagent.service.InteractiveSandbox;
import de.tum.cit.aet.artemis.core.service.TempFileUtilService;
import de.tum.cit.aet.artemis.hyperion.config.HyperionExerciseGenerationEnabled;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.GenerationWorkspaceService;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.WorkspaceArchive;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingExercise;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingLanguage;
import de.tum.cit.aet.artemis.programming.domain.RepositoryType;

/**
 * Adds Ares structural tests to a generated Java exercise exactly as a manually authored one carries them. For staged generation, the approved typed SPEC contract is serialized
 * directly; agent-authored implementation code never defines or expands the grading authority. A provider whose oracle section is empty is omitted, because its empty dynamic
 * factory is reported under the shared method name {@code generateTestsForAllClasses} and would create duplicate production test cases instead of a useful structural check.
 * <p>
 * Without an approved specification, candidate repository differences are never treated as authority. Existing instructor-authored structural assets remain untouched.
 */
@Lazy
@Service
@Conditional(HyperionExerciseGenerationEnabled.class)
public class StructuralOracleSeedingService {

    private static final Logger log = LoggerFactory.getLogger(StructuralOracleSeedingService.class);

    private static final String STRUCTURAL_RESOURCE_DIR = "templates/java/test/testFiles/structural/";

    private static final List<String> STRUCTURAL_CLASSES = List.of("ClassTest.java", "MethodTest.java", "AttributeTest.java", "ConstructorTest.java");

    private static final String ORACLE_FILE = "test.json";

    private static final String GENERATED_MARKER = "// Generated by Artemis Hyperion structural oracle seeding. Safe to replace.";

    private static final String PACKAGE_PLACEHOLDER = "${packageName}";

    private static final Pattern PACKAGE_DECLARATION = Pattern.compile("(?m)^\\s*package\\s+([\\w.]+)\\s*;");

    private static final ObjectMapper MAPPER = new ObjectMapper();

    /** Captures the optional {@code public} modifier, because only a public solution type may be seeded. */
    private static final Pattern TYPE_DECLARATION = Pattern
            .compile("(?m)(?:^|\\s)(public\\s+)?(?:abstract\\s+|final\\s+|sealed\\s+|non-sealed\\s+|strictfp\\s+)*(?:class|interface|enum|record)\\s+(\\w+)");

    private final GenerationWorkspaceService workspace;

    private final TempFileUtilService tempFileUtilService;

    private final ApprovedSpecRegistry approvedSpecs;

    private final Map<String, BaselineStructuralBundle> baselineBundles = new ConcurrentHashMap<>();

    @Autowired
    public StructuralOracleSeedingService(GenerationWorkspaceService workspace, TempFileUtilService tempFileUtilService, ApprovedSpecRegistry approvedSpecs) {
        this.workspace = workspace;
        this.tempFileUtilService = tempFileUtilService;
        this.approvedSpecs = approvedSpecs;
    }

    StructuralOracleSeedingService(GenerationWorkspaceService workspace, TempFileUtilService tempFileUtilService) {
        this(workspace, tempFileUtilService, new ApprovedSpecRegistry());
    }

    /**
     * Freezes the instructor-authored structural bundle before the first model call. Runs without a SPEC (ADAPT or an explicitly unstaged run) may restore this exact bundle,
     * but can never infer a new grading contract from candidate code.
     *
     * @param sessionId  the sandbox session whose immutable baseline is captured
     * @param testsFiles the complete tests repository before agent authoring
     */
    public void captureBaseline(String sessionId, Map<String, String> testsFiles) {
        if (sessionId == null) {
            return;
        }
        Map<String, String> files = testsFiles == null ? Map.of() : testsFiles;
        Set<String> structuralDirectories = structuralBundleDirectories(files, true);
        Map<String, String> assets = new LinkedHashMap<>();
        files.forEach((path, content) -> {
            if (structuralDirectories.contains(directory(path)) && isRecognizedStructuralAsset(path, content)) {
                assets.put(path, content);
            }
        });
        if (assets.isEmpty()) {
            freezeBaseline(sessionId, BaselineStructuralBundle.EMPTY);
            return;
        }

        Set<String> names = new LinkedHashSet<>();
        boolean valid = true;
        for (Map.Entry<String, String> oracle : assets.entrySet().stream().filter(entry -> entry.getKey().endsWith("/" + ORACLE_FILE) || ORACLE_FILE.equals(entry.getKey()))
                .toList()) {
            try {
                String oracleDirectory = directory(oracle.getKey());
                String prefix = oracleDirectory.isEmpty() ? "" : oracleDirectory + "/";
                List<String> providers = requiredStructuralClasses(oracle.getValue());
                if (!providers.stream().allMatch(provider -> assets.containsKey(prefix + provider))) {
                    valid = false;
                    log.warn("Ignoring incomplete baseline structural bundle for session {} in {}", sessionId, oracleDirectory);
                    break;
                }
                names.addAll(structuralTestNames(oracle.getValue()));
            }
            catch (IOException | RuntimeException exception) {
                valid = false;
                log.warn("Ignoring malformed baseline structural oracle for session {}: {}", sessionId, exception.getMessage());
                break;
            }
        }
        freezeBaseline(sessionId, new BaselineStructuralBundle(Map.copyOf(assets), valid ? Set.copyOf(names) : Set.of()));
    }

    private void freezeBaseline(String sessionId, BaselineStructuralBundle baseline) {
        BaselineStructuralBundle previous = baselineBundles.putIfAbsent(sessionId, baseline);
        if (previous != null && !previous.equals(baseline)) {
            throw new IllegalStateException("The pre-authoring structural baseline for session " + sessionId + " was already captured and cannot be replaced");
        }
    }

    /**
     * Generates the structure oracle and seeds the structural tests when the structures differ; Java only, and a no-op for other languages.
     * <p>
     * The returned names are derived from the oracle this service generated, never from anything the agent wrote, so the agent cannot grow the set to smuggle a behaviour test
     * into structural-test handling. The verifier keys its starter-credit and task-binding exemptions to exactly this set.
     *
     * @param sandbox   the live sandbox session holding the produced files
     * @param sessionId the session id
     * @param exercise  the exercise being generated
     * @return the structural test-case names seeded this run (empty when none)
     */
    public Set<String> seedIfStructuralDiff(InteractiveSandbox sandbox, String sessionId, ProgrammingExercise exercise) {
        if (exercise.getProgrammingLanguage() != ProgrammingLanguage.JAVA) {
            return Set.of();
        }
        var approvedSpecification = approvedSpecs.approved(sessionId);
        Set<String> expectedStudentCreatedTypes = approvedSpecification.map(StageCheckService::specStudentCreatedTypes).map(Set::copyOf).orElse(Set.of());
        if (approvedSpecification.isEmpty()) {
            return restoreBaselineStructuralBundle(sandbox, sessionId);
        }
        Set<String> allowedDesignTypes = StageCheckService.designTableRows(approvedSpecification.get()).stream().map(StageCheckService.DesignRow::type)
                .collect(java.util.stream.Collectors.toSet());
        ApprovedStructuralContract.ParseResult parsedContract = ApprovedStructuralContract.parse(approvedSpecification.get(), allowedDesignTypes, expectedStudentCreatedTypes);
        if (!parsedContract.valid()) {
            throw new IllegalStateException("The approved Java Public API contract is invalid: " + parsedContract.errors());
        }
        boolean managedAssetsDetected = false;
        try {
            Map<String, String> testFiles = workspace.extractRepositoryFiles(sandbox, sessionId, RepositoryType.TESTS);
            String packageName = exercise.getPackageName() == null ? "" : exercise.getPackageName();
            String testDirectory = locateStructuralAssetDirectory(testFiles);
            if (testDirectory == null) {
                testDirectory = canonicalJavaTestDirectory(packageName);
            }
            StructuralAssetOwnership ownership = structuralAssetOwnership(testFiles, testDirectory);
            managedAssetsDetected = ownership == StructuralAssetOwnership.HYPERION_MANAGED;
            if (ownership == StructuralAssetOwnership.UNMANAGED) {
                if (expectedStudentCreatedTypes.isEmpty()) {
                    log.info("Preserving existing structural test assets for exercise {} because they are not managed by Hyperion", exercise.getId());
                    return Set.of();
                }
                throw new IllegalStateException("The tests repository already contains structural Ares assets not managed by Hyperion. Refusing to overwrite the existing "
                        + "grading harness while materializing approved student-created types " + expectedStudentCreatedTypes);
            }

            String oracle = parsedContract.contract().toOracle(packageName, MAPPER, expectedStudentCreatedTypes);

            if (isStructurallyEmpty(oracle)) {
                if (!expectedStudentCreatedTypes.isEmpty()) {
                    throw new IllegalStateException(
                            "The approved student-created types could not be materialized as public structural requirements: " + expectedStudentCreatedTypes);
                }
                if (managedAssetsDetected && !cleanupStructuralFiles(sandbox, sessionId, testDirectory)) {
                    throw new IllegalStateException("The previous Hyperion-managed structural assets could not be removed");
                }
                return Set.of();
            }

            Map<String, String> seededFiles = new LinkedHashMap<>();
            String dirPrefix = GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/" + testDirectory;
            seededFiles.put(dirPrefix + "/" + ORACLE_FILE, oracle);
            List<String> requiredStructuralClasses = requiredStructuralClasses(oracle);
            for (String className : requiredStructuralClasses) {
                seededFiles.put(dirPrefix + "/" + className, structuralClassContent(className, packageName));
            }
            if (managedAssetsDetected && !cleanupStructuralFiles(sandbox, sessionId, testDirectory)) {
                throw new IllegalStateException("The previous Hyperion-managed structural assets could not be removed before refresh");
            }
            sandbox.copyIn(sessionId, GenerationWorkspaceService.WORKSPACE, WorkspaceArchive.buildWorkspaceTarStream(seededFiles, Map.of()));
            Set<String> seededTestNames = structuralTestNames(oracle);
            List<String> missingExpectedTypes = expectedStudentCreatedTypes.stream().filter(type -> !seededTestNames.contains("testClass[" + type + "]")).sorted().toList();
            if (!missingExpectedTypes.isEmpty()) {
                throw new IllegalStateException("No public structural oracle could be generated for approved student-created type(s) " + missingExpectedTypes);
            }
            log.info("Seeded {} structural test classes and a structure oracle for exercise {} (package '{}'), structural test names {}", requiredStructuralClasses.size(),
                    exercise.getId(), packageName, seededTestNames);
            return seededTestNames;
        }
        catch (RuntimeException | IOException e) {
            log.warn("Could not seed structural tests for exercise {}: {}", exercise.getId(), e.getMessage());
            if (!expectedStudentCreatedTypes.isEmpty() || managedAssetsDetected) {
                throw new IllegalStateException("Could not safely materialize the structural grading contract"
                        + (expectedStudentCreatedTypes.isEmpty() ? "" : " for approved student-created type(s) " + expectedStudentCreatedTypes) + ": " + e.getMessage(), e);
            }
            return Set.of();
        }
    }

    private Set<String> restoreBaselineStructuralBundle(InteractiveSandbox sandbox, String sessionId) {
        BaselineStructuralBundle baseline = sessionId == null ? null : baselineBundles.get(sessionId);
        if (baseline == null) {
            throw new IllegalStateException(
                    "No pre-authoring structural baseline was captured for session " + sessionId + "; refusing to derive grading authority from mutable candidate code");
        }
        try {
            Map<String, String> liveFiles = workspace.extractRepositoryFiles(sandbox, sessionId, RepositoryType.TESTS);
            Set<String> liveDirectories = structuralBundleDirectories(liveFiles, false);
            Map<String, String> liveAssets = new LinkedHashMap<>();
            liveFiles.forEach((path, content) -> {
                if (liveDirectories.contains(directory(path)) && isRecognizedStructuralAsset(path, content)) {
                    liveAssets.put(path, content);
                }
            });
            boolean baselineIntact = baseline.assets().entrySet().stream().allMatch(entry -> entry.getValue().equals(liveFiles.get(entry.getKey())))
                    && liveAssets.keySet().stream().allMatch(baseline.assets()::containsKey);
            if (baselineIntact) {
                return baseline.testNames();
            }
            for (String directory : liveDirectories) {
                if (!cleanupStructuralFiles(sandbox, sessionId, directory)) {
                    throw new IllegalStateException("The unapproved structural bundle could not be removed");
                }
            }
            if (!baseline.assets().isEmpty()) {
                Map<String, String> workspaceFiles = new LinkedHashMap<>();
                baseline.assets().forEach((path, content) -> workspaceFiles.put(GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/" + path, content));
                sandbox.copyIn(sessionId, GenerationWorkspaceService.WORKSPACE, WorkspaceArchive.buildWorkspaceTarStream(workspaceFiles, Map.of()));
            }
            return baseline.testNames();
        }
        catch (RuntimeException exception) {
            throw new IllegalStateException("Could not restore the pre-authoring structural grading bundle: " + exception.getMessage(), exception);
        }
    }

    /**
     * Drops the immutable oracle when its sandbox session ends.
     *
     * @param sessionId the finished sandbox session
     */
    public void forget(String sessionId) {
        if (sessionId != null) {
            baselineBundles.remove(sessionId);
        }
    }

    private record BaselineStructuralBundle(Map<String, String> assets, Set<String> testNames) {

        private static final BaselineStructuralBundle EMPTY = new BaselineStructuralBundle(Map.of(), Set.of());
    }

    /**
     * The exact Ares dynamic-test names the seeded providers report at runtime: every retained class has {@code testClass[<ClassName>]}, while member names exist only where that
     * oracle section is non-empty. Reconstructed from the oracle rather than matched by name shape, which the agent could imitate.
     */
    private static Set<String> structuralTestNames(String oracle) throws IOException {
        Set<String> names = new LinkedHashSet<>();
        for (JsonNode entry : (ArrayNode) MAPPER.readTree(oracle)) {
            String className = entry.path("class").path("name").asText("");
            if (className.isEmpty()) {
                continue;
            }
            names.add("testClass[" + className + "]");
            if (hasEntries(entry, "methods")) {
                names.add("testMethods[" + className + "]");
            }
            if (hasEntries(entry, "attributes")) {
                names.add("testAttributes[" + className + "]");
            }
            if (hasEntries(entry, "constructors")) {
                names.add("testConstructors[" + className + "]");
            }
        }
        return names;
    }

    /** Only providers with at least one dynamic test to create (see class javadoc on the shared factory name). */
    private static List<String> requiredStructuralClasses(String oracle) throws IOException {
        ArrayNode entries = (ArrayNode) MAPPER.readTree(oracle);
        List<String> classes = new ArrayList<>();
        classes.add("ClassTest.java");
        if (hasEntries(entries, "methods")) {
            classes.add("MethodTest.java");
        }
        if (hasEntries(entries, "attributes")) {
            classes.add("AttributeTest.java");
        }
        if (hasEntries(entries, "constructors")) {
            classes.add("ConstructorTest.java");
        }
        return List.copyOf(classes);
    }

    private static boolean hasEntries(JsonNode entries, String field) {
        if (entries.isArray()) {
            for (JsonNode entry : entries) {
                if (hasEntries(entry, field)) {
                    return true;
                }
            }
            return false;
        }
        JsonNode values = entries.path(field);
        return values.isArray() && !values.isEmpty();
    }

    /** The first Java test file's directory, so structural tests land in the same source set and package; {@code null} when the agent wrote none. */
    private static String locateTestSourceDirectory(Map<String, String> testFiles) {
        return testFiles.keySet().stream().filter(path -> path.endsWith(".java") && path.contains("/")).map(path -> path.substring(0, path.lastIndexOf('/'))).findFirst()
                .orElse(null);
    }

    private static String locateStructuralAssetDirectory(Map<String, String> testFiles) {
        Set<String> directories = structuralBundleDirectories(testFiles, false);
        return directories.size() == 1 ? directories.iterator().next() : null;
    }

    /**
     * Structural tests are seeded before the agent authors behavioural tests, so their location cannot depend on an existing test source. The Java generation workspace has one
     * canonical test source root and mirrors the solution package beneath it.
     */
    private static String canonicalJavaTestDirectory(String packageName) {
        return packageName.isBlank() ? "test" : "test/" + packageName.replace('.', '/');
    }

    private static boolean hasStructuralFileName(String path) {
        String fileName = path.substring(path.lastIndexOf('/') + 1);
        return ORACLE_FILE.equals(fileName) || STRUCTURAL_CLASSES.contains(fileName);
    }

    private static boolean isRecognizedStructuralAsset(String path, String content) {
        String fileName = path.substring(path.lastIndexOf('/') + 1);
        if (ORACLE_FILE.equals(fileName)) {
            return isStructuralOracle(content);
        }
        if (!STRUCTURAL_CLASSES.contains(fileName)) {
            return false;
        }
        String provider = fileName.substring(0, fileName.length() - ".java".length()) + "Provider";
        return content != null && (content.contains(GENERATED_MARKER) || content.contains("extends " + provider) && content.contains("retrieveStructureOracleJSON"));
    }

    private static boolean isStructuralOracle(String content) {
        try {
            JsonNode root = MAPPER.readTree(content);
            if (!(root instanceof ArrayNode entries) || entries.isEmpty()) {
                return false;
            }
            Set<String> names = new HashSet<>();
            for (JsonNode entry : entries) {
                String name = entry.path("class").path("name").asText("");
                if (name.isBlank() || !names.add(name)) {
                    return false;
                }
            }
            return true;
        }
        catch (IOException | RuntimeException exception) {
            return false;
        }
    }

    private static Set<String> structuralBundleDirectories(Map<String, String> files, boolean requireComplete) {
        Set<String> candidates = new LinkedHashSet<>();
        files.forEach((path, content) -> {
            if (isRecognizedStructuralAsset(path, content)) {
                candidates.add(directory(path));
            }
        });
        for (String candidate : List.copyOf(candidates)) {
            String prefix = candidate.isEmpty() ? "" : candidate + "/";
            String oracle = files.get(prefix + ORACLE_FILE);
            List<String> recognizedProviders = STRUCTURAL_CLASSES.stream().filter(name -> isRecognizedStructuralAsset(prefix + name, files.get(prefix + name))).toList();
            boolean oracleValid = isStructuralOracle(oracle);
            if (requireComplete && (!oracleValid || recognizedProviders.isEmpty())) {
                throw new IllegalStateException("The pre-authoring structural bundle in '" + candidate + "' is incomplete or malformed");
            }
            if (requireComplete && oracleValid) {
                try {
                    List<String> requiredProviders = requiredStructuralClasses(oracle);
                    if (!recognizedProviders.containsAll(requiredProviders)) {
                        throw new IllegalStateException("The pre-authoring structural bundle in '" + candidate + "' is missing required provider(s) "
                                + requiredProviders.stream().filter(provider -> !recognizedProviders.contains(provider)).toList());
                    }
                }
                catch (IOException exception) {
                    throw new IllegalStateException("The pre-authoring structural oracle in '" + candidate + "' is malformed", exception);
                }
            }
        }
        return Set.copyOf(candidates);
    }

    private static String directory(String path) {
        int separator = path.lastIndexOf('/');
        return separator < 0 ? "" : path.substring(0, separator);
    }

    private Path materialize(Map<String, String> files, String prefix) throws IOException {
        Path dir = tempFileUtilService.createTempDirectory(prefix);
        for (Map.Entry<String, String> entry : files.entrySet()) {
            // qdox reads only .java sources.
            if (!entry.getKey().endsWith(".java")) {
                continue;
            }
            Path target = dir.resolve(entry.getKey()).normalize();
            if (!target.startsWith(dir)) {
                continue;
            }
            Files.createDirectories(target.getParent());
            FileUtils.writeStringToFile(target.toFile(), entry.getValue(), StandardCharsets.UTF_8);
        }
        return dir;
    }

    private String structuralClassContent(String className, String packageName) throws IOException {
        String content;
        try (var input = new ClassPathResource(STRUCTURAL_RESOURCE_DIR + className).getInputStream()) {
            content = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
        if (packageName.isEmpty()) {
            content = content.replaceFirst("(?m)^\\s*package\\s+" + Pattern.quote(PACKAGE_PLACEHOLDER) + "\\s*;\\s*\\n", "");
        }
        else {
            content = content.replace(PACKAGE_PLACEHOLDER, packageName);
        }
        return GENERATED_MARKER + "\n" + content;
    }

    private static StructuralAssetOwnership structuralAssetOwnership(Map<String, String> testFiles, String testDirectory) {
        Set<String> assetDirectories = structuralBundleDirectories(testFiles, false);
        if (assetDirectories.isEmpty()) {
            return StructuralAssetOwnership.NONE;
        }
        if (!assetDirectories.equals(Set.of(testDirectory))) {
            return StructuralAssetOwnership.UNMANAGED;
        }
        String prefix = testDirectory.isEmpty() ? "" : testDirectory + "/";
        // Ownership is decided by the marker, never by whether the asset set is complete: incomplete own output is exactly the state this service repairs.
        boolean anyUnmarkedClass = STRUCTURAL_CLASSES.stream().filter(className -> testFiles.containsKey(prefix + className))
                .anyMatch(className -> !testFiles.get(prefix + className).contains(GENERATED_MARKER));
        if (anyUnmarkedClass) {
            // Someone's hand-authored grading harness, which must never be overwritten.
            return StructuralAssetOwnership.UNMANAGED;
        }
        boolean anyMarkedClass = STRUCTURAL_CLASSES.stream().anyMatch(className -> testFiles.getOrDefault(prefix + className, "").contains(GENERATED_MARKER));
        if (anyMarkedClass) {
            return StructuralAssetOwnership.HYPERION_MANAGED;
        }
        // No structural class survives, and a bare oracle grades nothing on its own, so it is leftover rather than a harness worth protecting.
        return testFiles.containsKey(prefix + ORACLE_FILE) ? StructuralAssetOwnership.HYPERION_MANAGED : StructuralAssetOwnership.UNMANAGED;
    }

    private enum StructuralAssetOwnership {
        NONE, HYPERION_MANAGED, UNMANAGED,
    }

    private static String parsePackage(Map<String, String> solutionFiles) {
        for (Map.Entry<String, String> entry : solutionFiles.entrySet()) {
            if (!entry.getKey().endsWith(".java")) {
                continue;
            }
            Matcher matcher = PACKAGE_DECLARATION.matcher(entry.getValue());
            if (matcher.find()) {
                return matcher.group(1);
            }
        }
        return "";
    }

    /** Keeps only classes the student must create (public in the solution, absent from the template) and only their public/protected members; {@code []} when none qualify. */
    static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles) throws IOException {
        return filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles, Set.of(), false);
    }

    static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles, Set<String> approvedStudentCreatedTypes)
            throws IOException {
        return filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles, approvedStudentCreatedTypes, true);
    }

    private static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles,
            Set<String> approvedStudentCreatedTypes, boolean approvedContractPresent) throws IOException {
        if (isStructurallyEmpty(oracle)) {
            return "[]";
        }
        Set<String> templateTypes = declaredTypes(templateFiles, false);
        Set<String> publicSolutionTypes = declaredTypes(solutionFiles, true);
        ArrayNode result = MAPPER.createArrayNode();
        for (JsonNode entry : (ArrayNode) MAPPER.readTree(oracle)) {
            String className = entry.path("class").path("name").asText("");
            boolean approved = !approvedContractPresent || approvedStudentCreatedTypes.contains(className);
            if (className.isEmpty() || !approved || templateTypes.contains(className) || !publicSolutionTypes.contains(className)) {
                continue;
            }
            ObjectNode kept = ((ObjectNode) entry).deepCopy();
            stripNonPublicMembers(kept, "methods");
            stripNonPublicMembers(kept, "attributes");
            stripNonPublicMembers(kept, "constructors");
            result.add(kept);
        }
        return result.isEmpty() ? "[]" : MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(result);
    }

    /** Private and package-private members are implementation details, not part of the graded contract. */
    private static void stripNonPublicMembers(ObjectNode classEntry, String field) {
        if (!(classEntry.get(field) instanceof ArrayNode members)) {
            return;
        }
        ArrayNode kept = MAPPER.createArrayNode();
        for (JsonNode member : members) {
            JsonNode modifiers = member.path("modifiers");
            boolean isPublicApi = false;
            if (modifiers.isArray()) {
                for (JsonNode modifier : modifiers) {
                    if ("public".equals(modifier.asText()) || "protected".equals(modifier.asText())) {
                        isPublicApi = true;
                        break;
                    }
                }
            }
            if (isPublicApi) {
                kept.add(member);
            }
        }
        classEntry.set(field, kept);
    }

    /** Simple names of top-level types; when {@code publicOnly}, restricted to those declared {@code public}. */
    private static Set<String> declaredTypes(Map<String, String> files, boolean publicOnly) {
        Set<String> names = new HashSet<>();
        for (String content : files.values()) {
            Matcher matcher = TYPE_DECLARATION.matcher(content);
            while (matcher.find()) {
                if (!publicOnly || matcher.group(1) != null) {
                    names.add(matcher.group(2));
                }
            }
        }
        return names;
    }

    /** An oracle with no class diffs serialises to an empty JSON array, which means there is nothing to seed. */
    static boolean isStructurallyEmpty(String oracle) {
        if (oracle == null) {
            return true;
        }
        String trimmed = oracle.trim();
        return trimmed.isEmpty() || trimmed.equals("[]") || trimmed.equals("[ ]");
    }

    private boolean cleanupStructuralFiles(InteractiveSandbox sandbox, String sessionId, String testDirectory) {
        String dir = GenerationWorkspaceService.WORKSPACE + "/" + GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/" + testDirectory;
        List<String> command = new ArrayList<>();
        command.add("rm");
        command.add("-f");
        command.add("--");
        command.add(dir + "/" + ORACLE_FILE);
        for (String className : STRUCTURAL_CLASSES) {
            command.add(dir + "/" + className);
        }
        try {
            var result = sandbox.exec(sessionId, GenerationWorkspaceService.SANDBOX_READ_TIMEOUT, command.toArray(String[]::new));
            return result != null && result.isSuccess();
        }
        catch (RuntimeException e) {
            log.debug("Structural cleanup command failed: {}", e.getMessage());
            return false;
        }
    }

    private static void deleteQuietly(Path dir) {
        if (dir != null) {
            FileUtils.deleteQuietly(dir.toFile());
        }
    }
}
