package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Conditional;
import org.springframework.context.annotation.Lazy;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import de.tum.cit.aet.artemis.buildagent.service.InteractiveSandbox;
import de.tum.cit.aet.artemis.core.service.TempFileUtilService;
import de.tum.cit.aet.artemis.hyperion.config.HyperionExerciseGenerationEnabled;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.GenerationWorkspaceService;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.WorkspaceArchive;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingExercise;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingLanguage;
import de.tum.cit.aet.artemis.programming.domain.RepositoryType;
import de.tum.cit.aet.artemis.programming.service.structureoraclegenerator.OracleGenerator;

/**
 * Adds Ares structural tests to a generated Java exercise, like a manually authored one: runs the deterministic {@link OracleGenerator} over the produced solution and template
 * and,
 * only when their structures differ, seeds the {@code test.json} oracle plus each applicable Ares test provider ({@code ClassTest}/{@code MethodTest}/{@code AttributeTest}/
 * {@code ConstructorTest}) into the test repository. Providers whose oracle section is empty are omitted: their empty dynamic factory is reported under the common method name
 * {@code generateTestsForAllClasses}, creating duplicate production test cases instead of a useful structural check.
 * <p>
 * Conservative: seeds only for a {@code public} class the student must create (present in the solution, absent from the template), and even then only its public/protected surface,
 * so a correct behaviour-only exercise is never burdened with spurious structural requirements. Legacy/no-structure flows remain best-effort; once an approved specification
 * requires student-created types, failure is explicit because silently omitting their grading contract would publish a different exercise.
 */
@Lazy
@Service
@Conditional(HyperionExerciseGenerationEnabled.class)
public class StructuralOracleSeedingService {

    private static final Logger log = LoggerFactory.getLogger(StructuralOracleSeedingService.class);

    private static final String STRUCTURAL_RESOURCE_DIR = "templates/java/test/testFiles/structural/";

    private static final List<String> STRUCTURAL_CLASSES = List.of("ClassTest.java", "MethodTest.java", "AttributeTest.java", "ConstructorTest.java");

    private static final String ORACLE_FILE = "test.json";

    private static final String GENERATED_MARKER = "// Generated by Artemis Hyperion structural oracle seeding. Safe to replace.";

    private static final String PACKAGE_PLACEHOLDER = "${packageName}";

    private static final Pattern PACKAGE_DECLARATION = Pattern.compile("(?m)^\\s*package\\s+([\\w.]+)\\s*;");

    private static final ObjectMapper MAPPER = new ObjectMapper();

    /** Matches a top-level type declaration so we can tell whether a class exists in a source set and whether the solution declares it {@code public}. */
    private static final Pattern TYPE_DECLARATION = Pattern
            .compile("(?m)(?:^|\\s)(public\\s+)?(?:abstract\\s+|final\\s+|sealed\\s+|non-sealed\\s+|strictfp\\s+)*(?:class|interface|enum|record)\\s+(\\w+)");

    private final GenerationWorkspaceService workspace;

    private final TempFileUtilService tempFileUtilService;

    private final ApprovedSpecRegistry approvedSpecs;

    @Autowired
    public StructuralOracleSeedingService(GenerationWorkspaceService workspace, TempFileUtilService tempFileUtilService, ApprovedSpecRegistry approvedSpecs) {
        this.workspace = workspace;
        this.tempFileUtilService = tempFileUtilService;
        this.approvedSpecs = approvedSpecs;
    }

    StructuralOracleSeedingService(GenerationWorkspaceService workspace, TempFileUtilService tempFileUtilService) {
        this(workspace, tempFileUtilService, new ApprovedSpecRegistry());
    }

    /**
     * Generates the structure oracle and seeds the structural tests when the structures differ. Java only; a no-op for other languages and on any error.
     * <p>
     * Returns the authoritative set of structural test-case names seeded this call ({@code testClass[X]} plus names for non-empty member sections), derived from the oracle this
     * service generated — not from anything the agent wrote, so the agent cannot grow it to smuggle a behaviour test into structural-test handling. The verifier uses these names
     * for starter-credit handling and task-binding resolution, while still requiring them to appear in the student checklist. Empty when nothing was seeded.
     *
     * @param sandbox   the live sandbox session holding the produced files
     * @param sessionId the session id
     * @param exercise  the exercise being generated
     * @return the structural test-case names seeded this run (empty when none)
     */
    public Set<String> seedIfStructuralDiff(InteractiveSandbox sandbox, String sessionId, ProgrammingExercise exercise) {
        if (exercise.getProgrammingLanguage() != ProgrammingLanguage.JAVA) {
            return Set.of();
        }
        var approvedSpecification = approvedSpecs.approved(sessionId);
        Set<String> expectedStudentCreatedTypes = approvedSpecification.map(StageCheckService::specStudentCreatedTypes).map(Set::copyOf).orElse(Set.of());
        Path solutionDir = null;
        Path templateDir = null;
        boolean managedAssetsDetected = false;
        try {
            Map<String, String> solutionFiles = workspace.extractRepositoryFiles(sandbox, sessionId, RepositoryType.SOLUTION);
            Map<String, String> templateFiles = workspace.extractRepositoryFiles(sandbox, sessionId, RepositoryType.TEMPLATE);
            Map<String, String> testFiles = workspace.extractRepositoryFiles(sandbox, sessionId, RepositoryType.TESTS);
            if (solutionFiles.isEmpty() || templateFiles.isEmpty()) {
                return Set.of();
            }
            String packageName = parsePackage(solutionFiles);
            String testDirectory = locateStructuralAssetDirectory(testFiles);
            if (testDirectory == null) {
                testDirectory = locateTestSourceDirectory(testFiles);
            }
            if (testDirectory == null) {
                testDirectory = canonicalJavaTestDirectory(packageName);
            }
            StructuralAssetOwnership ownership = structuralAssetOwnership(testFiles, testDirectory);
            managedAssetsDetected = ownership == StructuralAssetOwnership.HYPERION_MANAGED;
            if (ownership == StructuralAssetOwnership.UNMANAGED) {
                if (expectedStudentCreatedTypes.isEmpty()) {
                    log.info("Preserving existing structural test assets for exercise {} because they are not managed by Hyperion", exercise.getId());
                    return Set.of();
                }
                throw new IllegalStateException("The tests repository already contains structural Ares assets not managed by Hyperion. Refusing to overwrite the existing "
                        + "grading harness while materializing approved student-created types " + expectedStudentCreatedTypes);
            }

            solutionDir = materialize(solutionFiles, "hyperion-oracle-solution-");
            templateDir = materialize(templateFiles, "hyperion-oracle-template-");
            String oracle = filterOracleToCreatedPublicApi(OracleGenerator.generateStructureOracleJSON(solutionDir, templateDir), templateFiles, solutionFiles,
                    expectedStudentCreatedTypes, approvedSpecification.isPresent());

            if (isStructurallyEmpty(oracle)) {
                if (!expectedStudentCreatedTypes.isEmpty()) {
                    throw new IllegalStateException(
                            "The approved student-created types could not be materialized as public structural requirements: " + expectedStudentCreatedTypes);
                }
                if (managedAssetsDetected && !cleanupStructuralFiles(sandbox, sessionId, testDirectory)) {
                    throw new IllegalStateException("The previous Hyperion-managed structural assets could not be removed");
                }
                return Set.of();
            }

            Map<String, String> seededFiles = new LinkedHashMap<>();
            String dirPrefix = GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/" + testDirectory;
            seededFiles.put(dirPrefix + "/" + ORACLE_FILE, oracle);
            List<String> requiredStructuralClasses = requiredStructuralClasses(oracle);
            for (String className : requiredStructuralClasses) {
                seededFiles.put(dirPrefix + "/" + className, structuralClassContent(className, packageName));
            }
            if (managedAssetsDetected && !cleanupStructuralFiles(sandbox, sessionId, testDirectory)) {
                throw new IllegalStateException("The previous Hyperion-managed structural assets could not be removed before refresh");
            }
            sandbox.copyIn(sessionId, GenerationWorkspaceService.WORKSPACE, WorkspaceArchive.buildWorkspaceTarStream(seededFiles, Map.of()));
            Set<String> seededTestNames = structuralTestNames(oracle);
            List<String> missingExpectedTypes = expectedStudentCreatedTypes.stream().filter(type -> !seededTestNames.contains("testClass[" + type + "]")).sorted().toList();
            if (!missingExpectedTypes.isEmpty()) {
                throw new IllegalStateException("No public structural oracle could be generated for approved student-created type(s) " + missingExpectedTypes);
            }
            log.info("Seeded {} structural test classes and a structure oracle for exercise {} (package '{}'), structural test names {}", requiredStructuralClasses.size(),
                    exercise.getId(), packageName, seededTestNames);
            return seededTestNames;
        }
        catch (RuntimeException | IOException e) {
            log.warn("Could not seed structural tests for exercise {}: {}", exercise.getId(), e.getMessage());
            if (!expectedStudentCreatedTypes.isEmpty() || managedAssetsDetected) {
                throw new IllegalStateException("Could not safely materialize the structural grading contract"
                        + (expectedStudentCreatedTypes.isEmpty() ? "" : " for approved student-created type(s) " + expectedStudentCreatedTypes) + ": " + e.getMessage(), e);
            }
            return Set.of();
        }
        finally {
            deleteQuietly(solutionDir);
            deleteQuietly(templateDir);
        }
    }

    /**
     * The exact Ares dynamic-test names the applicable structural providers report at runtime. Every retained class has {@code testClass[<ClassName>]}; method, attribute, and
     * constructor names exist only when that oracle section is non-empty. Reconstructed from the oracle this service produced so the verifier's exemption is keyed to a
     * forgery-resistant authority, not a name pattern the agent could imitate.
     */
    private static Set<String> structuralTestNames(String oracle) throws IOException {
        Set<String> names = new LinkedHashSet<>();
        for (JsonNode entry : (ArrayNode) MAPPER.readTree(oracle)) {
            String className = entry.path("class").path("name").asText("");
            if (className.isEmpty()) {
                continue;
            }
            names.add("testClass[" + className + "]");
            if (hasEntries(entry, "methods")) {
                names.add("testMethods[" + className + "]");
            }
            if (hasEntries(entry, "attributes")) {
                names.add("testAttributes[" + className + "]");
            }
            if (hasEntries(entry, "constructors")) {
                names.add("testConstructors[" + className + "]");
            }
        }
        return names;
    }

    /** Seeds only Ares providers that have at least one dynamic test to create; an empty provider is reported under its shared factory name and creates duplicate test cases. */
    private static List<String> requiredStructuralClasses(String oracle) throws IOException {
        ArrayNode entries = (ArrayNode) MAPPER.readTree(oracle);
        List<String> classes = new ArrayList<>();
        classes.add("ClassTest.java");
        if (hasEntries(entries, "methods")) {
            classes.add("MethodTest.java");
        }
        if (hasEntries(entries, "attributes")) {
            classes.add("AttributeTest.java");
        }
        if (hasEntries(entries, "constructors")) {
            classes.add("ConstructorTest.java");
        }
        return List.copyOf(classes);
    }

    private static boolean hasEntries(JsonNode entries, String field) {
        if (entries.isArray()) {
            for (JsonNode entry : entries) {
                if (hasEntries(entry, field)) {
                    return true;
                }
            }
            return false;
        }
        JsonNode values = entries.path(field);
        return values.isArray() && !values.isEmpty();
    }

    /**
     * The directory of the first {@code .java} test file (so structural tests land in the same source set and package), or {@code null} if the agent wrote no Java test file.
     */
    private static String locateTestSourceDirectory(Map<String, String> testFiles) {
        return testFiles.keySet().stream().filter(path -> path.endsWith(".java") && path.contains("/")).map(path -> path.substring(0, path.lastIndexOf('/'))).findFirst()
                .orElse(null);
    }

    private static String locateStructuralAssetDirectory(Map<String, String> testFiles) {
        return testFiles.keySet().stream().filter(StructuralOracleSeedingService::isStructuralAsset).map(StructuralOracleSeedingService::directory).findFirst().orElse(null);
    }

    /**
     * Structural tests are seeded before the agent authors behavioral tests, so their location cannot depend on an existing test source. The Java generation workspace has one
     * canonical test source root ({@code test/}) and mirrors the solution package beneath it.
     */
    private static String canonicalJavaTestDirectory(String packageName) {
        return packageName.isBlank() ? "test" : "test/" + packageName.replace('.', '/');
    }

    private static boolean isStructuralAsset(String path) {
        String fileName = path.substring(path.lastIndexOf('/') + 1);
        return ORACLE_FILE.equals(fileName) || STRUCTURAL_CLASSES.contains(fileName);
    }

    private static String directory(String path) {
        int separator = path.lastIndexOf('/');
        return separator < 0 ? "" : path.substring(0, separator);
    }

    private Path materialize(Map<String, String> files, String prefix) throws IOException {
        Path dir = tempFileUtilService.createTempDirectory(prefix);
        for (Map.Entry<String, String> entry : files.entrySet()) {
            // qdox only needs the .java sources.
            if (!entry.getKey().endsWith(".java")) {
                continue;
            }
            Path target = dir.resolve(entry.getKey()).normalize();
            if (!target.startsWith(dir)) {
                continue;
            }
            Files.createDirectories(target.getParent());
            FileUtils.writeStringToFile(target.toFile(), entry.getValue(), StandardCharsets.UTF_8);
        }
        return dir;
    }

    private String structuralClassContent(String className, String packageName) throws IOException {
        String content;
        try (var input = new ClassPathResource(STRUCTURAL_RESOURCE_DIR + className).getInputStream()) {
            content = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
        if (packageName.isEmpty()) {
            content = content.replaceFirst("(?m)^\\s*package\\s+" + Pattern.quote(PACKAGE_PLACEHOLDER) + "\\s*;\\s*\\n", "");
        }
        else {
            content = content.replace(PACKAGE_PLACEHOLDER, packageName);
        }
        return GENERATED_MARKER + "\n" + content;
    }

    private static StructuralAssetOwnership structuralAssetOwnership(Map<String, String> testFiles, String testDirectory) {
        Set<String> assetDirectories = new HashSet<>();
        testFiles.keySet().stream().filter(StructuralOracleSeedingService::isStructuralAsset).map(StructuralOracleSeedingService::directory).forEach(assetDirectories::add);
        if (assetDirectories.isEmpty()) {
            return StructuralAssetOwnership.NONE;
        }
        if (!assetDirectories.equals(Set.of(testDirectory))) {
            return StructuralAssetOwnership.UNMANAGED;
        }
        String prefix = testDirectory.isEmpty() ? "" : testDirectory + "/";
        // Ownership is decided by the marker, never by whether the asset set is complete: incomplete own output is exactly the state this service repairs.
        boolean anyUnmarkedClass = STRUCTURAL_CLASSES.stream().filter(className -> testFiles.containsKey(prefix + className))
                .anyMatch(className -> !testFiles.get(prefix + className).contains(GENERATED_MARKER));
        if (anyUnmarkedClass) {
            // A structural class this service did not write. That is someone's hand-authored grading harness, and it must never be overwritten.
            return StructuralAssetOwnership.UNMANAGED;
        }
        boolean anyMarkedClass = STRUCTURAL_CLASSES.stream().anyMatch(className -> testFiles.getOrDefault(prefix + className, "").contains(GENERATED_MARKER));
        if (anyMarkedClass) {
            return StructuralAssetOwnership.HYPERION_MANAGED;
        }
        // No structural class survives. A bare oracle file grades nothing on its own, so it is this service's leftover rather than a harness worth protecting.
        return testFiles.containsKey(prefix + ORACLE_FILE) ? StructuralAssetOwnership.HYPERION_MANAGED : StructuralAssetOwnership.UNMANAGED;
    }

    private enum StructuralAssetOwnership {
        NONE, HYPERION_MANAGED, UNMANAGED,
    }

    private static String parsePackage(Map<String, String> solutionFiles) {
        for (Map.Entry<String, String> entry : solutionFiles.entrySet()) {
            if (!entry.getKey().endsWith(".java")) {
                continue;
            }
            Matcher matcher = PACKAGE_DECLARATION.matcher(entry.getValue());
            if (matcher.find()) {
                return matcher.group(1);
            }
        }
        return "";
    }

    /**
     * Filters the raw oracle to entries whose class is a {@code public} solution type absent from the template (a class the student must create), keeping only public/protected
     * members. Returns {@code []} when nothing qualifies.
     */
    static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles) throws IOException {
        return filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles, Set.of(), false);
    }

    static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles, Set<String> approvedStudentCreatedTypes)
            throws IOException {
        return filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles, approvedStudentCreatedTypes, true);
    }

    private static String filterOracleToCreatedPublicApi(String oracle, Map<String, String> templateFiles, Map<String, String> solutionFiles,
            Set<String> approvedStudentCreatedTypes, boolean approvedContractPresent) throws IOException {
        if (isStructurallyEmpty(oracle)) {
            return "[]";
        }
        Set<String> templateTypes = declaredTypes(templateFiles, false);
        Set<String> publicSolutionTypes = declaredTypes(solutionFiles, true);
        ArrayNode result = MAPPER.createArrayNode();
        for (JsonNode entry : (ArrayNode) MAPPER.readTree(oracle)) {
            String className = entry.path("class").path("name").asText("");
            boolean approved = !approvedContractPresent || approvedStudentCreatedTypes.contains(className);
            if (className.isEmpty() || !approved || templateTypes.contains(className) || !publicSolutionTypes.contains(className)) {
                continue;
            }
            ObjectNode kept = ((ObjectNode) entry).deepCopy();
            stripNonPublicMembers(kept, "methods");
            stripNonPublicMembers(kept, "attributes");
            stripNonPublicMembers(kept, "constructors");
            result.add(kept);
        }
        return result.isEmpty() ? "[]" : MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(result);
    }

    /** Drops members whose modifiers do not include {@code public} or {@code protected}; private/package-private members are implementation details, not part of the contract. */
    private static void stripNonPublicMembers(ObjectNode classEntry, String field) {
        if (!(classEntry.get(field) instanceof ArrayNode members)) {
            return;
        }
        ArrayNode kept = MAPPER.createArrayNode();
        for (JsonNode member : members) {
            JsonNode modifiers = member.path("modifiers");
            boolean isPublicApi = false;
            if (modifiers.isArray()) {
                for (JsonNode modifier : modifiers) {
                    if ("public".equals(modifier.asText()) || "protected".equals(modifier.asText())) {
                        isPublicApi = true;
                        break;
                    }
                }
            }
            if (isPublicApi) {
                kept.add(member);
            }
        }
        classEntry.set(field, kept);
    }

    /** The simple names of top-level types declared across the given sources; when {@code publicOnly}, only types declared {@code public}. */
    private static Set<String> declaredTypes(Map<String, String> files, boolean publicOnly) {
        Set<String> names = new HashSet<>();
        for (String content : files.values()) {
            Matcher matcher = TYPE_DECLARATION.matcher(content);
            while (matcher.find()) {
                if (!publicOnly || matcher.group(1) != null) {
                    names.add(matcher.group(2));
                }
            }
        }
        return names;
    }

    /** An oracle with no class diffs serialises to an empty JSON array; treat that as "nothing to seed". */
    static boolean isStructurallyEmpty(String oracle) {
        if (oracle == null) {
            return true;
        }
        String trimmed = oracle.trim();
        return trimmed.isEmpty() || trimmed.equals("[]") || trimmed.equals("[ ]");
    }

    private boolean cleanupStructuralFiles(InteractiveSandbox sandbox, String sessionId, String testDirectory) {
        String dir = GenerationWorkspaceService.WORKSPACE + "/" + GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/" + testDirectory;
        StringBuilder command = new StringBuilder("rm -f");
        command.append(" \"").append(dir).append("/").append(ORACLE_FILE).append("\"");
        for (String className : STRUCTURAL_CLASSES) {
            command.append(" \"").append(dir).append("/").append(className).append("\"");
        }
        try {
            var result = sandbox.exec(sessionId, GenerationWorkspaceService.SANDBOX_READ_TIMEOUT, "sh", "-c", command.toString());
            return result != null && result.isSuccess();
        }
        catch (RuntimeException e) {
            log.debug("Structural cleanup command failed: {}", e.getMessage());
            return false;
        }
    }

    private static void deleteQuietly(Path dir) {
        if (dir != null) {
            FileUtils.deleteQuietly(dir.toFile());
        }
    }
}
