#!/usr/bin/env python3
"""
Cuts a new Liquibase baseline: folds every changelog listed in master.xml into one initial schema,
files the folded changelogs under history/, and rewrites master.xml.

A baseline is *added* alongside the history it folds, never written over it. Nothing that a deployed
database already recorded changes, so this can be run whenever the changelog directory has grown
inconvenient rather than once per major release.

    python3 supporting_scripts/liquibase/cut_baseline.py --generation v10
    python3 supporting_scripts/liquibase/verify_schema.py

The second command is not optional. This script is a source-to-source transformation with no database
anywhere near it, so the only thing that establishes that the baseline it produced is the schema the
changelogs describe is the converge check.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from schema_state import NAMESPACE, Column, Schema, Table, UnsupportedChange  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
LIQUIBASE_DIR = REPO / "src/main/resources/config/liquibase"
RESOURCE_ROOT = REPO / "src/main/resources"

CHANGESET = f"{NAMESPACE}changeSet"
PRECONDITIONS = f"{NAMESPACE}preConditions"
DBMS = f"{NAMESPACE}dbms"
ROLLBACK = f"{NAMESPACE}rollback"
COMMENT = f"{NAMESPACE}comment"
VALID_CHECKSUM = f"{NAMESPACE}validCheckSum"
MODIFY_SQL = f"{NAMESPACE}modifySql"

MYSQL_FAMILY = {"mysql", "mariadb", "h2"}
POSTGRES_FAMILY = {"postgresql"}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd"
                   logicalFilePath="config/liquibase/baseline/{generation}_initial_schema.xml">

    <!--
        Generated by supporting_scripts/liquibase/cut_baseline.py. Do not edit by hand: the next cut
        regenerates it, and the converge check in verify_schema.py is what proves it correct.

        Three changesets, because a handful of columns cannot have one type on both supported databases:
          {generation}-01  everything both databases express the same way
          {generation}-02  MySQL and H2 only, for the columns those spell differently
          {generation}-03  PostgreSQL only, for the same columns

        Each is guarded so that it marks itself as ran, rather than executing, on a database that
        already has this schema from the changelogs under history/.
    -->
"""


# --- Reading the manifest --------------------------------------------------------------------------


def foldable_changelogs(master: Path) -> list[Path]:
    """
    Returns what the next baseline has to fold, in the order master.xml applies it.

    That is the current baseline followed by the changelogs written since, and nothing else. The folded
    history is deliberately skipped: the current baseline already *is* that history, so replaying both
    would apply the same schema twice. Seed data is skipped because a baseline runs against an empty
    database, where there is nothing to seed for.
    """
    paths = []
    for match in re.finditer(r'<include\s+file="([^"]+)"', master.read_text()):
        reference = match.group(1).removeprefix("classpath:")
        if "/history/" in reference or "/data/" in reference:
            continue
        paths.append(RESOURCE_ROOT / reference)
    return paths


def changeset_engines(changeset) -> set[str]:
    """
    Returns the engine families a changeset's ``dbms`` *attribute* restricts it to.

    The ``<dbms>`` precondition is deliberately not read here. Answering what it means requires
    understanding the ``<not>`` and ``<or>`` around it, which the precondition evaluator in
    schema_state already does; a second, simpler reading of the same elements would disagree with it at
    exactly one spelling -- ``<not><dbms type="postgresql"/></not>``, which scopes a changeset *to*
    MySQL while naming PostgreSQL. Collecting names out of the tree would read that backwards and drop
    the changeset from the MySQL baseline without saying so.
    """
    named = {value.strip().lower() for value in (changeset.get("dbms") or "").split(",") if value.strip()}
    if not named:
        return {"mysql", "postgres"}
    engines = set()
    if named & MYSQL_FAMILY:
        engines.add("mysql")
    if named & POSTGRES_FAMILY:
        engines.add("postgres")
    return engines


def scopes_by_database(preconditions) -> bool:
    """Whether these preconditions say anything about which database they apply to."""
    return preconditions is not None and next(preconditions.iter(DBMS), None) is not None


# --- Folding ---------------------------------------------------------------------------------------


PROPERTY = f"{NAMESPACE}property"
PLACEHOLDER = re.compile(r"\$\{([^}]+)\}")


def collect_properties(root, properties: dict[str, dict[str, str]]) -> None:
    """
    Records a changelog's <property> definitions, per engine family.

    These are how a changelog gives one column a different type on each database, so a fold that left
    them unresolved would write ``${hashType}`` into the baseline. Liquibase keeps the value a property
    is first given, which is what lets a changelog name MySQL and PostgreSQL and then declare a fallback
    for everything else, so a definition only counts here if the name is still free.
    """
    for element in root:
        if element.tag != PROPERTY:
            continue
        name, value = element.get("name"), element.get("value", "")
        named = {entry.strip().lower() for entry in (element.get("dbms") or "").split(",") if entry.strip()}
        for engine, families in (("mysql", MYSQL_FAMILY), ("postgres", POSTGRES_FAMILY)):
            if named and not (named & families):
                continue
            properties[engine].setdefault(name, value)


def resolve(element, values: dict[str, str]):
    """Returns a copy of a change element with every ${property} replaced by its value for one engine."""
    def substitute(text: str) -> str:
        return PLACEHOLDER.sub(lambda match: values.get(match.group(1), match.group(0)), text)

    copy = ElementTree.Element(element.tag, {key: substitute(value) for key, value in element.attrib.items()})
    copy.text = substitute(element.text) if element.text else element.text
    copy.tail = element.tail
    for child in element:
        copy.append(resolve(child, values))
    return copy


def fold(changelogs: list[Path]) -> tuple[dict[str, Schema], list[str], set[str]]:
    """Replays every changelog onto one schema per engine family, and reports what it refused to fold."""
    schemas = {"mysql": Schema(), "postgres": Schema()}
    properties: dict[str, dict[str, str]] = {"mysql": {}, "postgres": {}}
    refusals: list[str] = []
    unknown_preconditions: set[str] = set()

    for changelog in changelogs:
        relative = changelog.relative_to(REPO)
        root = ElementTree.parse(changelog).getroot()
        collect_properties(root, properties)

        for changeset in root.iter(CHANGESET):
            identifier = changeset.get("id", "?")
            context = f"{relative}::{identifier}"

            if changeset.get("context") or changeset.get("contexts"):
                refusals.append(
                    f"{context}: gated by a context, so it must not be folded. Move it to config/liquibase/data "
                    f"and leave it in master.xml."
                )
                continue

            engines = changeset_engines(changeset)
            preconditions = changeset.find(PRECONDITIONS)

            for engine in engines:
                if preconditions is not None and not schemas[engine].satisfies(preconditions, engine, unknown_preconditions):
                    # A failing precondition means Liquibase skipped this changeset, which the fold has
                    # to do too -- but only where Liquibase would have carried on. onFail="HALT", the
                    # default, aborts the whole update instead, so a database in that state never
                    # reached the schema being folded and the fold cannot speak for it.
                    #
                    # A precondition that names a database is the exception: failing it on the other
                    # engine is how a changeset scopes itself, not a state anyone has to answer for.
                    on_fail = (preconditions.get("onFail") or "HALT").upper()
                    if on_fail not in ("MARK_RAN", "CONTINUE") and not scopes_by_database(preconditions):
                        refusals.append(f"{context}: precondition fails during the fold with onFail=\"{on_fail}\", which would abort an update rather than skip it")
                    continue
                for element in changeset:
                    if element.tag in (PRECONDITIONS, ROLLBACK, COMMENT, VALID_CHECKSUM, MODIFY_SQL):
                        continue
                    # A change element may narrow the changeset's databases further.
                    if not element_applies(element, engine):
                        continue
                    try:
                        schemas[engine].apply(resolve(element, properties[engine]), context)
                    except UnsupportedChange as error:
                        refusals.append(f"{error} (on {engine})")

    return schemas, refusals, unknown_preconditions


def element_applies(element, engine: str) -> bool:
    """Whether a change element's own dbms attribute, if it has one, includes this engine family."""
    named = {value.strip().lower() for value in (element.get("dbms") or "").split(",") if value.strip()}
    if not named:
        return True
    families = MYSQL_FAMILY if engine == "mysql" else POSTGRES_FAMILY
    return bool(named & families)


# --- Emitting --------------------------------------------------------------------------------------


def _attributes(pairs: dict[str, str]) -> str:
    return "".join(f' {key}="{_escape(value)}"' for key, value in pairs.items())


def _escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _column_xml(column: Column, indent: str) -> list[str]:
    constraints = dict(column.constraints)
    # A column that only became NOT NULL later is written back as a later ALTER, so it is created
    # nullable here. See Column.not_null_via_alter for why the order matters.
    if column.not_null_via_alter:
        constraints.pop("nullable", None)
        constraints.pop("notNullConstraintName", None)

    opening = f'{indent}<column name="{_escape(column.name)}" type="{_escape(column.type)}"{_attributes(column.attributes)}'
    if not constraints:
        return [opening + "/>"]
    return [opening + ">", f"{indent}    <constraints{_attributes(constraints)}/>", f"{indent}</column>"]


def _named_not_null_xml(table_name: str, column: Column, indent: str) -> str | None:
    if not column.not_null_via_alter:
        return None
    name = column.constraints.get("notNullConstraintName")
    named = f' constraintName="{_escape(name)}"' if name else ""
    return (
        f'{indent}<addNotNullConstraint tableName="{_escape(table_name)}" columnName="{_escape(column.name)}" '
        f'columnDataType="{_escape(column.type)}"{named}/>'
    )


def _create_table_xml(table: Table, columns: list[Column], indent: str) -> list[str]:
    lines = [f'{indent}<createTable tableName="{_escape(table.name)}">']
    for column in columns:
        lines += _column_xml(column, indent + "    ")
    lines.append(f"{indent}</createTable>")
    return lines


def _index_xml(index, indent: str) -> list[str]:
    unique = ' unique="true"' if index.unique else ""
    lines = [f'{indent}<createIndex indexName="{_escape(index.name)}" tableName="{_escape(index.table)}"{unique}>']
    for name, descending in index.columns:
        marker = f' descending="{descending}"' if descending else ""
        lines.append(f'{indent}    <column name="{_escape(name)}"{marker}/>')
    lines.append(f"{indent}</createIndex>")
    return lines


def _foreign_key_xml(key, indent: str) -> str:
    extra = ""
    if key.on_delete:
        extra += f' onDelete="{_escape(key.on_delete)}"'
    if key.on_update:
        extra += f' onUpdate="{_escape(key.on_update)}"'
    return (
        f'{indent}<addForeignKeyConstraint constraintName="{_escape(key.name)}" baseTableName="{_escape(key.table)}" '
        f'baseColumnNames="{_escape(key.columns)}" referencedTableName="{_escape(key.referenced_table)}" '
        f'referencedColumnNames="{_escape(key.referenced_columns)}"{extra}/>'
    )


def _load_data_xml(load, indent: str) -> list[str]:
    """Re-emits a seed load exactly as it was written, attributes and column type hints included."""
    opening = f"{indent}<loadData{_attributes(load.attributes)}"
    if not load.columns:
        return [opening + "/>"]
    lines = [opening + ">"]
    for column in load.columns:
        lines.append(f"{indent}    <column{_attributes(column)}/>")
    lines.append(f"{indent}</loadData>")
    return lines


def _unique_xml(constraint, indent: str) -> str:
    return f'{indent}<addUniqueConstraint constraintName="{_escape(constraint.name)}" tableName="{_escape(constraint.table)}" columnNames="{_escape(constraint.columns)}"/>'


def partition(schemas: dict[str, Schema]) -> dict[str, dict]:
    """
    Splits the two engine schemas into what they agree on and what each holds alone.

    Everything both describe identically belongs in the shared changeset. A table that exists on only
    one engine, or a column the two spell differently, belongs in that engine's changeset -- along with
    every index, foreign key and unique constraint that touches it, which would otherwise reference a
    column that does not exist yet.
    """
    mysql, postgres = schemas["mysql"], schemas["postgres"]
    shared: dict = {"tables": [], "indexes": [], "foreign_keys": [], "unique_constraints": [], "sql": [], "load_data": []}
    per_engine = {
        "mysql": {"tables": [], "columns": [], "indexes": [], "foreign_keys": [], "unique_constraints": [], "sql": [], "load_data": []},
        "postgres": {"tables": [], "columns": [], "indexes": [], "foreign_keys": [], "unique_constraints": [], "sql": [], "load_data": []},
    }

    divergent_columns: set[tuple[str, str]] = set()

    for name, table in mysql.tables.items():
        other = postgres.tables.get(name)
        if other is None:
            per_engine["mysql"]["tables"].append((table, table.columns))
            divergent_columns.update((name, column.name) for column in table.columns)
            continue

        common, differing = [], {"mysql": [], "postgres": []}
        for column in table.columns:
            counterpart = other.column(column.name)
            if counterpart is not None and counterpart.identity() == column.identity():
                common.append(column)
            else:
                differing["mysql"].append(column)
                if counterpart is not None:
                    differing["postgres"].append(counterpart)
        for column in other.columns:
            if table.column(column.name) is None:
                differing["postgres"].append(column)

        # A column the two databases spell differently is normally added back by the per-database
        # changeset. That does not work for a key column: addColumn cannot extend a primary key, so a
        # table whose key diverges has to be created per database, in full.
        if any(column.constraints.get("primaryKey") == "true" for columns in differing.values() for column in columns):
            per_engine["mysql"]["tables"].append((table, table.columns))
            per_engine["postgres"]["tables"].append((other, other.columns))
            divergent_columns.update((name, column.name) for column in table.columns)
            divergent_columns.update((name, column.name) for column in other.columns)
            continue

        shared["tables"].append((table, common))
        for engine in ("mysql", "postgres"):
            for column in differing[engine]:
                per_engine[engine]["columns"].append((name, column))
                divergent_columns.add((name, column.name))

    for name, table in postgres.tables.items():
        if name not in mysql.tables:
            per_engine["postgres"]["tables"].append((table, table.columns))
            divergent_columns.update((name, column.name) for column in table.columns)

    # Anything that references a column the shared changeset does not create has to move to the
    # per-database changesets too, or the shared changeset indexes a column that does not exist yet.
    divergent = divergent_columns

    def touches_divergent(obj, kind: str) -> bool:
        if kind == "indexes":
            return any((obj.table, name) in divergent for name, _ in obj.columns)
        if kind == "foreign_keys":
            return any((obj.table, name.strip()) in divergent for name in obj.columns.split(",")) or any(
                (obj.referenced_table, name.strip()) in divergent for name in obj.referenced_columns.split(",")
            )
        return any((obj.table, name.strip()) in divergent for name in obj.columns.split(","))

    for kind in ("indexes", "foreign_keys", "unique_constraints"):
        left, right = getattr(mysql, kind), getattr(postgres, kind)
        for key in sorted(set(left) | set(right)):
            in_left, in_right = left.get(key), right.get(key)
            identical = in_left is not None and in_right is not None and in_left == in_right
            if identical and not touches_divergent(in_left, kind):
                shared[kind].append(in_left)
            else:
                if in_left is not None:
                    per_engine["mysql"][kind].append(in_left)
                if in_right is not None:
                    per_engine["postgres"][kind].append(in_right)

    shared_sql = [statement for statement in mysql.carried_sql if statement in postgres.carried_sql]
    shared["sql"] = shared_sql
    per_engine["mysql"]["sql"] = [statement for statement in mysql.carried_sql if statement not in shared_sql]
    per_engine["postgres"]["sql"] = [statement for statement in postgres.carried_sql if statement not in shared_sql]

    postgres_loads = [load.identity() for load in postgres.load_data]
    shared["load_data"] = [load for load in mysql.load_data if load.identity() in postgres_loads]
    shared_loads = [load.identity() for load in shared["load_data"]]
    per_engine["mysql"]["load_data"] = [load for load in mysql.load_data if load.identity() not in shared_loads]
    per_engine["postgres"]["load_data"] = [load for load in postgres.load_data if load.identity() not in shared_loads]

    return {"shared": shared, **per_engine}


def _guard(first_object: tuple[str, str] | None, sentinel_table: str, engines_precondition: list[str]) -> list[str]:
    """
    Builds the precondition that stops a changeset re-running on a database that already has its objects.

    The shared changeset checks the sentinel table it creates. A per-engine changeset cannot: the shared
    changeset has already created that table by the time it runs, so it checks the first object it adds
    itself, which is what the hand-written baselines did too.
    """
    lines = ['        <preConditions onFail="MARK_RAN">']
    lines += engines_precondition
    lines.append("            <not>")
    if first_object is None:
        lines.append(f'                <tableExists tableName="{sentinel_table}"/>')
    elif first_object[1]:
        lines.append(f'                <columnExists tableName="{first_object[0]}" columnName="{first_object[1]}"/>')
    else:
        lines.append(f'                <tableExists tableName="{first_object[0]}"/>')
    lines.append("            </not>")
    lines.append("        </preConditions>")
    return lines


def emit(generation: str, author: str, schemas: dict[str, Schema], sentinel_table: str) -> str:
    parts = partition(schemas)
    lines = [HEADER.format(generation=generation)]

    # --- shared ---
    lines.append(f'    <changeSet id="{generation}-01" author="{author}">')
    lines += _guard(None, sentinel_table, [])
    for table, columns in parts["shared"]["tables"]:
        lines += _create_table_xml(table, columns, "        ")
    for table, columns in parts["shared"]["tables"]:
        lines += [line for line in (_named_not_null_xml(table.name, column, "        ") for column in columns) if line]
    for index in parts["shared"]["indexes"]:
        lines += _index_xml(index, "        ")
    for key in parts["shared"]["foreign_keys"]:
        lines.append(_foreign_key_xml(key, "        "))
    for constraint in parts["shared"]["unique_constraints"]:
        lines.append(_unique_xml(constraint, "        "))
    for statement in parts["shared"]["sql"]:
        lines.append(f"        <sql>{_escape(statement)}</sql>")
    for load in parts["shared"]["load_data"]:
        lines += _load_data_xml(load, "        ")
    lines.append("    </changeSet>")
    lines.append("")

    # --- per engine ---
    engine_preconditions = {
        "mysql": ["            <or>", '                <dbms type="mysql"/>', '                <dbms type="h2"/>', "            </or>"],
        "postgres": ['            <dbms type="postgresql"/>'],
    }
    for number, engine in (("02", "mysql"), ("03", "postgres")):
        section = parts[engine]
        if not any(section[kind] for kind in ("tables", "columns", "indexes", "foreign_keys", "unique_constraints", "sql", "load_data")):
            continue
        # The guard has to name whatever this changeset creates *first*, and tables are emitted before
        # columns below. Guarding on a column while a createTable runs ahead of it would let a database
        # that has the table but not the column execute the changeset and fail on the duplicate table.
        first: tuple[str, str] | None = None
        if section["tables"]:
            first = (section["tables"][0][0].name, "")
        elif section["columns"]:
            first = (section["columns"][0][0], section["columns"][0][1].name)

        lines.append(f'    <changeSet id="{generation}-{number}" author="{author}">')
        lines += _guard(first, sentinel_table, engine_preconditions[engine])
        for table, columns in section["tables"]:
            lines += _create_table_xml(table, columns, "        ")
        for table_name, column in section["columns"]:
            lines.append(f'        <addColumn tableName="{_escape(table_name)}">')
            lines += _column_xml(column, "            ")
            lines.append("        </addColumn>")
        for table, columns in section["tables"]:
            lines += [line for line in (_named_not_null_xml(table.name, column, "        ") for column in columns) if line]
        for table_name, column in section["columns"]:
            named = _named_not_null_xml(table_name, column, "        ")
            if named:
                lines.append(named)
        for index in section["indexes"]:
            lines += _index_xml(index, "        ")
        for key in section["foreign_keys"]:
            lines.append(_foreign_key_xml(key, "        "))
        for constraint in section["unique_constraints"]:
            lines.append(_unique_xml(constraint, "        "))
        for statement in section["sql"]:
            lines.append(f"        <sql>{_escape(statement)}</sql>")
        for load in section["load_data"]:
            lines += _load_data_xml(load, "        ")
        lines.append("    </changeSet>")
        lines.append("")

    lines.append("</databaseChangeLog>")
    return "\n".join(lines) + "\n"


# --- Filing the folded changelogs ------------------------------------------------------------------


def pin_logical_path(path: Path, recorded_as: str) -> None:
    """Records the path this changelog had when it was first applied, so moving the file changes nothing."""
    text = path.read_text()
    match = re.search(r"<databaseChangeLog\b[^>]*?(/?)>", text, re.DOTALL)
    if match is None:
        raise RuntimeError(f"{path}: no <databaseChangeLog> element")
    element = match.group(0)
    # Only the root element counts. A comment further down that merely mentions the attribute is not it.
    if "logicalFilePath" in element:
        return
    replacement = element[: -1 - len(match.group(1))].rstrip() + f'\n                   logicalFilePath="{recorded_as}"' + match.group(1) + ">"
    path.write_text(text[: match.start()] + replacement + text[match.end() :])


def file_under_history(changelogs: list[Path], generation: str) -> list[str]:
    """Moves the folded changelogs into history/<generation>/ and returns their new manifest entries."""
    destination = LIQUIBASE_DIR / "history" / generation
    destination.mkdir(parents=True, exist_ok=True)
    entries = []
    for changelog in changelogs:
        recorded_as = str(changelog.relative_to(RESOURCE_ROOT))
        target = destination / changelog.name
        shutil.move(str(changelog), target)
        pin_logical_path(target, recorded_as)
        entries.append(f"config/liquibase/history/{generation}/{changelog.name}")
    return entries


def write_history_manifests(generation: str, entries: list[str]) -> None:
    generation_master = LIQUIBASE_DIR / "history" / generation / "master.xml"
    includes = "\n".join(f'    <include file="{entry}" relativeToChangelogFile="false"/>' for entry in entries)
    generation_master.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
        '                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">\n'
        f"    <!-- Folded into the {generation} baseline. Recorded, not executed, on a fresh installation. -->\n"
        f"{includes}\n"
        "</databaseChangeLog>\n"
    )

    history_master = LIQUIBASE_DIR / "history" / "master.xml"
    # Oldest generation first, and by number: a lexicographic sort puts v10 before v9, and the order
    # these are applied in is what makes an upgrade from an older generation work.
    generations = sorted((path.name for path in (LIQUIBASE_DIR / "history").iterdir() if path.is_dir()), key=lambda name: int(name.lstrip("v")))
    generation_includes = "\n".join(f'    <include file="config/liquibase/history/{name}/master.xml" relativeToChangelogFile="false"/>' for name in generations)
    history_master.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
        '                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">\n'
        "    <!--\n"
        "        Every changelog a baseline has already folded, oldest generation first. A fresh installation\n"
        "        records these without executing them; an upgrade has already executed the ones it ran before.\n"
        "        Delete a generation only when upgrades from it are no longer supported.\n"
        "    -->\n"
        f"{generation_includes}\n"
        "</databaseChangeLog>\n"
    )


MASTER_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <!--
        Four sections, in this order. See documentation/docs/developer/guidelines/database-migration-consolidation.mdx.

        history/    Every changelog a baseline has already folded. An upgrade has these recorded already.
                    A fresh installation normally has them recorded too, without executing them, by the
                    changelog-sync ArtemisSpringLiquibase runs first.
        baseline/   The schema as of the last cut, in one file. It creates everything on an empty
                    database and marks itself as ran on a database that already has that schema.
        changelog/  Migrations written since the last cut. These run everywhere. New changelogs go here.
        data/       Seed data. Evaluated on every installation and never folded, because a folded
                    changeset is recorded rather than executed and its rows would simply be missing.

        The history comes first so that this changelog is correct on its own. Applied by a plain
        SpringLiquibase to an empty database (which is what test harnesses that build their own do,
        Zonky's embedded-database provider among them) the history executes, and the baseline then
        finds the schema already there and marks itself as ran. Same schema, just the slower way round.
        That makes the changelog-sync an optimisation rather than something correctness depends on.
    -->

    <include file="classpath:config/liquibase/history/master.xml" relativeToChangelogFile="false"/>

    <include file="classpath:config/liquibase/baseline/{generation}_initial_schema.xml" relativeToChangelogFile="false"/>

    <!-- NOTE: please use the format "YYYYMMDDhhmmss_changelog.xml", i.e. year month day hour minutes seconds and not something else! -->
    <!-- we should also stay in a chronological order! -->
    <!-- you can use the command "date '+%Y%m%d%H%M%S'" to get the current date and time in the correct format -->
{changelogs}
{data}
</databaseChangeLog>
"""


def write_master(generation: str, data_includes: list[str]) -> None:
    """Rewrites master.xml for the new generation: one baseline, the history, no changelogs yet, the seed data."""
    master = LIQUIBASE_DIR / "master.xml"
    data = "\n".join(f'    <include file="classpath:{entry}" relativeToChangelogFile="false"/>' for entry in data_includes)
    master.write_text(MASTER_TEMPLATE.format(generation=generation, changelogs="", data=data))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--generation", required=True, help="name of the generation being cut, for example v10")
    parser.add_argument("--author", default="krusche")
    parser.add_argument("--sentinel-table", default="jhi_user", help="table whose absence means the database is empty")
    parser.add_argument("--dry-run", action="store_true", help="write the baseline but leave the changelogs where they are")
    arguments = parser.parse_args()

    master = LIQUIBASE_DIR / "master.xml"
    foldable = foldable_changelogs(master)
    data_includes = [
        match.group(1).removeprefix("classpath:") for match in re.finditer(r'<include\s+file="([^"]+)"', master.read_text()) if "/data/" in match.group(1)
    ]

    print(f"Folding {len(foldable)} changelog(s) into {arguments.generation}")
    schemas, refusals, unknown_preconditions = fold(foldable)

    # Assuming an unrecognised precondition is satisfied applies a change Liquibase might have skipped,
    # which is a baseline that is wrong in a way no check phrased in terms of the baseline can see.
    refusals += [f"no rule for precondition <{tag}>; add one to schema_state.satisfies rather than guessing at it" for tag in sorted(unknown_preconditions)]

    if refusals:
        print(f"\nRefused to fold {len(refusals)} changeset(s):", file=sys.stderr)
        for refusal in refusals:
            print(f"  {refusal}", file=sys.stderr)
        print("\nResolve these and run again. Nothing has been changed.", file=sys.stderr)
        return 1

    print(f"  {len(schemas['mysql'].tables)} tables, {len(schemas['mysql'].indexes)} indexes, {len(schemas['mysql'].foreign_keys)} foreign keys")

    baseline_dir = LIQUIBASE_DIR / "baseline"
    baseline_dir.mkdir(exist_ok=True)
    baseline = baseline_dir / f"{arguments.generation}_initial_schema.xml"
    baseline.write_text(emit(arguments.generation, arguments.author, schemas, arguments.sentinel_table))
    print(f"  wrote {baseline.relative_to(REPO)}")

    if arguments.dry_run:
        print("  dry run: the changelogs were left where they are")
        return 0

    entries = file_under_history(foldable, arguments.generation)
    write_history_manifests(arguments.generation, entries)
    write_master(arguments.generation, data_includes)
    print(f"  filed {len(entries)} changelog(s) under history/{arguments.generation}")
    print("  rewrote master.xml")
    print("\nNow run: python3 supporting_scripts/liquibase/verify_schema.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
