version: '2'
services:
    exerciseapplication-mysql:
        extends:
            file: mysql.yml
            service: exerciseapplication-mysql
    exerciseapplication-bamboo:
        image: josezuazo/atlassian-bamboo-server
        ports:
         - "8085:8085"
    exerciseapplication-bitbucket:
        image: cptactionhank/atlassian-bitbucket
        ports:
         - "7990:7990"
         - "7999:7999"
    exerciseapplication-jira:
        image: cptactionhank/atlassian-jira
        ports:
         - "8000:8080"
