blank_issues_enabled: false
contact_links:
  - name: ❓ Support Question
    url: mailto:artemis.in@tum.de
    about: 🛑 Please do not file questions or support requests on the GitHub issues tracker. Please contact the Artemis Team using Email.
