package de.tum.in.www1.artemis.domain;

/**
 * Used to define the type of a ProgrammingExerciseTestCase
 */
public enum ProgrammingExerciseTestCaseType {
    /**
     * Test case has been generated by the structure oracle
     */
    STRUCTURAL,
    /**
     * Test case has been generated by an instructor
     */
    BEHAVIORAL,
}
