package de.tum.cit.aet.artemis.domain.enumeration;

public enum GraphType {
    SUBMISSIONS, ACTIVE_USERS, LOGGED_IN_USERS, RELEASED_EXERCISES, EXERCISES_DUE, CONDUCTED_EXAMS, EXAM_PARTICIPATIONS, EXAM_REGISTRATIONS, ACTIVE_TUTORS, CREATED_RESULTS,
    CREATED_FEEDBACKS, POSTS, RESOLVED_POSTS
}
