# ----------------------------------------------------------------------------------------------------------------------
# Artemis-Prod-MySQL Setup
# ----------------------------------------------------------------------------------------------------------------------

# this links to /docker/artemis-prod-mysql.yml which is the default artemis production docker compose setup

services:
    artemis-app:
        extends:
            file: ./artemis-prod-mysql.yml
            service: artemis-app
    mysql:
        extends:
            file: ./artemis-prod-mysql.yml
            service: mysql
    nginx:
        extends:
            file: ./artemis-prod-mysql.yml
            service: nginx
    transcription-service:
      build:
        context: ./flask-transcription  # Adjust if needed
        dockerfile: Dockerfile
      container_name: transcription-service
      ports:
        - "5000:5000"  # Change this to ensure Flask is exposed on port 5000
      volumes:
        - ./flask-transcription/uploads:/app/uploads
        - ./flask-transcription/transcripts:/app/transcripts
      restart: on-failure
      networks:
        - artemis


networks:
    artemis:
        driver: "bridge"
        name: artemis
