# ----------------------------------------------------------------------------------------------------------------------
# Mailpit service (drop-in replacement for MailHog)
#
# Web UI: http://localhost:8025
# SMTP:   localhost:1025
#
# Out of the box this setup just works with a containerized dev Artemis instance
# see comments above artemis-app on how to get it working with a non-containerized Artemis instance
# ----------------------------------------------------------------------------------------------------------------------
services:
    mailpit:
        container_name: artemis-mailpit
        image: docker.io/axllent/mailpit:${MAILPIT_VERSION}
        pull_policy: missing
        ports:
            - "1025:1025"
            - "8025:8025"
        # expose the ports to make them reachable docker internally even if the external port mapping changes
        expose:
            - "1025"
            - "8025"
        networks:
            - artemis

    # comment this section if you use mailpit with a non-containerized Artemis instance
    # and add the following spring configuration in your application-local.yml
    artemis-app:
        environment:
            SPRING_MAIL_HOST: "mailpit"
            SPRING_MAIL_PORT: "1025"
            SPRING_MAIL_USERNAME:
            SPRING_MAIL_PASSWORD:

networks:
    artemis:
        driver: "bridge"
        name: artemis
