Artemis offers a build queue view that shows the all running, queued and finished build jobs.
The build queue of all build jobs is accessible only to **Administrators** and is accessible via the *System Administration* menu.

.. figure:: programming/buildQueueSystemAdministration.png
   :alt: Build Queue System Administration
   :align: center

   Build Queue System Administration

The build queue for a specific course is also accessible to **Instructors** via the *Build Queue* menu in the *Course Management* menu
and shows only the build jobs for the selected course.

.. figure:: programming/buildQueueCourseManagement.png
   :alt: Build Queue Course Management
   :align: center

   Build Queue Course Management

The build queue view is divided into three sections:

Running Build Jobs
""""""""""""""""""
The running build jobs section shows all build jobs that are currently running.
New build jobs are added and removed from the queue in real-time and can be cancelled by the user.
The table shows the following information:

.. figure:: programming/running-build-jobs.png
   :alt: Running Build Jobs
   :align: center

   Running Build Jobs



Queued Build Jobs
""""""""""""""""""
The queued build jobs section shows all build jobs that are currently queued. New build jobs are added and removed from the queue in real-time and can be cancelled by the user.
The table shows the following information:

.. figure:: programming/queued-build-jobs.png
   :alt: Queued Build Jobs
   :align: center

   Queued Build Jobs

Finished Build Jobs
"""""""""""""""""""
The finished build jobs section shows all build jobs that have finished (successfully with or without a result, failed or cancelled).
The finished build jobs are fetched gradually as the user navigates through the pages. The table shows the following information:

.. figure:: programming/finished-build-jobs.png
   :alt: Finished Build Jobs
   :align: center

   Finished Build Jobs



