package de.tum.cit.aet.artemis.programming;

import static org.assertj.core.api.Assertions.assertThat;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import org.junit.jupiter.api.Test;

import de.tum.cit.aet.artemis.programming.domain.ProgrammingExercise;

/**
 * Forces a decision for every field of a programming exercise that an import has to carry.
 * <p>
 * The course material, exam and variant imports build a skeleton exercise on the server, and the programming import service copies only the build configuration
 * and the entities that hang off the exercise. A setting that nobody copies onto the skeleton fails the import or falls back to a default without a sign.
 * <p>
 * Every field is therefore expected to be copied by {@link ProgrammingExercise#copyImportSettingsFrom(ProgrammingExercise)}, unless it is listed in
 * {@link #NOT_COPIED} with the reason. A new field fails this test until it is copied or listed.
 */
class ProgrammingExerciseImportSettingsTest {

    private static final String SET_BY_IMPORT = "The import itself creates or resets it, so it must not come from the source";

    private static final String CALLER_OWNED = "Each caller decides it differently (an override, a reset, or a copy of its own), so it stays with the caller";

    private static final String DATE_RESET = "Reset on import, so the imported exercise starts without the source's schedule (a variant sets its own)";

    private static final String TRANSIENT_STATE = "Computed for a response and never stored, so there is nothing to import";

    /**
     * The fields that {@link ProgrammingExercise#copyImportSettingsFrom(ProgrammingExercise)} does not copy, each with the reason.
     */
    private static final Map<String, String> NOT_COPIED = new TreeMap<>(Map.ofEntries(Map.entry("id", SET_BY_IMPORT),
            Map.entry("projectKey", "Generated by the import from the course short name and the exercise short name"), Map.entry("testRepositoryUri", SET_BY_IMPORT),
            Map.entry("templateParticipation", SET_BY_IMPORT), Map.entry("solutionParticipation", SET_BY_IMPORT), Map.entry("testCases", SET_BY_IMPORT),
            Map.entry("tasks", SET_BY_IMPORT), Map.entry("staticCodeAnalysisCategories", SET_BY_IMPORT), Map.entry("auxiliaryRepositories", SET_BY_IMPORT),
            Map.entry("studentParticipations", SET_BY_IMPORT), Map.entry("tutorParticipations", SET_BY_IMPORT), Map.entry("exampleSubmissions", SET_BY_IMPORT),
            Map.entry("plagiarismCases", SET_BY_IMPORT), Map.entry("teams", SET_BY_IMPORT), Map.entry("testCasesChanged", SET_BY_IMPORT),
            Map.entry("gradingCriteria", "The import service deep-copies them from the source, a skeleton passes null to ask for that"),
            Map.entry("plagiarismDetectionConfig", "The import stores the one a skeleton carries, or the default configuration when it carries none, as a row of its own"),
            Map.entry("buildAndTestStudentSubmissionsAfterDueDate", "The import recomputes it from the build plan phases and the due date"),
            Map.entry("problemStatement", "The import copies it from the source and remaps the test ids inside it, a variant replaces it afterwards"),
            Map.entry("title", CALLER_OWNED), Map.entry("shortName", CALLER_OWNED), Map.entry("maxPoints", CALLER_OWNED), Map.entry("bonusPoints", CALLER_OWNED),
            Map.entry("mode",
                    "Goes together with the team assignment configuration, which the course material fetch does not load: the exam and variant imports copy the mode, the course material import leaves it out"),
            Map.entry("teamAssignmentConfig", "Goes together with the mode, see there"), Map.entry("course", "The target of the import, which each caller names"),
            Map.entry("exerciseGroup", "The target of the import, which each caller names"),
            Map.entry("exerciseVariantGroup", "A variant joins its group after the import, no other caller has one"),
            Map.entry("competencyLinks", "They point at competencies of the source course, so a caller supplies links to competencies of the target"),
            Map.entry("submissionPolicy",
                    "A separate entity that no import fetch loads: the course material import copies it itself, and the import service only saves the one a skeleton carries"),
            Map.entry("channelNameTransient", "The name of the channel the import creates, which the caller chooses"), Map.entry("releaseDate", DATE_RESET),
            Map.entry("startDate", DATE_RESET), Map.entry("dueDate", DATE_RESET), Map.entry("assessmentDueDate", DATE_RESET),
            Map.entry("exampleSolutionPublicationDate", DATE_RESET), Map.entry("averageRatingTransient", TRANSIENT_STATE),
            Map.entry("isGradingInstructionFeedbackUsedTransient", TRANSIENT_STATE), Map.entry("numberOfComplaintsTransient", TRANSIENT_STATE),
            Map.entry("numberOfMoreFeedbackRequestsTransient", TRANSIENT_STATE), Map.entry("numberOfOpenComplaintsTransient", TRANSIENT_STATE),
            Map.entry("numberOfOpenMoreFeedbackRequestsTransient", TRANSIENT_STATE), Map.entry("numberOfParticipationsTransient", TRANSIENT_STATE),
            Map.entry("numberOfRatingsTransient", TRANSIENT_STATE), Map.entry("studentAssignedTeamIdComputedTransient", TRANSIENT_STATE),
            Map.entry("studentAssignedTeamIdTransient", TRANSIENT_STATE), Map.entry("testRunParticipationsExistTransient", TRANSIENT_STATE),
            Map.entry("latestExamEndDateTransient", TRANSIENT_STATE), Map.entry("assessmentPossibleFromTransient", TRANSIENT_STATE),
            Map.entry("numberOfSubmissionsTransient", TRANSIENT_STATE), Map.entry("totalNumberOfAssessmentsTransient", TRANSIENT_STATE),
            Map.entry("numberOfAssessmentsOfCorrectionRoundsTransient", TRANSIENT_STATE)));

    @Test
    void everyFieldIsCopiedOrExcludedWithAReason() throws Exception {
        List<Field> fields = instanceFields();
        Set<String> fieldNames = new HashSet<>();
        fields.forEach(field -> assertThat(fieldNames.add(field.getName())).as("field name %s exists twice in the class hierarchy", field.getName()).isTrue());
        assertThat(NOT_COPIED.keySet()).as("exclusions of fields that no longer exist").isSubsetOf(fieldNames);

        ProgrammingExercise freshInstance = new ProgrammingExercise();
        ProgrammingExercise source = new ProgrammingExercise();
        ProgrammingExercise skeleton = new ProgrammingExercise();
        Map<Field, Object> expectedValues = new TreeMap<>((first, second) -> first.getName().compareTo(second.getName()));
        List<String> problems = new ArrayList<>();
        for (Field field : fields) {
            if (NOT_COPIED.containsKey(field.getName())) {
                continue;
            }
            Object value = valueDifferentFromDefault(field, freshInstance);
            if (value == null) {
                problems.add(field.getName() + " (" + field.getGenericType().getTypeName() + "): not copied and no test value for its type, copy it or list it in NOT_COPIED");
                continue;
            }
            field.set(source, value);
            expectedValues.put(field, value);
        }

        skeleton.copyImportSettingsFrom(source);

        for (var expected : expectedValues.entrySet()) {
            Object actual = expected.getKey().get(skeleton);
            if (!expected.getValue().equals(actual)) {
                problems.add(expected.getKey().getName() + ": expected " + expected.getValue() + " on the skeleton but found " + actual
                        + ", copy it in copyImportSettingsFrom or list it in NOT_COPIED");
            }
        }
        assertThat(problems).as("fields that an import loses").isEmpty();
    }

    /**
     * All non-static fields of the programming exercise and its superclasses, so that a column added to any of them is covered.
     */
    private static List<Field> instanceFields() {
        List<Field> fields = new ArrayList<>();
        for (Class<?> type = ProgrammingExercise.class; type != null && type != Object.class; type = type.getSuperclass()) {
            for (Field field : type.getDeclaredFields()) {
                if (!Modifier.isStatic(field.getModifiers()) && !field.isSynthetic()) {
                    field.setAccessible(true);
                    fields.add(field);
                }
            }
        }
        return fields;
    }

    /**
     * Returns a value of the field's type that differs from what a new exercise holds, or {@code null} if the type is not supported.
     */
    private static Object valueDifferentFromDefault(Field field, ProgrammingExercise freshInstance) throws IllegalAccessException {
        Class<?> type = field.getType();
        Object defaultValue = field.get(freshInstance);
        if (type == String.class) {
            return "changed " + field.getName();
        }
        if (type == boolean.class || type == Boolean.class) {
            return !Boolean.TRUE.equals(defaultValue);
        }
        if (type == int.class || type == Integer.class) {
            return 7;
        }
        if (type == long.class || type == Long.class) {
            return 7L;
        }
        if (type == double.class || type == Double.class) {
            return 7.5;
        }
        if (type.isEnum()) {
            for (Object constant : type.getEnumConstants()) {
                if (!constant.equals(defaultValue)) {
                    return constant;
                }
            }
            return null;
        }
        if (Set.class.isAssignableFrom(type) && field.getGenericType() instanceof ParameterizedType parameterized && parameterized.getActualTypeArguments()[0] == String.class) {
            return new HashSet<>(Set.of("first changed value", "second changed value"));
        }
        return null;
    }
}
