package ${packageName}.testutils;

public enum ScanResultType {
	CORRECTNAME_CORRECTPLACE,
	CORRECTNAME_MISPLACED,
    CORRECTNAME_MULTIPLETIMESPRESENT,
	WRONGCASE_CORRECTPLACE,
	WRONGCASE_MISPLACED,
    WRONGCASE_MULTIPLETIMESPRESENT,
	TYPOS_CORRECTPLACE,
	TYPOS_MISPLACED,
    TYPOS_MULTIPLETIMESPRESENT,
	NOTFOUND,
	UNDEFINED;
}
