package ${packageName}.testutils;

public enum ScanResultType {
	CORRECTNAME_CORRECTPLACE,
	CORRECTNAME_MISPLACED,
	WRONGCASE_CORRECTPLACE,
	WRONGCASE_MISPLACED,
	TYPOS_CORRECTPLACE,
	TYPOS_MISPLACED,
	NOTFOUND,
	UNDEFINED;
}
