package ${packageName}.testutils;

/**
 * @author Stephan Krusche (krusche@in.tum.de)
 * @version 2.0 (24.02.2019)
 */
public enum ScanResultType {
    CORRECTNAME_CORRECTPLACE,
    CORRECTNAME_MISPLACED,
    CORRECTNAME_MULTIPLETIMESPRESENT,
    WRONGCASE_CORRECTPLACE,
    WRONGCASE_MISPLACED,
    WRONGCASE_MULTIPLETIMESPRESENT,
    TYPOS_CORRECTPLACE,
    TYPOS_MISPLACED,
    TYPOS_MULTIPLETIMESPRESENT,
    NOTFOUND,
    UNDEFINED;
}
