@startuml
skinparam ArrowFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
    FontSize 20
    BackgroundColor white
    AttributeFontSize 16
    BorderColor black
    ArrowColor black
}
!pragma useIntermediatePackages false
package "src.main.java.de.tum.cit.aet.artemis.repository" {
  interface FileUploadExerciseRepository {
  save(FileUploadExerciseRepository): FileUploadExerciseRepository
  }
}
package "src.test.java.de.tum.cit.aet.artemis.exercise" {
  class ExerciseTestFactory {
  + {static} populateExercise(Exercise, [...]): Exercise
  + {static} populateExerciseForExam(Exercise, [...]): Exercise
  }
  package "fileUpload" {
    class FileUploadTestService {
    + createAndSaveFileUploadExercise(ZonedDateTim, [...]): FileUploadExercise
    + generateFileUploadExercise(ZonedDateTime, [...]): FileUploadExercise
    + createAndSaveExamFileUploadExercise(ZonedDateTime, [...]): FileUploadExercise
    + generateExamFileUploadExercise(ZonedDateTime, [...]): FileUploadExercise
    }
    class FileUploadTestFactory {
    + {static} generateFileUploadExercise(ZonedDateTime, [...]): FileUploadExercise
    + {static} generateFileUploadExerciseForExam(String, [...]): FileUploadExercise
    }
    together {
    class FileUploadExerciseIntegrationTest {
    + test(): void
    }
    }
  }
}
FileUploadTestService o-d- FileUploadExerciseRepository
ExerciseTestFactory <.. FileUploadTestFactory
FileUploadTestFactory <.. FileUploadTestService
FileUploadTestFactory <.. FileUploadExerciseIntegrationTest
FileUploadTestService -u-o FileUploadExerciseIntegrationTest
@enduml
