/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalendarEvent { 
    type: CalendarEvent.TypeEnum;
    title: string;
    startDate: string;
    endDate?: string;
    location?: string;
    facilitator?: string;
}
export namespace CalendarEvent {
    export const TypeEnum = {
        Lecture: 'LECTURE',
        Tutorial: 'TUTORIAL',
        Exam: 'EXAM',
        QuizExercise: 'QUIZ_EXERCISE',
        TextExercise: 'TEXT_EXERCISE',
        ModelingExercise: 'MODELING_EXERCISE',
        ProgrammingExercise: 'PROGRAMMING_EXERCISE',
        FileUploadExercise: 'FILE_UPLOAD_EXERCISE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


