/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DifficultyAssessment } from './difficultyAssessment';
import { BloomRadar } from './bloomRadar';
import { InferredCompetency } from './inferredCompetency';
import { QualityIssue } from './qualityIssue';


/**
 * Response containing the checklist analysis results
 */
export interface ChecklistAnalysisResponse { 
    /**
     * Top inferred competencies from the standardized catalog
     */
    inferredCompetencies?: Array<InferredCompetency>;
    /**
     * Bloom\'s taxonomy radar distribution
     */
    bloomRadar?: BloomRadar;
    /**
     * Difficulty assessment with delta indicator
     */
    difficultyAssessment?: DifficultyAssessment;
    /**
     * List of quality issues found in the problem statement
     */
    qualityIssues?: Array<QualityIssue>;
}

