/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to analyze a problem statement for quality, competencies, and difficulty
 */
export interface ChecklistAnalysisRequest { 
    /**
     * Problem statement in Markdown format
     */
    problemStatementMarkdown: string;
    /**
     * Declared difficulty of the exercise
     */
    declaredDifficulty?: string;
    /**
     * Programming language, e.g. JAVA, PYTHON
     */
    language?: string;
    /**
     * ID of the exercise
     */
    exerciseId?: number;
}

