/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChecklistAnalysisRequest { 
    problemStatement: string;
    existingDifficulty?: string;
    existingLearningGoals?: Array<string>;
}

