/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response from applying a checklist action to the problem statement
 */
export interface ChecklistActionResponse { 
    /**
     * The updated problem statement markdown
     */
    updatedProblemStatement?: string;
    /**
     * Whether the action was successfully applied
     */
    applied?: boolean;
    /**
     * Short summary of what was changed
     */
    summary?: string;
}

