/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response DTO for code generation result
 */
export interface CodeGenerationResultDTO { 
    /**
     * Whether the code generation was successful
     */
    success: boolean;
    /**
     * Result message describing the outcome
     */
    message: string;
    /**
     * Number of generation attempts made
     */
    attempts: number;
}

