/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ArtifactLocation } from './artifact-location';

/**
 * Individual consistency issue details
 */
export interface ConsistencyIssue {
    /** Severity of the issue */
    severity: ConsistencyIssueSeverityEnum;
    /** Category of the issue */
    category: ConsistencyIssueCategoryEnum;
    /** Detailed description of the issue */
    description: string;
    /** Suggested fix for the issue */
    suggestedFix: string;
    /** Related locations across artifacts */
    relatedLocations: Array<ArtifactLocation>;
}

export type ConsistencyIssueSeverityEnum = 'LOW' | 'MEDIUM' | 'HIGH';

export const ConsistencyIssueSeverityEnum = {
    Low: 'LOW' as const,
    Medium: 'MEDIUM' as const,
    High: 'HIGH' as const,
} as const;

export const ConsistencyIssueSeverityEnumValues = ['LOW', 'MEDIUM', 'HIGH'] as const;

export type ConsistencyIssueCategoryEnum = 'METHOD_RETURN_TYPE_MISMATCH' | 'METHOD_PARAMETER_MISMATCH' | 'CONSTRUCTOR_PARAMETER_MISMATCH' | 'ATTRIBUTE_TYPE_MISMATCH' | 'VISIBILITY_MISMATCH' | 'IDENTIFIER_NAMING_INCONSISTENCY';

export const ConsistencyIssueCategoryEnum = {
    MethodReturnTypeMismatch: 'METHOD_RETURN_TYPE_MISMATCH' as const,
    MethodParameterMismatch: 'METHOD_PARAMETER_MISMATCH' as const,
    ConstructorParameterMismatch: 'CONSTRUCTOR_PARAMETER_MISMATCH' as const,
    AttributeTypeMismatch: 'ATTRIBUTE_TYPE_MISMATCH' as const,
    VisibilityMismatch: 'VISIBILITY_MISMATCH' as const,
    IdentifierNamingInconsistency: 'IDENTIFIER_NAMING_INCONSISTENCY' as const,
} as const;

export const ConsistencyIssueCategoryEnumValues = ['METHOD_RETURN_TYPE_MISMATCH', 'METHOD_PARAMETER_MISMATCH', 'CONSTRUCTOR_PARAMETER_MISMATCH', 'ATTRIBUTE_TYPE_MISMATCH', 'VISIBILITY_MISMATCH', 'IDENTIFIER_NAMING_INCONSISTENCY'] as const;
