/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing consistency check costs
 */
export interface Costs { 
    /**
     * Prompt costs in EUR
     */
    promptEur?: number;
    /**
     * Completion costs in EUR
     */
    completionEur?: number;
    /**
     * Total costs in EUR
     */
    totalEur?: number;
}

