/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DifficultyAssessment { 
    suggested?: DifficultyAssessment.SuggestedEnum;
    confidence?: number;
    reasoning?: string;
    matchesDeclared?: boolean;
    delta?: DifficultyAssessment.DeltaEnum;
    taskCount?: number;
    testCount?: number;
}
export namespace DifficultyAssessment {
    export const SuggestedEnum = {
        Easy: 'EASY',
        Medium: 'MEDIUM',
        Hard: 'HARD',
        Unknown: 'UNKNOWN'
    } as const;
    export type SuggestedEnum = typeof SuggestedEnum[keyof typeof SuggestedEnum];
    export const DeltaEnum = {
        Lower: 'LOWER',
        Match: 'MATCH',
        Higher: 'HIGHER',
        Unknown: 'UNKNOWN'
    } as const;
    export type DeltaEnum = typeof DeltaEnum[keyof typeof DeltaEnum];
}


