/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DragItem } from './dragItem';
import { DropLocation } from './dropLocation';


export interface DragAndDropMapping { 
    id?: number;
    dragItemIndex?: number;
    dropLocationIndex?: number;
    invalid?: boolean;
    dragItem?: DragItem;
    dropLocation?: DropLocation;
}

