/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { DragAndDropMapping } from './drag-and-drop-mapping';
import type { DragItem } from './drag-item';
import type { DropLocation } from './drop-location';

export interface DragAndDropQuizQuestionWithSolution {
    id?: number;
    title?: string;
    text?: string;
    hint?: string;
    points?: number;
    scoringType?: DragAndDropQuizQuestionWithSolutionScoringTypeEnum;
    randomizeOrder?: boolean;
    invalid?: boolean;
    type: DragAndDropQuizQuestionWithSolutionTypeEnum;
    explanation?: string;
    backgroundFilePath?: string;
    dropLocations?: Array<DropLocation>;
    dragItems?: Array<DragItem>;
    correctMappings?: Array<DragAndDropMapping>;
}

export type DragAndDropQuizQuestionWithSolutionScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const DragAndDropQuizQuestionWithSolutionScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const DragAndDropQuizQuestionWithSolutionScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type DragAndDropQuizQuestionWithSolutionTypeEnum = 'drag-and-drop';

export const DragAndDropQuizQuestionWithSolutionTypeEnum = {
    DragAndDrop: 'drag-and-drop' as const,
} as const;

export const DragAndDropQuizQuestionWithSolutionTypeEnumValues = ['drag-and-drop'] as const;

