/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { DragItemCreate } from './drag-item-create';
import type { DropLocationCreate } from './drop-location-create';
import type { DragAndDropMappingCreate } from './drag-and-drop-mapping-create';

export interface DragAndDropQuestionCreate {
    title: string;
    text?: string;
    hint?: string;
    explanation?: string;
    points: number;
    scoringType: DragAndDropQuestionCreateScoringTypeEnum;
    randomizeOrder?: boolean;
    backgroundFilePath?: string;
    dropLocations: Array<DropLocationCreate>;
    dragItems: Array<DragItemCreate>;
    correctMappings: Array<DragAndDropMappingCreate>;
    type: DragAndDropQuestionCreateTypeEnum;
}

export type DragAndDropQuestionCreateScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const DragAndDropQuestionCreateScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const DragAndDropQuestionCreateScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type DragAndDropQuestionCreateTypeEnum = 'drag-and-drop';

export const DragAndDropQuestionCreateTypeEnum = {
    DragAndDrop: 'drag-and-drop' as const,
} as const;

export const DragAndDropQuestionCreateTypeEnumValues = ['drag-and-drop'] as const;
