/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { DragItemFromEditor } from './drag-item-from-editor';
import type { DragAndDropMappingFromEditor } from './drag-and-drop-mapping-from-editor';
import type { DropLocationFromEditor } from './drop-location-from-editor';

export interface DragAndDropQuestionFromEditor {
    id?: number;
    title: string;
    text?: string;
    hint?: string;
    explanation?: string;
    points: number;
    scoringType: DragAndDropQuestionFromEditorScoringTypeEnum;
    randomizeOrder?: boolean;
    backgroundFilePath?: string;
    dropLocations: Array<DropLocationFromEditor>;
    dragItems: Array<DragItemFromEditor>;
    correctMappings: Array<DragAndDropMappingFromEditor>;
    type: DragAndDropQuestionFromEditorTypeEnum;
}

export type DragAndDropQuestionFromEditorScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const DragAndDropQuestionFromEditorScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const DragAndDropQuestionFromEditorScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type DragAndDropQuestionFromEditorTypeEnum = 'drag-and-drop';

export const DragAndDropQuestionFromEditorTypeEnum = {
    DragAndDrop: 'drag-and-drop' as const,
} as const;

export const DragAndDropQuestionFromEditorTypeEnumValues = ['drag-and-drop'] as const;
