/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { DragAndDropMappingReEvaluate } from './drag-and-drop-mapping-re-evaluate';

export interface DragAndDropSubmittedAnswerFromStudent {
    questionId: number;
    mappings: Array<DragAndDropMappingReEvaluate>;
    type: DragAndDropSubmittedAnswerFromStudentTypeEnum;
}

export type DragAndDropSubmittedAnswerFromStudentTypeEnum = 'drag-and-drop';

export const DragAndDropSubmittedAnswerFromStudentTypeEnum = {
    DragAndDrop: 'drag-and-drop' as const,
} as const;

export const DragAndDropSubmittedAnswerFromStudentTypeEnumValues = ['drag-and-drop'] as const;
