/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * What a generation run has spent so far, streamed while it runs
 */
export interface ExerciseGenerationLiveUsage {
    /** Prompt tokens billed so far */
    inputTokens: number;
    /** Completion tokens billed so far */
    outputTokens: number;
    /** The share of the prompt tokens the provider served from its cache */
    cachedInputTokens: number;
    /** Tokens charged against the run\'s token budget, with cached input discounted */
    billableTokens: number;
    /** The token ceiling this run was admitted against */
    tokenBudget: number;
    /** Provider responses accounted for so far */
    modelCalls: number;
    /** Estimated cost in EUR, absent when any model used has no configured price */
    estimatedCostEur?: number;
    /** Whether a price was configured for every response counted so far */
    estimatedCostComplete: boolean;
}
