/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ExerciseGenerationVerdict } from './exercise-generation-verdict';
import type { ExerciseGenerationRepairRound } from './exercise-generation-repair-round';

/**
 * A progress event streamed to the instructor while an agentic whole-exercise generation or adaptation runs
 */
export interface ExerciseGenerationEvent {
    /** The event kind */
    type: ExerciseGenerationEventTypeEnum;
    /** Human-readable progress or result message */
    message?: string;
    /** Stable instructor-facing phase of the generation journey */
    phase?: ExerciseGenerationEventPhaseEnum;
    /** On a terminal DONE event, whether the run succeeded, needs review, or partially completed */
    completionStatus?: ExerciseGenerationEventCompletionStatusEnum;
    /** On a terminal event, the structured verification verdict */
    verdict?: ExerciseGenerationVerdict;
    /** On a terminal event, whether the live exercise changed and open editors should refresh */
    liveExerciseChanged?: boolean;
    /** Exact saved commit hashes keyed by repository name */
    savedRepositoryCommits?: { [key: string]: string; };
    /** The exact saved exercise version id, on a successful terminal event */
    savedExerciseVersionId?: number;
    /** On a terminal event, why the generation run ended */
    terminationReason?: ExerciseGenerationEventTerminationReasonEnum;
    /** On a repair-round progress event, that round\'s finding bookkeeping */
    repairRound?: ExerciseGenerationRepairRound;
    /** The moment the event was produced */
    timestamp: string;
}

export type ExerciseGenerationEventTypeEnum = 'STARTED' | 'PROGRESS' | 'DONE' | 'CANCELLED' | 'ERROR';

export const ExerciseGenerationEventTypeEnum = {
    Started: 'STARTED' as const,
    Progress: 'PROGRESS' as const,
    Done: 'DONE' as const,
    Cancelled: 'CANCELLED' as const,
    Error: 'ERROR' as const,
} as const;

export const ExerciseGenerationEventTypeEnumValues = ['STARTED', 'PROGRESS', 'DONE', 'CANCELLED', 'ERROR'] as const;

export type ExerciseGenerationEventPhaseEnum = 'PREPARING' | 'DESIGNING' | 'VERIFYING' | 'REVIEWING' | 'REPAIRING' | 'SAVING';

export const ExerciseGenerationEventPhaseEnum = {
    Preparing: 'PREPARING' as const,
    Designing: 'DESIGNING' as const,
    Verifying: 'VERIFYING' as const,
    Reviewing: 'REVIEWING' as const,
    Repairing: 'REPAIRING' as const,
    Saving: 'SAVING' as const,
} as const;

export const ExerciseGenerationEventPhaseEnumValues = ['PREPARING', 'DESIGNING', 'VERIFYING', 'REVIEWING', 'REPAIRING', 'SAVING'] as const;

export type ExerciseGenerationEventCompletionStatusEnum = 'SUCCESS' | 'NEEDS_REVIEW' | 'PARTIAL';

export const ExerciseGenerationEventCompletionStatusEnum = {
    Success: 'SUCCESS' as const,
    NeedsReview: 'NEEDS_REVIEW' as const,
    Partial: 'PARTIAL' as const,
} as const;

export const ExerciseGenerationEventCompletionStatusEnumValues = ['SUCCESS', 'NEEDS_REVIEW', 'PARTIAL'] as const;

export type ExerciseGenerationEventTerminationReasonEnum = 'CONVERGED' | 'REPAIR_BUDGET_EXHAUSTED' | 'ATTEMPT_CAP_REACHED' | 'MECHANICAL_REPAIR_EXHAUSTED' | 'POST_REPAIR_CORRECTION_EXHAUSTED' | 'NO_SCHEDULABLE_SURFACE' | 'REVIEW_UNAVAILABLE' | 'UNCHANGED_CANDIDATE_RESUBMITTED' | 'REPAIR_DID_NOT_IMPROVE' | 'NO_ADMISSIBLE_CONCEPT' | 'CONCEPT_ADMITTED_WITH_FINDINGS' | 'CANCELLED' | 'DEADLINE_EXCEEDED' | 'TOKEN_BUDGET_EXHAUSTED' | 'AGENT_ERROR' | 'ENVIRONMENT_UNAVAILABLE' | 'RUN_FAILED' | 'NOT_STARTED';

export const ExerciseGenerationEventTerminationReasonEnum = {
    Converged: 'CONVERGED' as const,
    RepairBudgetExhausted: 'REPAIR_BUDGET_EXHAUSTED' as const,
    AttemptCapReached: 'ATTEMPT_CAP_REACHED' as const,
    MechanicalRepairExhausted: 'MECHANICAL_REPAIR_EXHAUSTED' as const,
    PostRepairCorrectionExhausted: 'POST_REPAIR_CORRECTION_EXHAUSTED' as const,
    NoSchedulableSurface: 'NO_SCHEDULABLE_SURFACE' as const,
    ReviewUnavailable: 'REVIEW_UNAVAILABLE' as const,
    UnchangedCandidateResubmitted: 'UNCHANGED_CANDIDATE_RESUBMITTED' as const,
    RepairDidNotImprove: 'REPAIR_DID_NOT_IMPROVE' as const,
    NoAdmissibleConcept: 'NO_ADMISSIBLE_CONCEPT' as const,
    ConceptAdmittedWithFindings: 'CONCEPT_ADMITTED_WITH_FINDINGS' as const,
    Cancelled: 'CANCELLED' as const,
    DeadlineExceeded: 'DEADLINE_EXCEEDED' as const,
    TokenBudgetExhausted: 'TOKEN_BUDGET_EXHAUSTED' as const,
    AgentError: 'AGENT_ERROR' as const,
    EnvironmentUnavailable: 'ENVIRONMENT_UNAVAILABLE' as const,
    RunFailed: 'RUN_FAILED' as const,
    NotStarted: 'NOT_STARTED' as const,
} as const;

export const ExerciseGenerationEventTerminationReasonEnumValues = ['CONVERGED', 'REPAIR_BUDGET_EXHAUSTED', 'ATTEMPT_CAP_REACHED', 'MECHANICAL_REPAIR_EXHAUSTED', 'POST_REPAIR_CORRECTION_EXHAUSTED', 'NO_SCHEDULABLE_SURFACE', 'REVIEW_UNAVAILABLE', 'UNCHANGED_CANDIDATE_RESUBMITTED', 'REPAIR_DID_NOT_IMPROVE', 'NO_ADMISSIBLE_CONCEPT', 'CONCEPT_ADMITTED_WITH_FINDINGS', 'CANCELLED', 'DEADLINE_EXCEEDED', 'TOKEN_BUDGET_EXHAUSTED', 'AGENT_ERROR', 'ENVIRONMENT_UNAVAILABLE', 'RUN_FAILED', 'NOT_STARTED'] as const;
