/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * The structured outcome of the differential verification, so the client can show which gates passed without parsing prose
 */
export interface ExerciseGenerationVerdict {
    /** Whether the exercise passed mechanical verification */
    mechanicallyVerified: boolean;
    /** Whether the solution passed all its tests */
    solutionPassed: boolean;
    /** Whether the template compiled but correctly failed the tests */
    templateFailed: boolean;
    /** The number of tests discovered */
    testCount: number;
    /** Human-readable explanations of any failed gate (empty when mechanically verified) */
    reasons: Array<string>;
}
