/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ExerciseGenerationRetainedFile } from './exercise-generation-retained-file';

/**
 * A generated candidate that was not saved to the exercise, retained read-only for inspection
 */
export interface ExerciseGenerationRetainedArtifacts {
    jobId: string;
    /** Whether the retained files are a complete account of what the run produced */
    completeness: ExerciseGenerationRetainedArtifactsCompletenessEnum;
    problemStatement?: string;
    specDocument?: string;
    files: Array<ExerciseGenerationRetainedFile>;
}

export type ExerciseGenerationRetainedArtifactsCompletenessEnum = 'COMPLETE' | 'PARTIAL';

export const ExerciseGenerationRetainedArtifactsCompletenessEnum = {
    Complete: 'COMPLETE' as const,
    Partial: 'PARTIAL' as const,
} as const;

export const ExerciseGenerationRetainedArtifactsCompletenessEnumValues = ['COMPLETE', 'PARTIAL'] as const;
