/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * The metadata Artemis derives for an exercise it is about to generate
 */
export interface ExerciseGenerationMetadataSuggestionResponse {
    title: string;
    shortName: string;
    packageName: string;
    difficulty: ExerciseGenerationMetadataSuggestionResponseDifficultyEnum;
    maxPoints: number;
}

export type ExerciseGenerationMetadataSuggestionResponseDifficultyEnum = 'EASY' | 'MEDIUM' | 'HARD';

export const ExerciseGenerationMetadataSuggestionResponseDifficultyEnum = {
    Easy: 'EASY' as const,
    Medium: 'MEDIUM' as const,
    Hard: 'HARD' as const,
} as const;

export const ExerciseGenerationMetadataSuggestionResponseDifficultyEnumValues = ['EASY', 'MEDIUM', 'HARD'] as const;
