/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExerciseGenerationRevertResult {
    fullyReverted: boolean;
    revertedRepositories: Array<ExerciseGenerationRevertResult.RevertedRepositoriesEnum>;
    completedAt: string;
}
export namespace ExerciseGenerationRevertResult {
    export const RevertedRepositoriesEnum = {
        Exercise: 'exercise',
        Solution: 'solution',
        Tests: 'tests',
        Auxiliary: 'auxiliary',
        User: 'user'
    } as const;
    export type RevertedRepositoriesEnum = typeof RevertedRepositoriesEnum[keyof typeof RevertedRepositoriesEnum];
}
