/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

export interface ExerciseGenerationMetadataSuggestionRequest {
    prompt: string;
    projectType?: ExerciseGenerationMetadataSuggestionRequestProjectTypeEnum;
}

export type ExerciseGenerationMetadataSuggestionRequestProjectTypeEnum =
    | 'MAVEN_MAVEN'
    | 'PLAIN_MAVEN'
    | 'PLAIN'
    | 'XCODE'
    | 'FACT'
    | 'GCC'
    | 'PLAIN_GRADLE'
    | 'GRADLE_GRADLE'
    | 'MAVEN_BLACKBOX';

export const ExerciseGenerationMetadataSuggestionRequestProjectTypeEnum = {
    MavenMaven: 'MAVEN_MAVEN' as const,
    PlainMaven: 'PLAIN_MAVEN' as const,
    Plain: 'PLAIN' as const,
    Xcode: 'XCODE' as const,
    Fact: 'FACT' as const,
    Gcc: 'GCC' as const,
    PlainGradle: 'PLAIN_GRADLE' as const,
    GradleGradle: 'GRADLE_GRADLE' as const,
    MavenBlackbox: 'MAVEN_BLACKBOX' as const,
} as const;

export const ExerciseGenerationMetadataSuggestionRequestProjectTypeEnumValues = [
    'MAVEN_MAVEN',
    'PLAIN_MAVEN',
    'PLAIN',
    'XCODE',
    'FACT',
    'GCC',
    'PLAIN_GRADLE',
    'GRADLE_GRADLE',
    'MAVEN_BLACKBOX',
] as const;
