/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.8
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ExerciseGenerationFileChange } from './exercise-generation-file-change';
import type { ExerciseGenerationEvent } from './exercise-generation-event';

export interface ExerciseGenerationStatus {
    jobId: string;
    running: boolean;
    mode?: ExerciseGenerationStatusModeEnum;
    events: Array<ExerciseGenerationEvent>;
    fileChanges: Array<ExerciseGenerationFileChange>;
    revertAvailable: boolean;
    revertJobId?: string;
    revertMode?: ExerciseGenerationStatusRevertModeEnum;
    ownedByCaller: boolean;
    cancellable: boolean;
    specDocument?: string;
}

export type ExerciseGenerationStatusModeEnum = 'GENERATE' | 'ADAPT';

export const ExerciseGenerationStatusModeEnum = {
    Generate: 'GENERATE' as const,
    Adapt: 'ADAPT' as const,
} as const;

export const ExerciseGenerationStatusModeEnumValues = ['GENERATE', 'ADAPT'] as const;

export type ExerciseGenerationStatusRevertModeEnum = 'GENERATE' | 'ADAPT';

export const ExerciseGenerationStatusRevertModeEnum = {
    Generate: 'GENERATE' as const,
    Adapt: 'ADAPT' as const,
} as const;

export const ExerciseGenerationStatusRevertModeEnumValues = ['GENERATE', 'ADAPT'] as const;
