/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.8
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ExerciseGenerationVerdict } from './exercise-generation-verdict';

export interface ExerciseGenerationEvent {
    type: ExerciseGenerationEventTypeEnum;
    message?: string;
    completionStatus?: ExerciseGenerationEventCompletionStatusEnum;
    verdict?: ExerciseGenerationVerdict;
    liveExerciseChanged?: boolean;
    timestamp: string;
}

export type ExerciseGenerationEventTypeEnum = 'STARTED' | 'PROGRESS' | 'DONE' | 'CANCELLED' | 'ERROR';

export const ExerciseGenerationEventTypeEnum = {
    Started: 'STARTED' as const,
    Progress: 'PROGRESS' as const,
    Done: 'DONE' as const,
    Cancelled: 'CANCELLED' as const,
    Error: 'ERROR' as const,
} as const;

export const ExerciseGenerationEventTypeEnumValues = ['STARTED', 'PROGRESS', 'DONE', 'CANCELLED', 'ERROR'] as const;

export type ExerciseGenerationEventCompletionStatusEnum = 'SUCCESS' | 'NEEDS_REVIEW' | 'PARTIAL';

export const ExerciseGenerationEventCompletionStatusEnum = {
    Success: 'SUCCESS' as const,
    NeedsReview: 'NEEDS_REVIEW' as const,
    Partial: 'PARTIAL' as const,
} as const;

export const ExerciseGenerationEventCompletionStatusEnumValues = ['SUCCESS', 'NEEDS_REVIEW', 'PARTIAL'] as const;
