/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.9
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * A file of a generated candidate that was not saved to the exercise
 */
export interface ExerciseGenerationRetainedFile {
    /** Owning repository bucket */
    repo: ExerciseGenerationRetainedFileRepoEnum;
    /** Repository-relative file path */
    path: string;
    /** The file\'s text content as the agent left it */
    content: string;
}

export type ExerciseGenerationRetainedFileRepoEnum = 'solution' | 'template' | 'tests';

export const ExerciseGenerationRetainedFileRepoEnum = {
    Solution: 'solution' as const,
    Template: 'template' as const,
    Tests: 'tests' as const,
} as const;

export const ExerciseGenerationRetainedFileRepoEnumValues = ['solution', 'template', 'tests'] as const;
