/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One generated answer option
 */
export interface GeneratedQuizAnswerOption { 
    /**
     * Answer option text
     */
    text: string;
    /**
     * Whether this option is correct
     */
    correct?: boolean;
    /**
     * Optional hint
     */
    hint?: string;
    /**
     * Optional explanation
     */
    explanation?: string;
}

