/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

export interface GenerationWorkerStatus {
    workerId?: string;
    state?: GenerationWorkerStatusStateEnum;
    lastHeartbeat?: string;
    imageDigest?: string;
    incarnation?: string;
    activeExecution?: string;
    leaseHeld?: boolean;
}

export type GenerationWorkerStatusStateEnum = 'OFFLINE' | 'NOT_READY' | 'AVAILABLE' | 'RESERVED' | 'BUSY';

export const GenerationWorkerStatusStateEnum = {
    Offline: 'OFFLINE' as const,
    NotReady: 'NOT_READY' as const,
    Available: 'AVAILABLE' as const,
    Reserved: 'RESERVED' as const,
    Busy: 'BUSY' as const,
} as const;

export const GenerationWorkerStatusStateEnumValues = ['OFFLINE', 'NOT_READY', 'AVAILABLE', 'RESERVED', 'BUSY'] as const;
