/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratedQuizAnswerOption } from './generatedQuizAnswerOption';


/**
 * One generated quiz question
 */
export interface GeneratedQuizQuestion { 
    /**
     * Question type
     */
    type: GeneratedQuizQuestion.TypeEnum;
    /**
     * Question title
     */
    title: string;
    /**
     * Question text
     */
    questionText: string;
    /**
     * Answer options
     */
    options: Array<GeneratedQuizAnswerOption>;
}
export namespace GeneratedQuizQuestion {
    export const TypeEnum = {
        SingleChoice: 'single-choice',
        MultipleChoice: 'multiple-choice',
        TrueFalse: 'true-false'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


