/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface IndexedEntity {
    type?: string;
    entityId?: number;
    title?: string;
    lectureId?: number;
    ingestedAt?: string;
    expected?: boolean;
}
