/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { IndexedCollectionCount } from './indexed-collection-count';

export interface IndexOverview {
    weaviateReachable: boolean;
    weaviateAddress?: string;
    irisEnabled: boolean;
    irisReachable: boolean;
    collections?: Array<IndexedCollectionCount>;
}
