/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InferredCompetency { 
    knowledgeAreaShortTitle?: string;
    competencyTitle?: string;
    competencyVersion?: string;
    catalogSourceId?: number;
    taxonomyLevel?: string;
    confidence?: number;
    rank?: number;
    evidence?: Array<string>;
    whyThisMatches?: string;
    isLikelyPrimary?: boolean;
    relatedTaskNames?: Array<string>;
    taskCoverageRatio?: number;
    testCoverageRatio?: number;
}

