/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { IngestionTypeCount } from './ingestion-type-count';

export interface IngestionCoverage {
    courseId: number;
    courseTitle?: string;
    releaseDate?: string;
    active: boolean;
    semester?: string;
    status?: IngestionCoverageStatusEnum;
    coverageGapScore: number;
    computedAt?: string;
    lastIngestedAt?: string;
    typeCounts?: Array<IngestionTypeCount>;
}

export type IngestionCoverageStatusEnum = 'COMPLETE' | 'INCOMPLETE' | 'EMPTY';

export const IngestionCoverageStatusEnum = {
    Complete: 'COMPLETE' as const,
    Incomplete: 'INCOMPLETE' as const,
    Empty: 'EMPTY' as const,
} as const;

export const IngestionCoverageStatusEnumValues = ['COMPLETE', 'INCOMPLETE', 'EMPTY'] as const;

