/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { AnswerOptionWithSolution } from './answer-option-with-solution';

export interface MultipleChoiceQuizQuestionWithSolution {
    id?: number;
    title?: string;
    text?: string;
    hint?: string;
    points?: number;
    scoringType?: MultipleChoiceQuizQuestionWithSolutionScoringTypeEnum;
    randomizeOrder?: boolean;
    invalid?: boolean;
    type: MultipleChoiceQuizQuestionWithSolutionTypeEnum;
    explanation?: string;
    answerOptions?: Array<AnswerOptionWithSolution>;
    singleChoice?: boolean;
}

export type MultipleChoiceQuizQuestionWithSolutionScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const MultipleChoiceQuizQuestionWithSolutionScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const MultipleChoiceQuizQuestionWithSolutionScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type MultipleChoiceQuizQuestionWithSolutionTypeEnum = 'multiple-choice';

export const MultipleChoiceQuizQuestionWithSolutionTypeEnum = {
    MultipleChoice: 'multiple-choice' as const,
} as const;

export const MultipleChoiceQuizQuestionWithSolutionTypeEnumValues = ['multiple-choice'] as const;

