/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { AnswerCounter } from './answer-counter';

export interface MultipleChoiceQuizQuestionStatistic {
    id?: number;
    participantsRated?: number;
    participantsUnrated?: number;
    ratedCorrectCounter?: number;
    unRatedCorrectCounter?: number;
    answerCounters?: Array<AnswerCounter>;
    type: MultipleChoiceQuizQuestionStatisticTypeEnum;
}

export type MultipleChoiceQuizQuestionStatisticTypeEnum = 'multiple-choice';

export const MultipleChoiceQuizQuestionStatisticTypeEnum = {
    MultipleChoice: 'multiple-choice' as const,
} as const;

export const MultipleChoiceQuizQuestionStatisticTypeEnumValues = ['multiple-choice'] as const;
