/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { AnswerOptionWithoutSolution } from './answer-option-without-solution';

export interface MultipleChoiceQuizQuestionWithoutSolution {
    id?: number;
    title?: string;
    text?: string;
    hint?: string;
    points?: number;
    scoringType?: MultipleChoiceQuizQuestionWithoutSolutionScoringTypeEnum;
    randomizeOrder?: boolean;
    invalid?: boolean;
    type: MultipleChoiceQuizQuestionWithoutSolutionTypeEnum;
    answerOptions?: Array<AnswerOptionWithoutSolution>;
    singleChoice?: boolean;
}

export type MultipleChoiceQuizQuestionWithoutSolutionScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const MultipleChoiceQuizQuestionWithoutSolutionScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const MultipleChoiceQuizQuestionWithoutSolutionScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type MultipleChoiceQuizQuestionWithoutSolutionTypeEnum = 'multiple-choice';

export const MultipleChoiceQuizQuestionWithoutSolutionTypeEnum = {
    MultipleChoice: 'multiple-choice' as const,
} as const;

export const MultipleChoiceQuizQuestionWithoutSolutionTypeEnumValues = ['multiple-choice'] as const;
