/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { AnswerOptionReEvaluate } from './answer-option-re-evaluate';

export interface MultipleChoiceQuestionReEvaluate {
    id: number;
    title: string;
    scoringType: MultipleChoiceQuestionReEvaluateScoringTypeEnum;
    randomizeOrder: boolean;
    invalid: boolean;
    text?: string;
    hint?: string;
    explanation?: string;
    answerOptions: Array<AnswerOptionReEvaluate>;
    type: MultipleChoiceQuestionReEvaluateTypeEnum;
}

export type MultipleChoiceQuestionReEvaluateScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const MultipleChoiceQuestionReEvaluateScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const MultipleChoiceQuestionReEvaluateScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type MultipleChoiceQuestionReEvaluateTypeEnum = 'multiple-choice';

export const MultipleChoiceQuestionReEvaluateTypeEnum = {
    MultipleChoice: 'multiple-choice' as const,
} as const;

export const MultipleChoiceQuestionReEvaluateTypeEnumValues = ['multiple-choice'] as const;
