/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing generated problem statement
 */
export interface ProblemStatementRefinementResponse { 
    /**
     * Refined problem statement text
     */
    refinedProblemStatement?: string;
    /**
     * Original problem statement if refinement failed
     */
    originalProblemStatement?: string;
}

