/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing the generated problem statement and the metadata the draft proposes for instructor review
 */
export interface ProblemStatementGenerationResponse {
    /**
     * Draft problem statement text
     */
    draftProblemStatement?: string;
    /**
     * Proposed exercise title
     */
    suggestedTitle?: string;
    /**
     * Proposed difficulty (EASY, MEDIUM or HARD)
     */
    suggestedDifficulty?: ProblemStatementGenerationResponse.SuggestedDifficultyEnum;
    /**
     * Proposed topic categories (raw, to be snapped to the course taxonomy on the client)
     */
    suggestedCategories?: Array<string>;
}
export namespace ProblemStatementGenerationResponse {
    export const SuggestedDifficultyEnum = {
        Easy: 'EASY',
        Medium: 'MEDIUM',
        Hard: 'HARD'
    } as const;
    export type SuggestedDifficultyEnum = typeof SuggestedDifficultyEnum[keyof typeof SuggestedDifficultyEnum];
}

