/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to refine a problem statement globally using a user prompt
 */
export interface ProblemStatementGlobalRefinementRequest { 
    /**
     * Original problem statement text to be refined (max 50,000 chars)
     */
    problemStatementText: string;
    /**
     * User prompt for global refinement
     */
    userPrompt?: string;
}

