/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to rewrite a problem statement
 */
export interface ProblemStatementRefinementRequest { 
    /**
     * Original problem statement text to be refined
     */
    problemStatementText: string;
    /**
     * User prompt describing the problem statement requirements
     */
    userPrompt: string;
}

