/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualityIssueLocation } from './qualityIssueLocation';


/**
 * A quality issue found in the problem statement
 */
export interface QualityIssue { 
    /**
     * Issue category: CLARITY, COHERENCE, or COMPLETENESS
     */
    category?: QualityIssue.CategoryEnum;
    /**
     * Issue severity: LOW, MEDIUM, or HIGH
     */
    severity?: QualityIssue.SeverityEnum;
    /**
     * Description of what is wrong
     */
    description?: string;
    /**
     * Location in the problem statement
     */
    location?: QualityIssueLocation;
    /**
     * Concrete suggestion to fix the issue
     */
    suggestedFix?: string;
    /**
     * How this issue increases extraneous cognitive load
     */
    impactOnLearners?: string;
}
export namespace QualityIssue {
    export const CategoryEnum = {
        Clarity: 'CLARITY',
        Coherence: 'COHERENCE',
        Completeness: 'COMPLETENESS'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
    export const SeverityEnum = {
        Low: 'LOW',
        Medium: 'MEDIUM',
        High: 'HIGH'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


