/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizQuestionStatistic } from './quiz-question-statistic';

export interface QuestionStatistics {
    id?: number;
    title?: string;
    points?: number;
    invalid?: boolean;
    quizQuestionStatistic?: QuizQuestionStatistic;
}
