/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { CourseForQuizExercise } from './course-for-quiz-exercise';
import type { ExerciseVariantGroupReference } from './exercise-variant-group-reference';
import type { QuizQuestionWithSolution } from './quiz-question-with-solution';
import type { QuizBatch } from './quiz-batch';

export interface QuizExerciseWithSolutionForStudent {
    id?: number;
    title?: string;
    shortName?: string;
    releaseDate?: string;
    startDate?: string;
    dueDate?: string;
    assessmentDueDate?: string;
    difficulty?: QuizExerciseWithSolutionForStudentDifficultyEnum;
    visibleToStudents?: boolean;
    course?: CourseForQuizExercise;
    type?: string;
    randomizeQuestionOrder?: boolean;
    allowedNumberOfAttempts?: number;
    remainingNumberOfAttempts?: number;
    quizMode?: QuizExerciseWithSolutionForStudentQuizModeEnum;
    duration?: number;
    quizBatches?: Array<QuizBatch>;
    quizStarted?: boolean;
    quizEnded?: boolean;
    includedInOverallScore?: QuizExerciseWithSolutionForStudentIncludedInOverallScoreEnum;
    mode?: QuizExerciseWithSolutionForStudentModeEnum;
    maxPoints?: number;
    bonusPoints?: number;
    exerciseVariantGroup?: ExerciseVariantGroupReference;
    quizQuestions?: Array<QuizQuestionWithSolution>;
    quizQuestionsType: QuizExerciseWithSolutionForStudentQuizQuestionsTypeEnum;
}

export type QuizExerciseWithSolutionForStudentDifficultyEnum = 'EASY' | 'MEDIUM' | 'HARD';

export const QuizExerciseWithSolutionForStudentDifficultyEnum = {
    Easy: 'EASY' as const,
    Medium: 'MEDIUM' as const,
    Hard: 'HARD' as const,
} as const;

export const QuizExerciseWithSolutionForStudentDifficultyEnumValues = ['EASY', 'MEDIUM', 'HARD'] as const;

export type QuizExerciseWithSolutionForStudentQuizModeEnum = 'SYNCHRONIZED' | 'BATCHED' | 'INDIVIDUAL';

export const QuizExerciseWithSolutionForStudentQuizModeEnum = {
    Synchronized: 'SYNCHRONIZED' as const,
    Batched: 'BATCHED' as const,
    Individual: 'INDIVIDUAL' as const,
} as const;

export const QuizExerciseWithSolutionForStudentQuizModeEnumValues = ['SYNCHRONIZED', 'BATCHED', 'INDIVIDUAL'] as const;

export type QuizExerciseWithSolutionForStudentIncludedInOverallScoreEnum = 'INCLUDED_COMPLETELY' | 'INCLUDED_AS_BONUS' | 'NOT_INCLUDED';

export const QuizExerciseWithSolutionForStudentIncludedInOverallScoreEnum = {
    IncludedCompletely: 'INCLUDED_COMPLETELY' as const,
    IncludedAsBonus: 'INCLUDED_AS_BONUS' as const,
    NotIncluded: 'NOT_INCLUDED' as const,
} as const;

export const QuizExerciseWithSolutionForStudentIncludedInOverallScoreEnumValues = ['INCLUDED_COMPLETELY', 'INCLUDED_AS_BONUS', 'NOT_INCLUDED'] as const;

export type QuizExerciseWithSolutionForStudentModeEnum = 'INDIVIDUAL' | 'TEAM';

export const QuizExerciseWithSolutionForStudentModeEnum = {
    Individual: 'INDIVIDUAL' as const,
    Team: 'TEAM' as const,
} as const;

export const QuizExerciseWithSolutionForStudentModeEnumValues = ['INDIVIDUAL', 'TEAM'] as const;

export type QuizExerciseWithSolutionForStudentQuizQuestionsTypeEnum = 'after-quiz-end';

export const QuizExerciseWithSolutionForStudentQuizQuestionsTypeEnum = {
    AfterQuizEnd: 'after-quiz-end' as const,
} as const;

export const QuizExerciseWithSolutionForStudentQuizQuestionsTypeEnumValues = ['after-quiz-end'] as const;
