/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizQuestionCreate } from './quiz-question-create';
import type { QuizBatchCreation } from './quiz-batch-creation';
import type { CompetencyLink } from './competency-link';

export interface QuizExerciseCreate {
    title: string;
    releaseDate?: string;
    startDate?: string;
    dueDate?: string;
    difficulty?: QuizExerciseCreateDifficultyEnum;
    mode: QuizExerciseCreateModeEnum;
    includedInOverallScore: QuizExerciseCreateIncludedInOverallScoreEnum;
    competencyLinks?: Array<CompetencyLink>;
    categories?: Array<string>;
    channelName?: string;
    randomizeQuestionOrder?: boolean;
    quizMode: QuizExerciseCreateQuizModeEnum;
    duration?: number;
    quizBatches?: Array<QuizBatchCreation>;
    quizQuestions: Array<QuizQuestionCreate>;
}

export type QuizExerciseCreateDifficultyEnum = 'EASY' | 'MEDIUM' | 'HARD';

export const QuizExerciseCreateDifficultyEnum = {
    Easy: 'EASY' as const,
    Medium: 'MEDIUM' as const,
    Hard: 'HARD' as const,
} as const;

export const QuizExerciseCreateDifficultyEnumValues = ['EASY', 'MEDIUM', 'HARD'] as const;

export type QuizExerciseCreateModeEnum = 'INDIVIDUAL' | 'TEAM';

export const QuizExerciseCreateModeEnum = {
    Individual: 'INDIVIDUAL' as const,
    Team: 'TEAM' as const,
} as const;

export const QuizExerciseCreateModeEnumValues = ['INDIVIDUAL', 'TEAM'] as const;

export type QuizExerciseCreateIncludedInOverallScoreEnum = 'INCLUDED_COMPLETELY' | 'INCLUDED_AS_BONUS' | 'NOT_INCLUDED';

export const QuizExerciseCreateIncludedInOverallScoreEnum = {
    IncludedCompletely: 'INCLUDED_COMPLETELY' as const,
    IncludedAsBonus: 'INCLUDED_AS_BONUS' as const,
    NotIncluded: 'NOT_INCLUDED' as const,
} as const;

export const QuizExerciseCreateIncludedInOverallScoreEnumValues = ['INCLUDED_COMPLETELY', 'INCLUDED_AS_BONUS', 'NOT_INCLUDED'] as const;

export type QuizExerciseCreateQuizModeEnum = 'SYNCHRONIZED' | 'BATCHED' | 'INDIVIDUAL';

export const QuizExerciseCreateQuizModeEnum = {
    Synchronized: 'SYNCHRONIZED' as const,
    Batched: 'BATCHED' as const,
    Individual: 'INDIVIDUAL' as const,
} as const;

export const QuizExerciseCreateQuizModeEnumValues = ['SYNCHRONIZED', 'BATCHED', 'INDIVIDUAL'] as const;
