/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */
import type { MultipleChoiceQuizQuestionWithoutSolution } from './multiple-choice-quiz-question-without-solution';
import type { DragAndDropQuizQuestionWithoutSolution } from './drag-and-drop-quiz-question-without-solution';
import type { ShortAnswerQuizQuestionWithoutSolution } from './short-answer-quiz-question-without-solution';
export type QuizQuestionWithoutSolution = MultipleChoiceQuizQuestionWithoutSolution | DragAndDropQuizQuestionWithoutSolution | ShortAnswerQuizQuestionWithoutSolution;
