/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizSearchExerciseGroup } from './quiz-search-exercise-group';
import type { QuizSearchCourse } from './quiz-search-course';

export interface QuizExerciseForSearch {
    type?: string;
    id?: number;
    title?: string;
    course?: QuizSearchCourse;
    exerciseGroup?: QuizSearchExerciseGroup;
}
