/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizQuestionRefinementResponse } from './quizQuestionRefinementResponse';


/**
 * Response containing one refinement result per input question, in the same order as request
 */
export interface QuizQuestionBulkRefinementResponse { 
    /**
     * Refinement results, one per input question in the same order
     */
    refinements: Array<QuizQuestionRefinementResponse>;
}

