/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratedQuizQuestion } from './generatedQuizQuestion';


/**
 * Successful refinement result containing the refined question and an explanation of the changes
 */
export interface QuizQuestionRefinementSuccess { 
    type: QuizQuestionRefinementSuccess.TypeEnum;
    question: GeneratedQuizQuestion;
    /**
     * Brief explanation of what was changed during refinement
     */
    reasoning: string;
}
export namespace QuizQuestionRefinementSuccess {
    export const TypeEnum = {
        Success: 'success'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


