/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratedQuizQuestion } from './generatedQuizQuestion';


/**
 * Response containing generated quiz questions
 */
export interface QuizQuestionGenerationResponse { 
    /**
     * Generated quiz questions
     */
    questions: Array<GeneratedQuizQuestion>;
}

