/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { CourseForQuizExercise } from './course-for-quiz-exercise';
import type { ExerciseVariantGroupReference } from './exercise-variant-group-reference';
import type { QuizBatch } from './quiz-batch';

export interface QuizExerciseWithoutQuestions {
    id?: number;
    title?: string;
    shortName?: string;
    releaseDate?: string;
    startDate?: string;
    dueDate?: string;
    assessmentDueDate?: string;
    difficulty?: QuizExerciseWithoutQuestionsDifficultyEnum;
    visibleToStudents?: boolean;
    course?: CourseForQuizExercise;
    type?: string;
    randomizeQuestionOrder?: boolean;
    allowedNumberOfAttempts?: number;
    remainingNumberOfAttempts?: number;
    quizMode?: QuizExerciseWithoutQuestionsQuizModeEnum;
    duration?: number;
    quizBatches?: Array<QuizBatch>;
    quizStarted?: boolean;
    quizEnded?: boolean;
    includedInOverallScore?: QuizExerciseWithoutQuestionsIncludedInOverallScoreEnum;
    mode?: QuizExerciseWithoutQuestionsModeEnum;
    maxPoints?: number;
    bonusPoints?: number;
    exerciseVariantGroup?: ExerciseVariantGroupReference;
}

export type QuizExerciseWithoutQuestionsDifficultyEnum = 'EASY' | 'MEDIUM' | 'HARD';

export const QuizExerciseWithoutQuestionsDifficultyEnum = {
    Easy: 'EASY' as const,
    Medium: 'MEDIUM' as const,
    Hard: 'HARD' as const,
} as const;

export const QuizExerciseWithoutQuestionsDifficultyEnumValues = ['EASY', 'MEDIUM', 'HARD'] as const;

export type QuizExerciseWithoutQuestionsQuizModeEnum = 'SYNCHRONIZED' | 'BATCHED' | 'INDIVIDUAL';

export const QuizExerciseWithoutQuestionsQuizModeEnum = {
    Synchronized: 'SYNCHRONIZED' as const,
    Batched: 'BATCHED' as const,
    Individual: 'INDIVIDUAL' as const,
} as const;

export const QuizExerciseWithoutQuestionsQuizModeEnumValues = ['SYNCHRONIZED', 'BATCHED', 'INDIVIDUAL'] as const;

export type QuizExerciseWithoutQuestionsIncludedInOverallScoreEnum = 'INCLUDED_COMPLETELY' | 'INCLUDED_AS_BONUS' | 'NOT_INCLUDED';

export const QuizExerciseWithoutQuestionsIncludedInOverallScoreEnum = {
    IncludedCompletely: 'INCLUDED_COMPLETELY' as const,
    IncludedAsBonus: 'INCLUDED_AS_BONUS' as const,
    NotIncluded: 'NOT_INCLUDED' as const,
} as const;

export const QuizExerciseWithoutQuestionsIncludedInOverallScoreEnumValues = ['INCLUDED_COMPLETELY', 'INCLUDED_AS_BONUS', 'NOT_INCLUDED'] as const;

export type QuizExerciseWithoutQuestionsModeEnum = 'INDIVIDUAL' | 'TEAM';

export const QuizExerciseWithoutQuestionsModeEnum = {
    Individual: 'INDIVIDUAL' as const,
    Team: 'TEAM' as const,
} as const;

export const QuizExerciseWithoutQuestionsModeEnumValues = ['INDIVIDUAL', 'TEAM'] as const;
