/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratedQuizQuestion } from './generatedQuizQuestion';


/**
 * Request to refine multiple quiz questions at once using a single user prompt
 */
export interface QuizQuestionBulkRefinementRequest { 
    /**
     * The quiz questions to refine
     */
    questions: Array<GeneratedQuizQuestion>;
    /**
     * User instructions describing how all questions should be changed
     */
    refinementPrompt: string;
}

