/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizSearchCourse } from './quiz-search-course';

export interface QuizSearchExam {
    title?: string;
    course?: QuizSearchCourse;
}
