/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizBatchForCourse } from './quiz-batch-for-course';

export interface QuizExerciseForCourse {
    id?: number;
    title: string;
    quizStarted?: boolean;
    quizEnded?: boolean;
    isEditable?: boolean;
    duration?: number;
    maxPoints?: number;
    releaseDate?: string;
    startDate?: string;
    dueDate?: string;
    includedInOverallScore: QuizExerciseForCourseIncludedInOverallScoreEnum;
    quizBatches?: Array<QuizBatchForCourse>;
    quizMode: QuizExerciseForCourseQuizModeEnum;
    categories?: Array<string>;
}

export type QuizExerciseForCourseIncludedInOverallScoreEnum = 'INCLUDED_COMPLETELY' | 'INCLUDED_AS_BONUS' | 'NOT_INCLUDED';

export const QuizExerciseForCourseIncludedInOverallScoreEnum = {
    IncludedCompletely: 'INCLUDED_COMPLETELY' as const,
    IncludedAsBonus: 'INCLUDED_AS_BONUS' as const,
    NotIncluded: 'NOT_INCLUDED' as const,
} as const;

export const QuizExerciseForCourseIncludedInOverallScoreEnumValues = ['INCLUDED_COMPLETELY', 'INCLUDED_AS_BONUS', 'NOT_INCLUDED'] as const;

export type QuizExerciseForCourseQuizModeEnum = 'SYNCHRONIZED' | 'BATCHED' | 'INDIVIDUAL';

export const QuizExerciseForCourseQuizModeEnum = {
    Synchronized: 'SYNCHRONIZED' as const,
    Batched: 'BATCHED' as const,
    Individual: 'INDIVIDUAL' as const,
} as const;

export const QuizExerciseForCourseQuizModeEnumValues = ['SYNCHRONIZED', 'BATCHED', 'INDIVIDUAL'] as const;
