/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing rewritten FAQ
 */
export interface RewriteFaqResponse { 
    rewrittenText?: string;
    inconsistencies?: Array<string>;
    suggestions?: Array<string>;
    improvement?: string;
}

