/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ShortAnswerSpotCounter } from './short-answer-spot-counter';

export interface ShortAnswerQuestionStatistic {
    participantsRated?: number;
    participantsUnrated?: number;
    ratedCorrectCounter?: number;
    unRatedCorrectCounter?: number;
    shortAnswerSpotCounters?: Array<ShortAnswerSpotCounter>;
    type: ShortAnswerQuestionStatisticTypeEnum;
}

export type ShortAnswerQuestionStatisticTypeEnum = 'short-answer';

export const ShortAnswerQuestionStatisticTypeEnum = {
    ShortAnswer: 'short-answer' as const,
} as const;

export const ShortAnswerQuestionStatisticTypeEnumValues = ['short-answer'] as const;
