/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ShortAnswerSpotCounter } from './short-answer-spot-counter';

export interface ShortAnswerQuizQuestionStatistic {
    id?: number;
    participantsRated?: number;
    participantsUnrated?: number;
    ratedCorrectCounter?: number;
    unRatedCorrectCounter?: number;
    shortAnswerSpotCounters?: Array<ShortAnswerSpotCounter>;
    type: ShortAnswerQuizQuestionStatisticTypeEnum;
}

export type ShortAnswerQuizQuestionStatisticTypeEnum = 'short-answer';

export const ShortAnswerQuizQuestionStatisticTypeEnum = {
    ShortAnswer: 'short-answer' as const,
} as const;

export const ShortAnswerQuizQuestionStatisticTypeEnumValues = ['short-answer'] as const;
