/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ShortAnswerMappingCreate } from './short-answer-mapping-create';
import type { ShortAnswerSolutionCreate } from './short-answer-solution-create';
import type { ShortAnswerSpotCreate } from './short-answer-spot-create';

export interface ShortAnswerQuestionCreate {
    title: string;
    text?: string;
    hint?: string;
    explanation?: string;
    points: number;
    scoringType: ShortAnswerQuestionCreateScoringTypeEnum;
    randomizeOrder?: boolean;
    spots: Array<ShortAnswerSpotCreate>;
    solutions: Array<ShortAnswerSolutionCreate>;
    correctMappings: Array<ShortAnswerMappingCreate>;
    similarityValue: number;
    matchLetterCase: boolean;
    type: ShortAnswerQuestionCreateTypeEnum;
}

export type ShortAnswerQuestionCreateScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const ShortAnswerQuestionCreateScoringTypeEnum = {
    AllOrNothing: 'ALL_OR_NOTHING' as const,
    ProportionalWithPenalty: 'PROPORTIONAL_WITH_PENALTY' as const,
    ProportionalWithoutPenalty: 'PROPORTIONAL_WITHOUT_PENALTY' as const,
} as const;

export const ShortAnswerQuestionCreateScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

export type ShortAnswerQuestionCreateTypeEnum = 'short-answer';

export const ShortAnswerQuestionCreateTypeEnum = {
    ShortAnswer: 'short-answer' as const,
} as const;

export const ShortAnswerQuestionCreateTypeEnumValues = ['short-answer'] as const;
