/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizExerciseWithSolution } from './quiz-exercise-with-solution';
import type { QuizSubmissionAfterEvaluation } from './quiz-submission-after-evaluation';
import type { DomainObject } from './domain-object';

export interface StudentQuizParticipationWithSolutions {
    id?: number;
    type?: string;
    initializationState?: StudentQuizParticipationWithSolutionsInitializationStateEnum;
    initializationDate?: string;
    student?: DomainObject;
    exercise?: QuizExerciseWithSolution;
    submissions?: Array<QuizSubmissionAfterEvaluation>;
    quizQuestionsType: StudentQuizParticipationWithSolutionsQuizQuestionsTypeEnum;
}

export type StudentQuizParticipationWithSolutionsInitializationStateEnum = 'UNINITIALIZED' | 'REPO_COPIED' | 'REPO_CONFIGURED' | 'INACTIVE' | 'BUILD_PLAN_COPIED' | 'BUILD_PLAN_CONFIGURED' | 'INITIALIZED' | 'FINISHED';

export const StudentQuizParticipationWithSolutionsInitializationStateEnum = {
    Uninitialized: 'UNINITIALIZED' as const,
    RepoCopied: 'REPO_COPIED' as const,
    RepoConfigured: 'REPO_CONFIGURED' as const,
    Inactive: 'INACTIVE' as const,
    BuildPlanCopied: 'BUILD_PLAN_COPIED' as const,
    BuildPlanConfigured: 'BUILD_PLAN_CONFIGURED' as const,
    Initialized: 'INITIALIZED' as const,
    Finished: 'FINISHED' as const,
} as const;

export const StudentQuizParticipationWithSolutionsInitializationStateEnumValues = ['UNINITIALIZED', 'REPO_COPIED', 'REPO_CONFIGURED', 'INACTIVE', 'BUILD_PLAN_COPIED', 'BUILD_PLAN_CONFIGURED', 'INITIALIZED', 'FINISHED'] as const;

export type StudentQuizParticipationWithSolutionsQuizQuestionsTypeEnum = 'after-quiz-end';

export const StudentQuizParticipationWithSolutionsQuizQuestionsTypeEnum = {
    AfterQuizEnd: 'after-quiz-end' as const,
} as const;

export const StudentQuizParticipationWithSolutionsQuizQuestionsTypeEnumValues = ['after-quiz-end'] as const;
