/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { MultipleChoiceSubmittedAnswerFromStudent } from './multiple-choice-submitted-answer-from-student';
import type { ShortAnswerSubmittedAnswerFromStudent } from './short-answer-submitted-answer-from-student';
import type { DragAndDropSubmittedAnswerFromStudent } from './drag-and-drop-submitted-answer-from-student';

export type SubmittedAnswerFromStudent = MultipleChoiceSubmittedAnswerFromStudent | DragAndDropSubmittedAnswerFromStudent | ShortAnswerSubmittedAnswerFromStudent;
