/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TutorialGroupSchedule } from './tutorialGroupSchedule';
import { TutorialGroupSession } from './tutorialGroupSession';
import { User } from './user';
import { Channel } from './channel';
import { TutorialGroupRegistration } from './tutorialGroupRegistration';
import { Course } from './course';


export interface TutorialGroupResponse { 
    id: number;
    title: string;
    course?: Course;
    capacity?: number;
    campus?: string;
    language?: string;
    additionalInformation?: string;
    isOnline?: boolean;
    teachingAssistant?: User;
    tutorialGroupSchedule?: TutorialGroupSchedule;
    tutorialGroupSessions?: Array<TutorialGroupSession>;
    registrations?: Array<TutorialGroupRegistration>;
    channel?: Channel;
    isUserRegistered?: boolean;
    isUserTutor?: boolean;
    numberOfRegisteredUsers?: number;
    teachingAssistantName?: string;
    teachingAssistantId?: number;
    teachingAssistantImageUrl?: string;
    courseTitle?: string;
    nextSession?: TutorialGroupSession;
    averageAttendance?: number;
}

