/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TutorialGroupSessionSchedule } from './tutorialGroupSessionSchedule';
import { TutorialGroupFreePeriod } from './tutorialGroupFreePeriod';


export interface TutorialGroupSession { 
    id?: number;
    start?: string;
    end?: string;
    status?: TutorialGroupSession.StatusEnum;
    statusExplanation?: string;
    location?: string;
    attendanceCount?: number;
    tutorialGroupSchedule?: TutorialGroupSessionSchedule;
    tutorialGroupFreePeriod?: TutorialGroupFreePeriod;
}
export namespace TutorialGroupSession {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


