/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentExport } from './studentExport';


export interface TutorialGroupExport { 
    id?: number;
    title?: string;
    dayOfWeek?: string;
    startTime?: string;
    endTime?: string;
    location?: string;
    campus?: string;
    language?: string;
    additionalInformation?: string;
    capacity?: number;
    isOnline?: boolean;
    students?: Array<StudentExport>;
}

