/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { TutorialGroupFreePeriod } from './tutorial-group-free-period';

export interface TutorialGroupSummarySession {
    id?: number;
    start?: string;
    end?: string;
    status?: TutorialGroupSummarySessionStatusEnum;
    statusExplanation?: string;
    location?: string;
    tutorialGroupFreePeriod?: TutorialGroupFreePeriod;
    attendanceCount?: number;
}

export type TutorialGroupSummarySessionStatusEnum = 'ACTIVE' | 'CANCELLED';

export const TutorialGroupSummarySessionStatusEnum = {
    Active: 'ACTIVE' as const,
    Cancelled: 'CANCELLED' as const,
} as const;

export const TutorialGroupSummarySessionStatusEnumValues = ['ACTIVE', 'CANCELLED'] as const;
