/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface TutorialGroupSummarySchedule {
    id?: number;
    dayOfWeek?: number;
    startTime?: string;
    endTime?: string;
    repetitionFrequency?: number;
    location?: string;
    validFromInclusive?: string;
    validToInclusive?: string;
}
