/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Student } from './student';


export interface TutorialGroupRegistrationImport { 
    title?: string;
    student?: Student;
    importSuccessful?: boolean;
    error?: TutorialGroupRegistrationImport.ErrorEnum;
    campus?: string;
    capacity?: number;
    language?: string;
    additionalInformation?: string;
    isOnline?: boolean;
}
export namespace TutorialGroupRegistrationImport {
    export type ErrorEnum = 'NO_TITLE' | 'NO_USER_FOUND' | 'MULTIPLE_REGISTRATIONS';
    export const ErrorEnum = {
        NoTitle: 'NO_TITLE' as ErrorEnum,
        NoUserFound: 'NO_USER_FOUND' as ErrorEnum,
        MultipleRegistrations: 'MULTIPLE_REGISTRATIONS' as ErrorEnum
    };
}


