/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.8
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { CreateExerciseVariantGroup } from './create-exercise-variant-group';

export interface VariantPlacement {
    type?: VariantPlacementTypeEnum;
    existingGroupId?: number | null;
    newGroup?: CreateExerciseVariantGroup;
}

export type VariantPlacementTypeEnum = 'EXISTING_GROUP' | 'NEW_GROUP' | 'STANDALONE' | 'SAME_EXAM_GROUP';

export const VariantPlacementTypeEnum = {
    ExistingGroup: 'EXISTING_GROUP' as const,
    NewGroup: 'NEW_GROUP' as const,
    Standalone: 'STANDALONE' as const,
    SameExamGroup: 'SAME_EXAM_GROUP' as const,
} as const;

export const VariantPlacementTypeEnumValues = ['EXISTING_GROUP', 'NEW_GROUP', 'STANDALONE', 'SAME_EXAM_GROUP'] as const;

