/**
 * Artemis Application Server API
 *
 * Contact: krusche@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VariantGenerationRequest } from './variantGenerationRequest';


export interface VariantJob { 
    jobId?: string;
    sourceExerciseId?: number;
    courseId?: number;
    sourceExerciseTitle?: string;
    exerciseType?: VariantJob.ExerciseTypeEnum;
    phase?: VariantJob.PhaseEnum;
    failedInPhase?: VariantJob.FailedInPhaseEnum;
    failureDetail?: string;
    instructorSummary?: string;
    attempt?: number;
    maxAttempts?: number;
    variantExerciseId?: number;
    variantExerciseTitle?: string;
    request?: VariantGenerationRequest;
    warnings?: Array<string>;
    totalTokensUsed?: number;
    startedAt?: string;
    finishedAt?: string;
}
export namespace VariantJob {
    export const ExerciseTypeEnum = {
        Text: 'text',
        Programming: 'programming',
        Modeling: 'modeling',
        FileUpload: 'file-upload',
        Quiz: 'quiz'
    } as const;
    export type ExerciseTypeEnum = typeof ExerciseTypeEnum[keyof typeof ExerciseTypeEnum];
    export const PhaseEnum = {
        Analyzing: 'ANALYZING',
        Planning: 'PLANNING',
        Provisioning: 'PROVISIONING',
        Transforming: 'TRANSFORMING',
        Verifying: 'VERIFYING',
        Repairing: 'REPAIRING',
        Finalizing: 'FINALIZING',
        Completed: 'COMPLETED',
        DraftWithWarnings: 'DRAFT_WITH_WARNINGS',
        Failed: 'FAILED',
        Cancelled: 'CANCELLED'
    } as const;
    export type PhaseEnum = typeof PhaseEnum[keyof typeof PhaseEnum];
    export const FailedInPhaseEnum = {
        Analyzing: 'ANALYZING',
        Planning: 'PLANNING',
        Provisioning: 'PROVISIONING',
        Transforming: 'TRANSFORMING',
        Verifying: 'VERIFYING',
        Repairing: 'REPAIRING',
        Finalizing: 'FINALIZING',
        Completed: 'COMPLETED',
        DraftWithWarnings: 'DRAFT_WITH_WARNINGS',
        Failed: 'FAILED',
        Cancelled: 'CANCELLED'
    } as const;
    export type FailedInPhaseEnum = typeof FailedInPhaseEnum[keyof typeof FailedInPhaseEnum];
}


