/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.8
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { VariantPlacement } from './variant-placement';

export interface VariantGenerationRequest {
    targetDifficulty?: VariantGenerationRequestTargetDifficultyEnum | null;
    domainText?: string | null;
    narrativeStyle?: VariantGenerationRequestNarrativeStyleEnum | null;
    additionalInstructions?: string | null;
    placement?: VariantPlacement;
}

export type VariantGenerationRequestTargetDifficultyEnum = 'EASY' | 'MEDIUM' | 'HARD';

export const VariantGenerationRequestTargetDifficultyEnum = {
    Easy: 'EASY' as const,
    Medium: 'MEDIUM' as const,
    Hard: 'HARD' as const,
} as const;

export const VariantGenerationRequestTargetDifficultyEnumValues = ['EASY', 'MEDIUM', 'HARD'] as const;

export type VariantGenerationRequestNarrativeStyleEnum = 'TECHNICAL' | 'REALISTIC' | 'CREATIVE' | 'IMAGINATIVE';

export const VariantGenerationRequestNarrativeStyleEnum = {
    Technical: 'TECHNICAL' as const,
    Realistic: 'REALISTIC' as const,
    Creative: 'CREATIVE' as const,
    Imaginative: 'IMAGINATIVE' as const,
} as const;

export const VariantGenerationRequestNarrativeStyleEnumValues = ['TECHNICAL', 'REALISTIC', 'CREATIVE', 'IMAGINATIVE'] as const;

