/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { WorkerExecution } from './worker-execution';
import type { WorkloadCapability } from './workload-capability';

export interface WorkerStatus {
    workerId?: string;
    state?: WorkerStatusStateEnum;
    lastHeartbeat?: string;
    imageDigest?: string;
    incarnation?: string;
    activeExecution?: string;
    leaseHeld?: boolean;
    capacity?: number;
    availableSlots?: number;
    executions?: Array<WorkerExecution>;
    capability?: WorkloadCapability;
}

export type WorkerStatusStateEnum = 'OFFLINE' | 'NOT_READY' | 'AVAILABLE' | 'RESERVED' | 'BUSY';

export const WorkerStatusStateEnum = {
    Offline: 'OFFLINE' as const,
    NotReady: 'NOT_READY' as const,
    Available: 'AVAILABLE' as const,
    Reserved: 'RESERVED' as const,
    Busy: 'BUSY' as const,
} as const;

export const WorkerStatusStateEnumValues = ['OFFLINE', 'NOT_READY', 'AVAILABLE', 'RESERVED', 'BUSY'] as const;
