export * from './activate/activate.component';
export * from './activate/activate.service';
export * from './activate/activate.route';
export * from './register/register.component';
export * from './register/register.service';
export * from './register/register.route';
export * from './settings/settings.component';
export * from './settings/settings.route';
export * from './account.route';
