import { Injectable } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import * as Remarkable from 'remarkable';

import { CodeEditorService } from '../../code-editor/code-editor.service';
import { Feedback } from '../feedback';
import { Result } from '../result';

type Step = {
    title: string;
    done: boolean;
};

@Injectable({ providedIn: 'root' })
export class ProgrammingExerciseMarkdownService {
    private markdown: Remarkable;
    private latestResult: Result;
    private resultDetails: Feedback[];
    public steps: Array<Step> = [];

    constructor(private editorService: CodeEditorService, private translateService: TranslateService) {
        this.markdown = new Remarkable();
        this.markdown.inline.ruler.before('text', 'testsStatus', this.remarkableTestsStatusParser.bind(this), {});
        this.markdown.block.ruler.before('paragraph', 'plantUml', this.remarkablePlantUmlParser.bind(this), {});
        this.markdown.renderer.rules['testsStatus'] = this.remarkableTestsStatusRenderer.bind(this);
        this.markdown.renderer.rules['plantUml'] = this.remarkablePlantUmlRenderer.bind(this);
    }

    public renderInstructions(markdown: string, latestResult: Result, resultDetails: Feedback[]) {
        this.steps = [];
        this.latestResult = latestResult;
        this.resultDetails = resultDetails;
        return this.markdown.render(markdown);
    }

    /**
     * @function remarkableTestsStatusParser
     * @desc Parser rule for Remarkable custom token TestStatus
     * @param state
     * @param silent
     */
    private remarkableTestsStatusParser(state: any, silent: boolean) {
        const regex = /^✅\[([^\]]*)\]\s*\(([^)]+)\)/;

        // It is surely not our rule, so we can stop early
        if (state.src[state.pos] !== '✅') {
            return false;
        }

        const match = regex.exec(state.src.slice(state.pos));
        if (!match) {
            return false;
        }

        // In silent mode it shouldn't output any tokens or modify pending
        if (!silent) {
            // Insert the testsStatus token to our rendered tokens
            state.push({
                type: 'testsStatus',
                title: match[1],
                tests: match[2].split(','),
                level: state.level,
            });
        }

        // Every rule should set state.pos to a position after token's contents
        state.pos += match[0].length;

        return true;
    }

    /**
     * @function remarkablePlantUmlParser
     * @desc Parser rule for Remarkable custom token PlantUml
     * @param state
     * @param startLine
     * @param endLine
     * @param silent
     */
    private remarkablePlantUmlParser = function(state: any, startLine: number, endLine: number, silent: boolean) {
        /**
         * Excerpt from the remarkable documentation regarding the stateBlock (param state):
         * src: the complete string the parser is currently working on
         * parser: The current block parser (here to make nested calls easier)
         * env: a namespaced data key-value store to allow core rules to exchange data
         * tokens: the tokens generated by the parser up to now, you will emit new tokens by calling push(newToken) on this
         * bMarks: a collection marking for each line the position of its start in src
         * eMarks: a collection marking for each line the position of its end in src
         * tShift: a collection marking for each line, how much spaces were used to indent it
         * level: the nested level for the current block
         */

        const shift = state.tShift[startLine];
        const max = state.eMarks[startLine];
        let pos = state.bMarks[startLine];
        pos += shift;

        if (shift > 3 || pos + 2 >= max) {
            return false;
        }
        if (state.src.charCodeAt(pos) !== 0x40 /* @ */) {
            return false;
        }

        const char = state.src.charCodeAt(pos + 1);

        // Is the current char a 's'?
        if (char === 0x73) {
            // Probably start or end of tag
            if (char === 0x73 /* \ */) {
                // opening tag
                const match = state.src.slice(pos, max).match(/^@startuml/);
                if (!match) {
                    return false;
                }
            }
            if (silent) {
                return true;
            }
        } else {
            return false;
        }

        // If we are here - we detected PlantUML block.
        // Let's roll down till empty line (block end).
        let nextLine = startLine + 1;
        while (nextLine < state.lineMax && !state.src.slice(state.bMarks[nextLine], state.bMarks[nextLine + 1]).match(/^@enduml/)) {
            nextLine++;
        }

        state.line = nextLine + 1;
        // Insert the plantUml token to our rendered tokens
        state.tokens.push({
            type: 'plantUml',
            level: state.level,
            lines: [startLine, state.line],
            content: state.getLines(startLine, state.line, 0, true),
        });

        return true;
    };

    /**
     * @function remarkableTestsStatusRenderer
     * @desc Renderer rule for Remarkable custom token TestStatus
     * Builds the raw html for test case status; also inserts the test details link
     * @param tokens
     * @param id
     * @param options
     * @param env
     */
    private remarkableTestsStatusRenderer(tokens: any[], id: number, options: any, env: any) {
        const tests = tokens[0].tests;
        const [done, label] = this.statusForTests(tests);

        let text = '<span class="bold">';

        text += done
            ? `<fa-icon size="lg" [icon]="['far', 'check-circle']" class="text-success" style="font-size: 1.7em;"></fa-icon>`
            : `<fa-icon size="lg" [icon]="['far', 'times-circle']" class="text-danger" style="font-size: 1.7em;"></fa-icon>`;
        text += ' ' + tokens[0].title;
        text += '</span>: ';
        // If the test is not done, we set the 'data-tests' attribute to the a-element, which we later use for the details dialog
        if (done) {
            text += '<span class="text-success bold">' + label + '</span>';
        } else {
            // bugfix: do not let the user click on 'No Results'
            if (label === this.translateService.instant('arTeMiSApp.editor.testStatusLabels.noResult')) {
                text += '<span class="text-danger bold">' + label + '</span>'; // this should be bold
            } else {
                text += '<a data-tests="' + tests.toString() + '" class="test-status"><span class="text-danger result">' + label + '</span></a>';
            }
        }
        text += '<br>';

        this.steps.push({
            title: tokens[0].title,
            done,
        });

        return text;
    }

    /**
     * @function remarkablePlantUmlRenderer
     * @desc Renderer rule for Remarkable custom token PlantUml
     * @param tokens the tokens generated by the parser up to now
     * @param id
     */
    private remarkablePlantUmlRenderer(tokens: any[], id: number) {
        let plantUml = tokens[id].content;

        // tslint:disable-next-line:max-line-length
        plantUml = plantUml.replace(
            '@startuml',
            '@startuml\nskinparam shadowing false\nskinparam classBorderColor black\nskinparam classArrowColor black\nskinparam DefaultFontSize 14\nskinparam ClassFontStyle bold\nskinparam classAttributeIconSize 0\nhide empty members\n',
        );

        plantUml = plantUml.replace(/testsColor\(([^)]+)\)/g, (match: any, capture: string) => {
            const tests = capture.split(',');
            const [done] = this.statusForTests(tests);
            return done ? 'green' : 'red';
        });

        /**
         * Explanation: This call fetches the plantUml png as base64 string; the function returns and inserts an empty img tag with a placeholder
         * When the promise is fulfilled, the src-attribute of the img element is being set with the returned value
         */
        this.editorService.getPlantUmlImage(plantUml).subscribe(
            plantUmlSrcAttribute => {
                // Assign plantUmlSrcAttribute as src attribute to our img element if exists.
                if (document.getElementById('plantUml' + id)) {
                    document.getElementById('plantUml' + id).setAttribute('src', 'data:image/jpeg;base64,' + plantUmlSrcAttribute);
                }
            },
            err => {
                console.log('Error getting plantUmlImage', err);
            },
        );

        return "<img id='plantUml" + id + "' alt='plantUml'" + id + " '/>";
    }

    /**
     * @function statusForTests
     * @desc Callback function for renderers to set the appropiate test status
     * @param tests
     */
    private statusForTests(tests: string[]): [boolean, string] {
        const translationBasePath = 'arTeMiSApp.editor.testStatusLabels.';
        let done = false;
        let label = this.translateService.instant('arTeMiSApp.editor.testStatusLabels.noResult');
        const totalTests = tests.length;

        if (this.resultDetails && this.resultDetails.length > 0) {
            let failedTests = 0;
            for (const test of tests) {
                for (const result of this.resultDetails) {
                    if (result.text === test) {
                        failedTests++;
                    }
                }
            }

            // Exercise is done if it was completed successfully or no tests have failed
            done = (this.latestResult && this.latestResult.successful) || failedTests === 0;
            if (totalTests === 1) {
                if (done) {
                    label = this.translateService.instant(translationBasePath + 'testPassing');
                } else {
                    label = this.translateService.instant(translationBasePath + 'testFailing');
                }
            } else {
                if (done) {
                    label = this.translateService.instant(translationBasePath + 'totalTestsPassing', { totalTests });
                } else {
                    label = this.translateService.instant(translationBasePath + 'totalTestsFailing', { totalTests, failedTests });
                }
            }
        } else if (this.latestResult && this.latestResult.successful) {
            done = true;
            label = this.translateService.instant(translationBasePath + 'testPassing');
        }

        return [done, label];
    }
}
