export class IrisPipeEventDTO {
    event: IrisPipeEvent;
}

export enum IrisPipeEvent {
    BUILD_WITH_POINTS = 'BUILD_WITH_POINTS',
    USER_INITIATES_PROMPTING = 'USER_INITIATES_PROMPTING',
    FIRST_QUESTION = 'FIRST_QUESTION',
    NEXT_QUESTION = 'NEXT_QUESTION',
    PROMPTING_FINISHED = 'PROMPTING_FINISHED',
}
