export enum IrisPipeEvent {
    BUILD_WITH_POINTS = 'BUILD_WITH_POINTS',
    USER_STARTS_QUIZ = 'USER_STARTS_QUIZ',
    FIRST_QUESTION = 'FIRST_QUESTION',
    NEXT_QUESTION = 'NEXT_QUESTION',
    QUIZ_FINISHED = 'QUIZ_FINISHED',
}
