import { TutorialGroupFreePeriod } from 'app/tutorialgroup/shared/entities/tutorial-group-free-day.model';
import { convertDateFromClient } from 'app/shared/util/date.utils';
import dayjs from 'dayjs/esm';
import { TutorialGroupsConfiguration } from 'app/tutorialgroup/shared/entities/tutorial-groups-configuration.model';

/**
 * Data Transfer Object representing a tutorial group free period.
 *
 * All date fields are serialized as ISO 8601 strings.
 */
export interface TutorialGroupFreePeriodDTO {
    id?: number;
    start: string;
    end: string;
    reason?: string;
    tutorialGroupConfigurationId?: number;
}

/**
 * Data Transfer Object used when creating or updating a tutorial group free period.
 * This DTO excludes the `id` field, as it is generated by the server.
 *
 * All date fields are serialized as ISO 8601 strings.
 */
export interface TutorialGroupFreePeriodRequestDTO {
    startDate: string;
    endDate: string;
    reason?: string;
}

/**
 * Converts a {@link TutorialGroupFreePeriod} entity into a
 * {@link TutorialGroupFreePeriodDTO}.
 *
 * If the provided entity is undefined, the function returns undefined.
 * This allows safe usage in optional mapping chains.
 *
 * @param entity the free period entity to convert
 * @returns the corresponding DTO or undefined if the entity is undefined
 */
export const entityToTutorialGroupFreePeriodDTO = (entity?: TutorialGroupFreePeriod): TutorialGroupFreePeriodDTO | undefined => {
    if (!entity) {
        return undefined;
    }
    return {
        id: entity.id,
        start: convertDateFromClient(entity.start)!,
        end: convertDateFromClient(entity.end)!,
        reason: entity.reason,
        tutorialGroupConfigurationId: entity.tutorialGroupConfiguration?.id,
    };
};

/**
 * Converts a {@link TutorialGroupFreePeriodDTO} into a {@link TutorialGroupFreePeriod} entity.
 * The provided tutorial group configuration is assigned to the resulting entity to maintain the relationship.
 *
 * @param dto the DTO containing the free period data
 * @param configuration the tutorial group configuration to which this free period belongs
 * @return a new {@link TutorialGroupFreePeriod} entity populated with the DTO data
 */
export function fromTutorialGroupFreePeriodDTO(dto: TutorialGroupFreePeriodDTO, configuration: TutorialGroupsConfiguration): TutorialGroupFreePeriod {
    return {
        id: dto.id,
        start: dayjs.utc(dto.start),
        end: dayjs.utc(dto.end),
        reason: dto.reason,
        tutorialGroupConfiguration: configuration,
    };
}
