{
 "title": "Artemis Public Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "semester",
    "label": "Semester",
    "query": {
     "query": "artemis_statistics_public_course_students"
    }
   }
  ]
 },
 "panels": [
  { "title": "General statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current connected users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artemis_global_websocket_users)"
    }
   ]
  },
  {
   "title": "Active Users (7 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artemis_statistics_public_active_users{period=\"7\"}"
    }
   ]
  },
  {
   "title": "Active Users (30 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artemis_statistics_public_active_users{period=\"30\"}"
    }
   ]
  },
  {
   "title": "Active Courses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artemis_statistics_public_active_courses"
    }
   ]
  },
  {
   "title": "Active Exercises",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artemis_statistics_public_active_courses"
    }
   ]
  },
  { "title": "Exercise Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Exercises",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "artemis_statistics_public_active_exercises",
     "legendFormat": "{{exerciseType}}"
    }
   ]
  },
  {
   "title": "Exercises",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "artemis_statistics_public_exercises",
     "legendFormat": "{{exerciseType}}"
    }
   ]
  },
  { "title": "Course Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Courses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "artemis_statistics_public_course_students"
    }
   ]
  },
  {
   "title": "Courses in Semester \"$semester\"",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "artemis_statistics_public_course_students{semester=\"$semester\"}"
    }
   ]
  },
  { "title": "Exam Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Exams in Active Courses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "artemis_statistics_public_exam_students"
    }
   ]
  }
 ]
}