import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    // The key here is the sidebarId. It can be anything you want.
    guidelinesSidebar: [
        {
            type: 'autogenerated',
            dirName: '.', // '.' means the root of the 'guidelines' folder
        },
    ],
};

export default sidebars;
