package de.tum.cit.aet.artemis.iris.domain.settings;

public enum IrisSubSettingsType {
    CHAT, // TODO: Rename to PROGRAMMING_EXERCISE_CHAT
    TEXT_EXERCISE_CHAT, COURSE_CHAT, COMPETENCY_GENERATION, LECTURE_INGESTION, LECTURE_CHAT, FAQ_INGESTION, TUTOR_SUGGESTION
}
