package de.tum.cit.aet.artemis.programming.domain;

/**
 * Used to define the type of a ProgrammingExerciseTestCase.
 * Currently, only used for tests in Java exercises. Test cases in other languages are always of type DEFAULT
 */
public enum ProgrammingExerciseTestCaseType {
    /**
     * Test case has been generated by the structure oracle
     */
    STRUCTURAL,
    /**
     * Test case has been created by an instructor
     */
    BEHAVIORAL,
    /**
     * All other types
     */
    DEFAULT,
}
