apply from: rootProject.file('gradle/isolated-module.gradle')

dependencies {
    api project(':aiworker:api')
    api 'org.springframework.ai:spring-ai-openai'
    api 'org.apache.commons:commons-compress:1.28.0'
    implementation 'org.slf4j:slf4j-api'
}

dependencies {
    testImplementation 'com.tngtech.archunit:archunit:1.5.0'
}
