import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
page.on('pageerror', e => console.log('[pageerror]', String(e).slice(0,400)));
page.on('console', m => { if (m.type()==='error' && !m.text().includes('ServiceWorker') && !m.text().includes('ngsw')) console.log('[err]', m.text().slice(0,300)); });
await page.goto('http://localhost:9000/sign-in', { waitUntil: 'domcontentloaded' });
await page.locator('#username').waitFor({ state: 'visible', timeout: 30000 });
await page.locator('#username').fill('artemis_admin'); await page.locator('#username').blur();
await page.click('#continue-button');
await page.locator('#password').waitFor({ state: 'visible' }); await page.locator('#password').fill('artemis_admin'); await page.locator('#password').blur();
await page.click('#login-button'); await page.waitForTimeout(4000);
await page.goto('http://localhost:9000/course-management/9020/quiz-exercises/new', { waitUntil: 'domcontentloaded' });
const btn = page.getByRole('button', { name: /Add Apollon Drag-And-Drop Question/i }).first();
await btn.waitFor({ state: 'visible', timeout: 90000 }); await page.waitForTimeout(1200); await btn.click();
await page.locator('#open-diagram').first().waitFor({state:'visible',timeout:60000});
await page.locator('#open-diagram').first().click();
await page.locator('.apollon-editor').waitFor({ state: 'visible', timeout: 60000 });
await page.waitForTimeout(2500);
console.log(JSON.stringify(await page.evaluate(() => {
  const el = document.querySelector('[data-testid="apollon-diagram-title"]');
  const canvas = document.querySelector('.apollon-diagram-detail__canvas');
  const ccs = getComputedStyle(canvas);
  const dump = { canvasRadius: ccs.borderRadius, chromeMd: ccs.getPropertyValue('--apollon-chrome-radius-md'), chromeLg: ccs.getPropertyValue('--apollon-chrome-radius-lg'), rootMd: getComputedStyle(document.documentElement).getPropertyValue('--apollon-chrome-radius-md'), canvasClass: canvas.className };
  console.log('CANVAS', JSON.stringify(dump));
  const s = getComputedStyle(el);
  return { cls: el.className, borderTop: s.borderTopWidth+' '+s.borderTopColor, borderLeft: s.borderLeftWidth+' '+s.borderLeftColor, borderRight: s.borderRightWidth+' '+s.borderRightColor, dialogRadius: getComputedStyle(document.querySelector('.p-dialog')).borderRadius };
}), null, 2));
await browser.close();
