package de.tum.cit.aet.artemis.core.domain;

public enum LLMServiceType {
    ATHENA, IRIS_CODE_FEEDBACK, IRIS_CHAT_COURSE_MESSAGE, IRIS_CHAT_EXERCISE_MESSAGE, IRIS_INTERACTION_SUGGESTION, IRIS_CHAT_LECTURE_MESSAGE, IRIS_COMPETENCY_GENERATION,
    IRIS_CITATION_PIPELINE, NOT_SET
}
