package de.tum.cit.aet.artemis.core.domain;

public enum LLMServiceType {
    ATHENA_PRELIMINARY_FEEDBACK, ATHENA_FEEDBACK_SUGGESTION, IRIS_CODE_FEEDBACK, IRIS_CHAT_COURSE_MESSAGE, IRIS_CHAT_EXERCISE_MESSAGE, IRIS_INTERACTION_SUGGESTION,
    IRIS_CHAT_LECTURE_MESSAGE, IRIS_COMPETENCY_GENERATION, IRIS_CITATION_PIPELINE, IRIS_LECTURE_RETRIEVAL_PIPELINE, IRIS_LECTURE_INGESTION, NOT_SET
}
