// ARTEMIS: JenkinsPipeline

pipeline {
        options {
            timeout(time: #jenkinsTimeout, unit: 'MINUTES')
        }
        agent {
            docker {
                image '#dockerImage'
                label 'docker'
            }
        }
        stages {
            stage('Checkout') {
                steps {
                    checkout([$class: 'GitSCM', branches: [[name: '#defaultBranch']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '#gitCredentials', name: 'tests', url: '#testRepository']]])
                    dir('#assignmentCheckoutPath') {
                        checkout([$class: 'GitSCM', branches: [[name: '#defaultBranch']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '#gitCredentials', name: 'assignment', url: '#assignmentRepository']]])
                    }
                }
            }
            stage('Build') {
                steps {
                    timestamps {
                        sh  '''
                            python3 -m compileall . -q || error=true
                            if [ ! $error ]
                            then
                                pytest --junitxml=test-reports/results.xml
                            else
                                exit 1
                            fi
                            '''
                    }
                }
            }
        }
        post {
            cleanup {
                sh  '''
                    rm -rf results
                    mkdir results
                    if [ -e test-reports/results.xml ]
                    then
                        sed -i 's/<testsuites>//g ; s/<\/testsuites>//g' test-reports/results.xml
                    fi
                    cp test-reports/*.xml $WORKSPACE/results/ || true
                    '''
                sendTestResults credentialsId: '#jenkinsNotificationToken', notificationUrl: '#notificationsUrl'
                cleanWs()
            }
        }
}
