/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface AnswerOptionWithSolution {
    id?: number;
    text?: string;
    hint?: string;
    invalid?: boolean;
    explanation?: string;
    isCorrect?: boolean;
}
