/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Bloom\'s taxonomy radar distribution with normalized proportions (0.0–1.0, summing to 1.0)
 */
export interface BloomRadar {
    /** Proportion of REMEMBER level (0.0–1.0) */
    REMEMBER?: number;
    /** Proportion of UNDERSTAND level (0.0–1.0) */
    UNDERSTAND?: number;
    /** Proportion of APPLY level (0.0–1.0) */
    APPLY?: number;
    /** Proportion of ANALYZE level (0.0–1.0) */
    ANALYZE?: number;
    /** Proportion of EVALUATE level (0.0–1.0) */
    EVALUATE?: number;
    /** Proportion of CREATE level (0.0–1.0) */
    CREATE?: number;
}
