/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 8.5.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Request DTO for code generation
 */
export interface CodeGenerationRequestDTO {
    /** Type of repository to generate code for */
    readonly repositoryType?: CodeGenerationRequestDTORepositoryTypeEnum;
}

export type CodeGenerationRequestDTORepositoryTypeEnum = 'TEMPLATE' | 'SOLUTION' | 'TESTS';

export const CodeGenerationRequestDTORepositoryTypeEnumValues = ['TEMPLATE', 'SOLUTION', 'TESTS'] as const;

