import type { ConsistencyIssue } from "./consistency-issue";

/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 8.5.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Response containing consistency check results
 */
export interface ConsistencyCheckResponse {
    /** List of consistency issues found */
    readonly issues: Array<ConsistencyIssue>;
}
