/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Response containing consistency check costs
 */
export interface Costs {
    /** Prompt costs in EUR */
    promptEur?: number;
    /** Completion costs in EUR */
    completionEur?: number;
    /** Total costs in EUR */
    totalEur?: number;
}
