/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface DifficultyAssessment {
    suggested?: DifficultyAssessmentSuggestedEnum;
    confidence?: number;
    reasoning?: string;
    matchesDeclared?: boolean;
    delta?: DifficultyAssessmentDeltaEnum;
    taskCount?: number;
    testCount?: number;
}

export type DifficultyAssessmentSuggestedEnum = 'EASY' | 'MEDIUM' | 'HARD' | 'UNKNOWN';

export const DifficultyAssessmentSuggestedEnumValues = ['EASY', 'MEDIUM', 'HARD', 'UNKNOWN'] as const;

export type DifficultyAssessmentDeltaEnum = 'LOWER' | 'MATCH' | 'HIGHER' | 'UNKNOWN';

export const DifficultyAssessmentDeltaEnumValues = ['LOWER', 'MATCH', 'HIGHER', 'UNKNOWN'] as const;

