/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface ExamSeat {
    name: string;
    condition: ExamSeatConditionEnum;
    x?: number;
    y?: number;
}

export type ExamSeatConditionEnum = 'USABLE' | 'NO_TABLE' | 'DEFECT' | 'WHEELCHAIR';

export const ExamSeatConditionEnumValues = ['USABLE', 'NO_TABLE', 'DEFECT', 'WHEELCHAIR'] as const;

