/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface LeaderboardEntry {
    rank?: number;
    selectedLeague?: number;
    userId?: number;
    userName: string;
    imageURL?: string;
    score?: number;
    answeredCorrectly?: number;
    answeredWrong?: number;
    totalQuestions?: number;
    dueDate: string;
    streak?: number;
}
