/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Request to refine a problem statement using targeted selection-based instructions
 */
export interface ProblemStatementTargetedRefinementRequest {
    /** Original problem statement text to be refined (max 50,000 chars) */
    problemStatementText: string;
    /** Start line number (1-indexed) */
    startLine: number;
    /** End line number (1-indexed, inclusive) */
    endLine: number;
    /** Start column within start line (1-indexed, optional for character-level targeting) */
    startColumn?: number;
    /** End column within end line (1-indexed, exclusive — points after the last selected character, optional for character-level targeting) */
    endColumn?: number;
    /** Instruction describing what should change */
    instruction: string;
}
