/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QualityIssueLocation } from './quality-issue-location';

/**
 * A quality issue found in the problem statement
 */
export interface QualityIssue {
    /** Issue category: CLARITY, COHERENCE, or COMPLETENESS */
    category?: QualityIssueCategoryEnum;
    /** Issue severity: LOW, MEDIUM, or HIGH */
    severity?: QualityIssueSeverityEnum;
    /** Description of what is wrong */
    description?: string;
    /** Location in the problem statement */
    location?: QualityIssueLocation;
    /** Concrete suggestion to fix the issue */
    suggestedFix?: string;
    /** How this issue increases extraneous cognitive load */
    impactOnLearners?: string;
}

export type QualityIssueCategoryEnum = 'CLARITY' | 'COHERENCE' | 'COMPLETENESS';

export const QualityIssueCategoryEnumValues = ['CLARITY', 'COHERENCE', 'COMPLETENESS'] as const;

export type QualityIssueSeverityEnum = 'LOW' | 'MEDIUM' | 'HIGH';

export const QualityIssueSeverityEnumValues = ['LOW', 'MEDIUM', 'HIGH'] as const;

