/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizQuestionRefinementResponse } from './quiz-question-refinement-response';

/**
 * Response containing one refinement result per input question, in the same order
 */
export interface QuizQuestionBulkRefinementResponse {
    /** Refinement results, one per input question in the same order */
    refinements: Array<QuizQuestionRefinementResponse>;
}
