/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { QuizQuestionWithSolution } from './quiz-question-with-solution';

export interface QuizQuestionTraining {
    quizQuestionWithSolutionDTO: QuizQuestionWithSolution;
    isRated?: boolean;
    questionIds?: Array<number>;
    isNewSession?: boolean;
    id?: number;
}
