/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


/**
 * Failed refinement result containing an error message
 */
export interface QuizQuestionRefinementFailure {
    /** Error message describing why the refinement failed */
    error: string;
    type?: QuizQuestionRefinementFailureTypeEnum;
}

export type QuizQuestionRefinementFailureTypeEnum = 'failure';

export const QuizQuestionRefinementFailureTypeEnumValues = ['failure'] as const;

