/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ShortAnswerMapping } from './short-answer-mapping';
import type { ShortAnswerSpot } from './short-answer-spot';
import type { ShortAnswerSolution } from './short-answer-solution';

export interface ShortAnswerQuizQuestionWithSolution {
    id?: number;
    title?: string;
    text?: string;
    hint?: string;
    points?: number;
    scoringType?: ShortAnswerQuizQuestionWithSolutionScoringTypeEnum;
    randomizeOrder?: boolean;
    invalid?: boolean;
    type?: string;
    explanation?: string;
    spots?: Array<ShortAnswerSpot>;
    solutions?: Array<ShortAnswerSolution>;
    similarityValue?: number;
    matchLetterCase?: boolean;
    correctMappings?: Array<ShortAnswerMapping>;
}

export type ShortAnswerQuizQuestionWithSolutionScoringTypeEnum = 'ALL_OR_NOTHING' | 'PROPORTIONAL_WITH_PENALTY' | 'PROPORTIONAL_WITHOUT_PENALTY';

export const ShortAnswerQuizQuestionWithSolutionScoringTypeEnumValues = ['ALL_OR_NOTHING', 'PROPORTIONAL_WITH_PENALTY', 'PROPORTIONAL_WITHOUT_PENALTY'] as const;

