/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

import type { ShortAnswerSpot } from './short-answer-spot';
import type { ShortAnswerSolution } from './short-answer-solution';

export interface ShortAnswerMapping {
    id?: number;
    shortAnswerSpotIndex?: number;
    shortAnswerSolutionIndex?: number;
    invalid?: boolean;
    solution?: ShortAnswerSolution;
    spot?: ShortAnswerSpot;
}
