import type { TutorialGroupDetailSession } from "./tutorial-group-detail-session";

/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 8.5.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */


export interface TutorialGroupDetailGroup {
    readonly id?: number;
    readonly title: string;
    readonly language: string;
    readonly isOnline?: boolean;
    readonly teachingAssistantName: string;
    readonly teachingAssistantLogin: string;
    readonly teachingAssistantImageUrl?: string;
    readonly capacity?: number;
    readonly campus?: string;
    readonly groupChannelId?: number;
    readonly tutorChatId?: number;
    readonly sessions: Array<TutorialGroupDetailSession>;
}
