import { ContentType, GuidedTour, Orientation } from 'app/guided-tour/guided-tour.constants';

export const courseOverviewTour: GuidedTour = {
    settingsId: 'showCourseOverviewTour',
    useOrb: false,
    minimumScreenSize: 600,
    steps: [
        {
            headline: 'Welcome to Artemis',
            headlineTranslateKey: 'tour.course-overview.1.headline',
            subHeadline: 'Subheadline',
            subHeadlineTranslateKey: 'tour.course-overview.1.subHeadline',
            contentType: ContentType.IMAGE,
            content: 'Artemis is a learning platform where you can solve programming exercises in interactive learning sessions.',
            contentTranslateKey: 'tour.course-overview.1.content',
            imageUrl: './../../../../content/images/logo_tum_256.png',
        },
        {
            headline: 'Course overview',
            headlineTranslateKey: 'tour.course-overview.2.headline',
            contentType: ContentType.TEXT,
            content: 'On this page you can see an overview of all courses which you are signed up for.',
            contentTranslateKey: 'tour.course-overview.2.content',
            selector: '#overview-menu',
            orientation: Orientation.BottomLeft,
        },
        {
            headline: 'Your current courses',
            headlineTranslateKey: 'tour.course-overview.3.headline',
            contentType: ContentType.TEXT,
            content: 'This is a course you are signed up to. Please check out the course details afterwards by clicking on the panel.',
            contentTranslateKey: 'tour.course-overview.3.content',
            selector: '.card-header',
            orientation: Orientation.Right,
        },
        {
            headline: 'Next due exercise',
            headlineTranslateKey: 'tour.course-overview.4.headline',
            contentType: ContentType.TEXT,
            content: 'See what exercise has to be completed in the next few days.',
            contentTranslateKey: 'tour.course-overview.4.content',
            selector: '.card-footer',
            orientation: Orientation.Right,
        },
        {
            headline: 'Sign up for other courses',
            headlineTranslateKey: 'tour.course-overview.5.headline',
            contentType: ContentType.TEXT,
            content: 'You can click here and see whether you can sign up for other courses additionally.',
            contentTranslateKey: 'tour.course-overview.5.content',
            selector: 'jhi-course-registration-selector button',
            orientation: Orientation.Left,
            useHighlightPadding: true,
            highlightPadding: 10,
        },
        {
            headline: 'Your notifications',
            headlineTranslateKey: 'tour.course-overview.6.headline',
            contentType: ContentType.TEXT,
            content: 'Get notified about new exercises from this notification dropdown.',
            contentTranslateKey: 'tour.course-overview.6.content',
            selector: '#notificationsNavBarDropdown',
            orientation: Orientation.Left,
            useHighlightPadding: true,
            highlightPadding: 10,
        },
        {
            headline: 'Personal settings',
            headlineTranslateKey: 'tour.course-overview.7.headline',
            contentType: ContentType.TEXT,
            content: 'In your account menu you can change your display language and restart the guided tour at any other time.',
            contentTranslateKey: 'tour.course-overview.7.content',
            selector: '#account-menu',
            orientation: Orientation.Left,
            useHighlightPadding: true,
            highlightPadding: 10,
        },
        {
            headline: 'Contact the Artemis team',
            headlineTranslateKey: 'tour.course-overview.8.headline',
            contentType: ContentType.TEXT,
            content: 'Feel free to contact us to leave us some feedback, request features or to report bugs in the application.',
            contentTranslateKey: 'tour.course-overview.8.content',
            selector: '.footer .col-sm-6',
            orientation: Orientation.TopLeft,
        },
        {
            headline: 'Contact the Artemis team',
            headlineTranslateKey: 'tour.course-overview.8.headline',
            contentType: ContentType.VIDEO,
            content: 'Feel free to contact us to leave us some feedback, request features or to report bugs in the application.',
            contentTranslateKey: 'tour.course-overview.8.content',
            videoUrl: 'https://www.youtube.com/embed/EOyxE9L-4X4',
        },
    ],
};
