import { GuidedTour } from 'app/guided-tour/guided-tour.model';
import { AssessmentTaskTourStep, TextTourStep, UserInterActionTourStep } from 'app/guided-tour/guided-tour-step.model';
import { Orientation, ResetParticipation, UserInteractionEvent } from 'app/guided-tour/guided-tour.constants';
import { AssessmentObject, GuidedTourAssessmentTask } from 'app/guided-tour/guided-tour-task.model';
import { Authority } from 'app/shared/constants/authority.constants';

export const tutorAssessmentTour: GuidedTour = {
    settingsKey: 'tutor_assessment_tour',
    resetParticipation: ResetParticipation.TUTOR_ASSESSMENT,
    steps: [
        new UserInterActionTourStep({
            highlightSelector: '.tutor-dashboard.guided-tour',
            headlineTranslateKey: 'tour.courseAdministration.assessmentDashboardButton.headline',
            contentTranslateKey: 'tour.courseAdministration.assessmentDashboardButton.content',
            highlightPadding: 10,
            orientation: Orientation.LEFT,
            permission: [Authority.TA],
            pageUrl: '/course-management',
            userInteractionEvent: UserInteractionEvent.CLICK,
        }),
        // new page
        new TextTourStep({
            highlightSelector: '.guided-tour-assessment-stats',
            headlineTranslateKey: 'tour.assessmentDashboard.overview.headline',
            contentTranslateKey: 'tour.assessmentDashboard.overview.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
            pageUrl: '/course-management/(\\d+)+/assessment-dashboard',
        }),
        new TextTourStep({
            highlightSelector: '.guided-tour-form-check',
            headlineTranslateKey: 'tour.assessmentDashboard.showFinished.headline',
            contentTranslateKey: 'tour.assessmentDashboard.showFinished.content',
            highlightPadding: 10,
            orientation: Orientation.TOPLEFT,
            permission: [Authority.TA],
        }),
        new TextTourStep({
            highlightSelector: '.guided-tour-exercise-table',
            headlineTranslateKey: 'tour.assessmentDashboard.exerciseTable.headline',
            contentTranslateKey: 'tour.assessmentDashboard.exerciseTable.content',
            highlightPadding: 25,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
        }),
        new TextTourStep({
            highlightSelector: 'jhi-tutor-participation-graph.guided-tour',
            headlineTranslateKey: 'tour.assessmentDashboard.gradingProcess.headline',
            contentTranslateKey: 'tour.assessmentDashboard.gradingProcess.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
        }),
        new UserInterActionTourStep({
            highlightSelector: '.btn.guided-tour',
            headlineTranslateKey: 'tour.assessmentDashboard.exerciseDashboardButton.headline',
            contentTranslateKey: 'tour.assessmentDashboard.exerciseDashboardButton.content',
            highlightPadding: 10,
            orientation: Orientation.TOPRIGHT,
            permission: [Authority.TA],
            userInteractionEvent: UserInteractionEvent.CLICK,
        }),
        // new page
        new TextTourStep({
            highlightSelector: '.guided-tour-markdown-preview',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.instructions.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.instructions.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
            pageUrl: '/course-management/(\\d+)+/exercises/(\\d+)+/assessment-dashboard',
        }),
        new UserInterActionTourStep({
            highlightSelector: '.guided-tour-instructions-button',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.instructionsButton.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.instructionsButton.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
            userInteractionEvent: UserInteractionEvent.CLICK,
            triggerNextStep: true,
        }),
        new UserInterActionTourStep({
            highlightSelector: '.review-example-submission.guided-tour',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.reviewExampleSubmission.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.reviewExampleSubmission.content',
            highlightPadding: 10,
            orientation: Orientation.TOPLEFT,
            userInteractionEvent: UserInteractionEvent.CLICK,
            permission: [Authority.TA],
        }),
        // new page
        new TextTourStep({
            highlightSelector: '.guided-tour-assessment-editor',
            headlineTranslateKey: 'tour.exampleReview.reviewSubmission.headline',
            contentTranslateKey: 'tour.exampleReview.reviewSubmission.content',
            orientation: Orientation.TOP,
            permission: [Authority.TA],
            pageUrl: 'course-management/(\\d+)+/text-exercises/(\\d+)+/example-submissions/(\\d+)+?readOnly=true',
        }),
        new TextTourStep({
            highlightSelector: '.guided-tour-text-assessment',
            headlineTranslateKey: 'tour.exampleReview.reviewAssessment.headline',
            contentTranslateKey: 'tour.exampleReview.reviewAssessment.content',
            orientation: Orientation.TOP,
            permission: [Authority.TA],
        }),
        new UserInterActionTourStep({
            highlightSelector: 'jhi-example-text-submission .guided-tour-read',
            headlineTranslateKey: 'tour.exampleReview.confirm.headline',
            contentTranslateKey: 'tour.exampleReview.confirm.content',
            userInteractionEvent: UserInteractionEvent.CLICK,
            orientation: Orientation.TOPRIGHT,
            highlightPadding: 10,
            permission: [Authority.TA],
        }),
        // new page
        new UserInterActionTourStep({
            highlightSelector: '.assess-example-submission.guided-tour',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.assessExampleSubmission.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.assessExampleSubmission.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            userInteractionEvent: UserInteractionEvent.CLICK,
            permission: [Authority.TA],
            pageUrl: '/course-management/(\\d+)+/exercises/(\\d+)+/assessment-dashboard',
        }),
        // new page
        new AssessmentTaskTourStep({
            highlightSelector: '.guided-tour-assessment-editor',
            headlineTranslateKey: 'tour.exampleAssessment.addAssessment.headline',
            contentTranslateKey: 'tour.exampleAssessment.addAssessment.content',
            orientation: Orientation.TOP,
            highlightPadding: 10,
            permission: [Authority.TA],
            userInteractionEvent: UserInteractionEvent.ASSESS_SUBMISSION,
            assessmentTask: new GuidedTourAssessmentTask('tour.exampleAssessment.addAssessment.task', new AssessmentObject(3, 0)),
            pageUrl: 'course-management/(\\d+)+/text-exercises/(\\d+)+/example-submissions/(\\d+)+?toComplete=true',
        }),
        new AssessmentTaskTourStep({
            highlightSelector: '.guided-tour-text-assessment .row',
            headlineTranslateKey: 'tour.exampleAssessment.addScore.headline',
            contentTranslateKey: 'tour.exampleAssessment.addScore.content',
            userInteractionEvent: UserInteractionEvent.ASSESS_SUBMISSION,
            orientation: Orientation.TOP,
            highlightPadding: 10,
            permission: [Authority.TA],
            assessmentTask: new GuidedTourAssessmentTask('tour.exampleAssessment.addScore.task', new AssessmentObject(3, 3)),
        }),
        new UserInterActionTourStep({
            highlightSelector: 'jhi-example-text-submission .guided-tour-check-assessment',
            headlineTranslateKey: 'tour.exampleAssessment.submit.headline',
            contentTranslateKey: 'tour.exampleAssessment.submit.content',
            orientation: Orientation.TOPRIGHT,
            highlightPadding: 10,
            userInteractionEvent: UserInteractionEvent.CLICK,
            permission: [Authority.TA],
        }),
        new UserInterActionTourStep({
            highlightSelector: 'jhi-example-text-submission .guided-tour-back',
            headlineTranslateKey: 'tour.exampleAssessment.back.headline',
            contentTranslateKey: 'tour.exampleAssessment.back.content',
            orientation: Orientation.RIGHT,
            highlightPadding: 10,
            userInteractionEvent: UserInteractionEvent.CLICK,
            permission: [Authority.TA],
        }),
        // new page
        new TextTourStep({
            highlightSelector: '.guided-tour-exercise-dashboard-table',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.submissionsAndComplaints.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.submissionsAndComplaints.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
            pageUrl: '/course-management/(\\d+)+/exercises/(\\d+)+/assessment-dashboard',
        }),
        new TextTourStep({
            highlightSelector: '.guided-tour-exercise-table button.guided-tour',
            headlineTranslateKey: 'tour.exerciseAssessmentDashboard.assessSubmissions.headline',
            contentTranslateKey: 'tour.exerciseAssessmentDashboard.assessSubmissions.content',
            highlightPadding: 10,
            orientation: Orientation.TOP,
            permission: [Authority.TA],
        }),
    ],
};
