
// NOTE: this list has to be kept in sync with the extensions defined in FileResource.java
export const FILE_EXTENSIONS = [
    'png',
    'jpg',
    'jpeg',
    'svg',
    'pdf',
    'zip',
    'doc',
    'docx',
    'csv',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
    'pages',
    'rtf',
    'pages-tef',
    'numbers',
    'key',
    'odt',
    'ods',
    'odp',
    'odg',
    'odf',
];
