package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.ArgumentCaptor;

import de.tum.cit.aet.artemis.buildagent.dto.SandboxExecResult;
import de.tum.cit.aet.artemis.buildagent.service.InteractiveSandbox;
import de.tum.cit.aet.artemis.core.service.TempFileUtilService;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.GenerationWorkspaceService;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingExercise;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingLanguage;
import de.tum.cit.aet.artemis.programming.domain.RepositoryType;

/**
 * Deterministic test for the structural-oracle seeder (no Docker, no LLM): it runs the real
 * {@link de.tum.cit.aet.artemis.programming.service.structureoraclegenerator.OracleGenerator} over fixture sources and asserts that structural tests are seeded ONLY for a public
 * class the student must create (absent from the template), and never for incidental member differences within shared classes.
 */
class StructuralOracleSeedingServiceTest {

    private static final String GENERATED_MARKER = "// Generated by Artemis Hyperion structural oracle seeding. Safe to replace.";

    @TempDir
    private Path tempDir;

    private static ProgrammingExercise javaExercise() {
        ProgrammingExercise exercise = new ProgrammingExercise();
        exercise.setProgrammingLanguage(ProgrammingLanguage.JAVA);
        return exercise;
    }

    private StructuralOracleSeedingService seederWith(InteractiveSandbox sandbox, Map<String, String> solution, Map<String, String> template, Map<String, String> tests) {
        return seederWith(sandbox, solution, template, tests, new ApprovedSpecRegistry());
    }

    private StructuralOracleSeedingService seederWith(InteractiveSandbox sandbox, Map<String, String> solution, Map<String, String> template, Map<String, String> tests,
            ApprovedSpecRegistry approvedSpecs) {
        GenerationWorkspaceService workspace = mock(GenerationWorkspaceService.class);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.SOLUTION)).thenReturn(solution);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TEMPLATE)).thenReturn(template);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TESTS)).thenReturn(tests);
        return new StructuralOracleSeedingService(workspace, new TempFileUtilService(tempDir), approvedSpecs);
    }

    private static Map<String, String> readTar(InputStream in) throws Exception {
        Map<String, String> entries = new LinkedHashMap<>();
        try (TarArchiveInputStream tar = new TarArchiveInputStream(in)) {
            TarArchiveEntry entry;
            while ((entry = tar.getNextEntry()) != null) {
                if (!entry.isDirectory()) {
                    entries.put(entry.getName(), new String(tar.readAllBytes(), StandardCharsets.UTF_8));
                }
            }
        }
        return entries;
    }

    @Test
    void seedsStructuralTests_whenTemplateOmitsAWholePublicClass() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        // Solution has Sorter (in both) and MergeSort (a public class the student must create); the template omits MergeSort entirely.
        Map<String, String> solution = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort implements Sorter {\n    public int[] sort(int[] a){ return a; }\n}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }");
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting;\nclass SortTest {}");

        java.util.Set<String> seededNames = seederWith(sandbox, solution, template, tests).seedIfStructuralDiff(sandbox, "s", javaExercise());

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        Map<String, String> seeded = readTar(tarCaptor.getValue());
        assertThat(seeded).containsKeys("tests/test/sorting/ClassTest.java", "tests/test/sorting/MethodTest.java", "tests/test/sorting/test.json")
                .doesNotContainKeys("tests/test/sorting/AttributeTest.java", "tests/test/sorting/ConstructorTest.java");
        assertThat(seeded.get("tests/test/sorting/ClassTest.java")).startsWith(GENERATED_MARKER).contains("package sorting;").doesNotContain("${packageName}");
        // The oracle enforces the created class, not the already-present interface.
        assertThat(seeded.get("tests/test/sorting/test.json")).contains("MergeSort");
        // Only providers with something to check are seeded. Empty AttributeTest/ConstructorTest factories are reported by JUnit under their shared factory-method name,
        // generateTestsForAllClasses, which creates duplicate production test cases and fails an otherwise correct solution.
        assertThat(seededNames).containsExactlyInAnyOrder("testClass[MergeSort]", "testMethods[MergeSort]");
    }

    @Test
    void seedsStructuralTestsBeforeAnyAgentAuthoredJavaTestExists() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/navigation/Strategy.java", "package navigation; public interface Strategy { double apply(double x); }",
                "src/navigation/Warp.java", "package navigation; public class Warp implements Strategy { public double apply(double x) { return x; } }");
        Map<String, String> template = Map.of("src/navigation/Strategy.java", "package navigation; public interface Strategy { double apply(double x); }");
        Map<String, String> harnessOnly = Map.of("pom.xml", "<project/>");

        java.util.Set<String> seededNames = seederWith(sandbox, solution, template, harnessOnly).seedIfStructuralDiff(sandbox, "s", javaExercise());

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        assertThat(readTar(tarCaptor.getValue())).containsKeys("tests/test/navigation/ClassTest.java", "tests/test/navigation/MethodTest.java", "tests/test/navigation/test.json");
        assertThat(seededNames).containsExactlyInAnyOrder("testClass[Warp]", "testMethods[Warp]");
    }

    /** A minimal Ares-compliant Maven pom, matching what the harness-convention gate demands, so the composed test isolates the timeout/annotation check under test. */
    private static final String ARES_POM = """
            <project>
                <dependencies>
                    <dependency>
                        <groupId>de.tum.in.ase</groupId>
                        <artifactId>artemis-java-test-sandbox</artifactId>
                    </dependency>
                </dependencies>
                <build><plugins><plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <configuration><rules><requireFilesDontExist><files>
                        <file>${project.build.outputDirectory}/de/tum/in/test/api/</file>
                        <file>${project.build.outputDirectory}/org/junit/</file>
                    </files></requireFilesDontExist></rules></configuration>
                </plugin></plugins></build>
            </project>
            """;

    @Test
    void seededStructuralTestClasses_passTheJavaAresConventionIntegrityGate() throws Exception {
        // Composed test: production wires this seeder and ExerciseIntegrityGate together (GenerationOrchestrationService seeds structural tests, then the read-back tests
        // repository is checked by the Java/Ares convention gate), but they were previously only exercised in isolation. The seeded structural classes carry @StrictTimeout(10)
        // (see ClassTest.java etc.), not the exact @StrictTimeout(1) the gate used to demand — a whole-missing-class seed must not be rejected by the gate it is composed with.
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort implements Sorter {\n    public int[] sort(int[] a){ return a; }\n}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }");
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting;\nclass SortTest {}");

        seederWith(sandbox, solution, template, tests).seedIfStructuralDiff(sandbox, "s", javaExercise());

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        Map<String, String> seeded = readTar(tarCaptor.getValue());

        // Re-key from workspace-relative ("tests/test/sorting/ClassTest.java") to tests-repo-relative ("test/sorting/ClassTest.java"), as the gate expects.
        String workspaceTestsPrefix = GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/";
        Map<String, String> producedTestsFiles = new LinkedHashMap<>();
        producedTestsFiles.put("pom.xml", ARES_POM);
        seeded.forEach((path, content) -> {
            if (path.startsWith(workspaceTestsPrefix)) {
                producedTestsFiles.put(path.substring(workspaceTestsPrefix.length()), content);
            }
        });
        assertThat(producedTestsFiles).containsKeys("test/sorting/ClassTest.java", "test/sorting/MethodTest.java").doesNotContainKeys("test/sorting/AttributeTest.java",
                "test/sorting/ConstructorTest.java");

        assertThat(ExerciseIntegrityGate.javaAresConventionReasons(producedTestsFiles))
                .as("the seeder's own @StrictTimeout(10) structural test classes must pass the integrity gate they are composed with in production").isEmpty();
    }

    @Test
    void seedsNothing_whenOnlyAPrivateHelperDiffers() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        // The class exists in both; only the solution's PRIVATE helper is absent from the template stub. This must NOT seed structural tests.
        Map<String, String> solution = Map.of("src/roman/RomanNumerals.java",
                "package roman;\npublic class RomanNumerals {\n    public int toInteger(String r){ return 0; }\n    private int valueOf(char c){ return 0; }\n}");
        Map<String, String> template = Map.of("src/roman/RomanNumerals.java", "package roman;\npublic class RomanNumerals {\n    public int toInteger(String r){ return 0; }\n}");
        Map<String, String> tests = Map.of("test/roman/RomanNumeralsTest.java", "package roman;\nclass RomanNumeralsTest {}");

        java.util.Set<String> seededNames = seederWith(sandbox, solution, template, tests).seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox, never()).copyIn(any(), any(), any());
        assertThat(seededNames).as("a behaviour-only diff seeds nothing, so there are no exempt structural names").isEmpty();
    }

    @Test
    void preservesUnmanagedStructuralAssets() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/MergeSort.java", "package sorting;\npublic class MergeSort {}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        Map<String, String> tests = new LinkedHashMap<>();
        tests.put("test/sorting/SortTest.java", "package sorting;\nclass SortTest {}");
        tests.put("test/structural/test.json", "[]");
        tests.put("test/structural/ClassTest.java", "package structural;\nclass ClassTest {}");

        java.util.Set<String> seededNames = seederWith(sandbox, solution, template, tests).seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox, never()).copyIn(any(), any(), any());
        verify(sandbox, never()).exec(any(), any(), any(), any(), any());
        assertThat(seededNames).isEmpty();
    }

    @Test
    void refusesToOverwriteUnmanagedStructuralAssetsForAnApprovedStudentCreatedType() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/MergeSort.java", "package sorting;\npublic class MergeSort {}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        Map<String, String> tests = Map.of("test/structural/test.json", "[]", "test/structural/ClassTest.java", "package structural;\nclass ClassTest {}");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs.approve("s", "## Design\n| Type | Role | Template status |\n|---|---|---|\n| MergeSort | strategy | student-creates |");

        assertThatThrownBy(() -> seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise()))
                .isInstanceOf(IllegalStateException.class).hasMessageContaining("Refusing to overwrite").hasMessageContaining("MergeSort");
        verify(sandbox, never()).copyIn(any(), any(), any());
    }

    @Test
    void refreshesACompleteManagedBundleWithOnlyApplicableProviders() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), eq("sh"), eq("-c"), any())).thenReturn(new SandboxExecResult(0, "", "", false));
        Map<String, String> solution = Map.of("src/sorting/MergeSort.java", "package sorting;\npublic class MergeSort { public void sort() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        String oracle = "[{\"class\":{\"name\":\"MergeSort\"},\"methods\":[{\"name\":\"sort\"}]}]";
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting; class SortTest {}", "test/sorting/test.json", oracle, "test/sorting/ClassTest.java",
                GENERATED_MARKER + "\nclass ClassTest {}", "test/sorting/MethodTest.java", GENERATED_MARKER + "\nclass MethodTest {}");

        java.util.Set<String> seededNames = seederWith(sandbox, solution, template, tests).seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox).copyIn(eq("s"), eq("/workspace"), any());
        ArgumentCaptor<String> cleanupCommand = ArgumentCaptor.forClass(String.class);
        verify(sandbox).exec(eq("s"), any(), eq("sh"), eq("-c"), cleanupCommand.capture());
        assertThat(cleanupCommand.getValue()).contains("ClassTest.java", "MethodTest.java", "AttributeTest.java", "ConstructorTest.java", "test.json");
        assertThat(seededNames).containsExactlyInAnyOrder("testClass[MergeSort]", "testMethods[MergeSort]");
    }

    @Test
    void removesManagedStructuralFiles_whenStructuresAreIdentical() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), eq("sh"), eq("-c"), any())).thenReturn(new SandboxExecResult(0, "", "", false));
        String identical = "package sorting;\npublic class BubbleSort {\n    public int[] sort(int[] a){ return a; }\n}";
        Map<String, String> tests = new LinkedHashMap<>();
        tests.put("test/sorting/BubbleSortTest.java", "package sorting;\nclass BubbleSortTest {}");
        tests.put("test/structural/test.json", "[]");
        for (String className : java.util.List.of("ClassTest.java", "MethodTest.java", "AttributeTest.java", "ConstructorTest.java")) {
            tests.put("test/structural/" + className, GENERATED_MARKER + "\npackage structural;\nclass Test {}");
        }
        java.util.Set<String> seededNames = seederWith(sandbox, Map.of("src/sorting/BubbleSort.java", identical), Map.of("src/sorting/BubbleSort.java", identical), tests)
                .seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox, never()).copyIn(any(), any(), any());
        assertThat(seededNames).isEmpty();
        ArgumentCaptor<String> cleanupCommand = ArgumentCaptor.forClass(String.class);
        verify(sandbox).exec(eq("s"), any(), eq("sh"), eq("-c"), cleanupCommand.capture());
        assertThat(cleanupCommand.getValue()).startsWith("rm -f").contains("/workspace/tests/test/structural/").contains("test.json").contains("ClassTest.java");
    }

    @Test
    void skipsNonJavaLanguages() {
        GenerationWorkspaceService workspace = mock(GenerationWorkspaceService.class);
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        ProgrammingExercise python = new ProgrammingExercise();
        python.setProgrammingLanguage(ProgrammingLanguage.PYTHON);

        java.util.Set<String> seededNames = new StructuralOracleSeedingService(workspace, new TempFileUtilService(tempDir)).seedIfStructuralDiff(sandbox, "s", python);

        verify(sandbox, never()).copyIn(any(), any(), any());
        verify(workspace, never()).extractRepositoryFiles(any(), any(), any());
        assertThat(seededNames).isEmpty();
    }

    @Test
    void filterOracle_keepsOnlyCreatedPublicClasses_andStripsPrivateMembers() throws Exception {
        // MergeSort is a public class missing from the template (keep, but drop its private member); BubbleSort exists in the template (drop the whole entry).
        String oracle = """
                [ { "class": { "name": "MergeSort", "package": "sorting" },
                    "methods": [ { "name": "sort", "modifiers": ["public"] }, { "name": "merge", "modifiers": ["private"] } ] },
                  { "class": { "name": "BubbleSort", "package": "sorting" },
                    "methods": [ { "name": "helper", "modifiers": ["private"] } ] } ]
                """;
        Map<String, String> templateFiles = Map.of("src/sorting/BubbleSort.java", "package sorting;\npublic class BubbleSort {}");
        Map<String, String> solutionFiles = Map.of("src/sorting/BubbleSort.java", "package sorting;\npublic class BubbleSort {}", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort {}");

        String filtered = StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles);

        assertThat(filtered).contains("MergeSort").contains("sort").doesNotContain("BubbleSort").doesNotContain("merge").doesNotContain("helper");
    }

    @Test
    void approvedOwnershipPreventsASolutionOnlyHelperFromBecomingGradedStructure() throws Exception {
        String oracle = """
                [ { "class": { "name": "StudentStrategy", "package": "sorting" }, "methods": [] },
                  { "class": { "name": "SolutionHelper", "package": "sorting" }, "methods": [] } ]
                """;
        Map<String, String> solutionFiles = Map.of("src/sorting/StudentStrategy.java", "package sorting; public class StudentStrategy {}", "src/sorting/SolutionHelper.java",
                "package sorting; public class SolutionHelper {}");

        String filtered = StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, Map.of(), solutionFiles, Set.of("StudentStrategy"));

        assertThat(filtered).contains("StudentStrategy").doesNotContain("SolutionHelper");
    }

    @Test
    void approvedSpecificationWithNoStudentCreatedTypesDoesNotGradeSolutionOnlyHelpers() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/SolutionHelper.java", "package sorting;\npublic class SolutionHelper { public void help() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs.approve("s", "## Design\n| Type | Role | Template status |\n|---|---|---|\n| Sorter | provided API | given |");

        Set<String> seededNames = seederWith(sandbox, solution, template, Map.of(), approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise());

        assertThat(seededNames).isEmpty();
        verify(sandbox, never()).copyIn(any(), any(), any());
    }

    @Test
    void filterOracle_dropsAMissingButNonPublicClass() throws Exception {
        // A package-private helper class missing from the template is an implementation detail, not a contract the student must fulfil — do not enforce it.
        String oracle = "[ { \"class\": { \"name\": \"Helper\", \"package\": \"x\" }, \"methods\": [ { \"name\": \"h\", \"modifiers\": [\"public\"] } ] } ]";
        Map<String, String> templateFiles = Map.of("src/x/Main.java", "package x;\npublic class Main {}");
        Map<String, String> solutionFiles = Map.of("src/x/Helper.java", "package x;\nclass Helper { public void h(){} }");

        assertThat(StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles)).isEqualTo("[]");
    }

    @Test
    void isStructurallyEmpty_recognizesEmptyOracles() {
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[]")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[ ]")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("  ")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty(null)).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[ { \"class\": {} } ]")).isFalse();
    }
}
