package de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.verification;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.ArgumentCaptor;

import de.tum.cit.aet.artemis.buildagent.dto.SandboxExecResultDTO;
import de.tum.cit.aet.artemis.buildagent.service.InteractiveSandbox;
import de.tum.cit.aet.artemis.core.service.TempFileUtilService;
import de.tum.cit.aet.artemis.hyperion.service.exercisegeneration.workspace.GenerationWorkspaceService;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingExercise;
import de.tum.cit.aet.artemis.programming.domain.ProgrammingLanguage;
import de.tum.cit.aet.artemis.programming.domain.RepositoryType;

/**
 * Deterministic test for the structural-oracle seeder (no Docker, no LLM): it runs the real
 * {@link de.tum.cit.aet.artemis.programming.service.structureoraclegenerator.OracleGenerator} over fixture sources and asserts that structural tests are seeded ONLY for a public
 * class the student must create (absent from the template), and never for incidental member differences within shared classes.
 */
class StructuralOracleSeedingServiceTest {

    private static final String GENERATED_MARKER = "// Generated by Artemis Hyperion structural oracle seeding. Safe to replace.";

    @TempDir
    private Path tempDir;

    private static ProgrammingExercise javaExercise() {
        ProgrammingExercise exercise = new ProgrammingExercise();
        exercise.setProgrammingLanguage(ProgrammingLanguage.JAVA);
        return exercise;
    }

    private static ApprovedSpecRegistry approvedSpec(String type, String declaration) {
        ApprovedSpecRegistry registry = new ApprovedSpecRegistry();
        registry.approve("s", """
                ## Design
                | Type | Role | Template status |
                |---|---|---|
                | %s | student-owned type | student-creates |

                ## Public API
                ### %s
                ```java
                %s
                ```
                """.formatted(type, type, declaration));
        return registry;
    }

    private StructuralOracleSeedingService seederWith(InteractiveSandbox sandbox, Map<String, String> solution, Map<String, String> template, Map<String, String> tests) {
        return seederWith(sandbox, solution, template, tests, new ApprovedSpecRegistry());
    }

    private StructuralOracleSeedingService seederWith(InteractiveSandbox sandbox, Map<String, String> solution, Map<String, String> template, Map<String, String> tests,
            ApprovedSpecRegistry approvedSpecs) {
        GenerationWorkspaceService workspace = mock(GenerationWorkspaceService.class);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.SOLUTION)).thenReturn(solution);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TEMPLATE)).thenReturn(template);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TESTS)).thenReturn(tests);
        return new StructuralOracleSeedingService(workspace, new TempFileUtilService(tempDir), approvedSpecs);
    }

    private static Map<String, String> readTar(InputStream in) throws Exception {
        Map<String, String> entries = new LinkedHashMap<>();
        try (TarArchiveInputStream tar = new TarArchiveInputStream(in)) {
            TarArchiveEntry entry;
            while ((entry = tar.getNextEntry()) != null) {
                if (!entry.isDirectory()) {
                    entries.put(entry.getName(), new String(tar.readAllBytes(), StandardCharsets.UTF_8));
                }
            }
        }
        return entries;
    }

    @Test
    void seedsStructuralTests_whenTemplateOmitsAWholePublicClass() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        // Solution has Sorter (in both) and MergeSort (a public class the student must create); the template omits MergeSort entirely.
        Map<String, String> solution = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort implements Sorter {\n    public int[] sort(int[] a){ return a; }\n}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }");
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting;\nclass SortTest {}");

        ApprovedSpecRegistry approvedSpecs = approvedSpec("MergeSort", """
                public class MergeSort implements Sorter {
                    public int[] sort(int[] a);
                }
                """);
        ProgrammingExercise exercise = javaExercise();
        exercise.setPackageName("sorting");
        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", exercise);

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        Map<String, String> seeded = readTar(tarCaptor.getValue());
        assertThat(seeded)
                .containsKeys("tests/test/sorting/ClassTest.java", "tests/test/sorting/MethodTest.java", "tests/test/sorting/ConstructorTest.java", "tests/test/sorting/test.json")
                .doesNotContainKeys("tests/test/sorting/AttributeTest.java");
        assertThat(seeded.get("tests/test/sorting/ClassTest.java")).startsWith(GENERATED_MARKER).contains("package sorting;").doesNotContain("${packageName}");
        // The oracle enforces the created class, not the already-present interface.
        assertThat(seeded.get("tests/test/sorting/test.json")).contains("MergeSort");
        assertThat(seededTests.repositoryFiles()).containsOnlyKeys("test/sorting/ClassTest.java", "test/sorting/MethodTest.java", "test/sorting/ConstructorTest.java",
                "test/sorting/test.json");
        assertThat(seededTests.repositoryFiles().get("test/sorting/test.json")).isEqualTo(seeded.get("tests/test/sorting/test.json"));
        // Only providers with something to check are seeded: empty factories all report under the shared factory-method name generateTestsForAllClasses, which creates
        // duplicate production test cases and fails an otherwise correct solution.
        assertThat(seededTests.testNames()).containsExactlyInAnyOrder("testClass[MergeSort]", "testMethods[MergeSort]", "testConstructors[MergeSort]");
    }

    @Test
    void seedsStructuralTestsBeforeAnyAgentAuthoredJavaTestExists() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/navigation/Strategy.java", "package navigation; public interface Strategy { double apply(double x); }",
                "src/navigation/Warp.java", "package navigation; public class Warp implements Strategy { public double apply(double x) { return x; } }");
        Map<String, String> template = Map.of("src/navigation/Strategy.java", "package navigation; public interface Strategy { double apply(double x); }");
        Map<String, String> harnessOnly = Map.of("pom.xml", "<project/>");

        ApprovedSpecRegistry approvedSpecs = approvedSpec("Warp", """
                public class Warp implements Strategy {
                    public double apply(double x);
                }
                """);
        ProgrammingExercise exercise = javaExercise();
        exercise.setPackageName("navigation");
        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, harnessOnly, approvedSpecs).seedIfStructuralDiff(sandbox, "s", exercise);

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        assertThat(readTar(tarCaptor.getValue())).containsKeys("tests/test/navigation/ClassTest.java", "tests/test/navigation/MethodTest.java",
                "tests/test/navigation/ConstructorTest.java", "tests/test/navigation/test.json");
        assertThat(seededTests.testNames()).containsExactlyInAnyOrder("testClass[Warp]", "testMethods[Warp]", "testConstructors[Warp]");
    }

    @Test
    void approvedPublicApiIsFrozen_andInventedOverloadsNeverBecomeStructuralRequirements() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> firstSolution = Map.of("src/lift/DispatchStrategy.java", "package lift; public interface DispatchStrategy {}", "src/lift/ElevatorDispatcher.java", """
                package lift;
                import java.util.ArrayList;
                import java.util.List;
                public class ElevatorDispatcher {
                    public ElevatorDispatcher(List<String> elevators, DispatchStrategy strategy) {}
                    public ElevatorDispatcher(ArrayList<String> elevators, DispatchStrategy strategy) {}
                    public String dispatchCall(int floor) { return ""; }
                    public String dispatchCall(String floor) { return ""; }
                }
                """);
        Map<String, String> laterSolution = Map.of("src/lift/DispatchStrategy.java", "package lift; public interface DispatchStrategy {}", "src/lift/ElevatorDispatcher.java", """
                package lift;
                import java.util.Collection;
                import java.util.List;
                public class ElevatorDispatcher {
                    public ElevatorDispatcher(List<String> elevators, DispatchStrategy strategy) {}
                    public ElevatorDispatcher(Collection<String> elevators, DispatchStrategy strategy) {}
                    public String dispatchCall(int floor) { return ""; }
                    public String dispatchCall(long floor) { return ""; }
                }
                """);
        Map<String, String> template = Map.of("src/lift/DispatchStrategy.java", "package lift; public interface DispatchStrategy {}");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs.approve("s", """
                ## Design
                | Type | Role | Template status |
                |---|---|---|
                | ElevatorDispatcher | dispatcher | student-creates |

                ## Public API
                ### ElevatorDispatcher
                ```java
                public class ElevatorDispatcher {
                    public ElevatorDispatcher(List<String> elevators, DispatchStrategy strategy);
                    public String dispatchCall(int floor);
                }
                ```

                ## Testing Strategy
                """);
        GenerationWorkspaceService workspace = mock(GenerationWorkspaceService.class);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.SOLUTION)).thenReturn(firstSolution, laterSolution);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TEMPLATE)).thenReturn(template);
        when(workspace.extractRepositoryFiles(sandbox, "s", RepositoryType.TESTS)).thenReturn(Map.of());
        StructuralOracleSeedingService seeder = new StructuralOracleSeedingService(workspace, new TempFileUtilService(tempDir), approvedSpecs);

        ProgrammingExercise exercise = javaExercise();
        exercise.setPackageName("lift");
        SeededStructuralTests firstTests = seeder.seedIfStructuralDiff(sandbox, "s", exercise);
        SeededStructuralTests laterTests = seeder.seedIfStructuralDiff(sandbox, "s", exercise);

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox, org.mockito.Mockito.times(2)).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        String firstOracle = readTar(tarCaptor.getAllValues().get(0)).get("tests/test/lift/test.json");
        String laterOracle = readTar(tarCaptor.getAllValues().get(1)).get("tests/test/lift/test.json");
        assertThat(firstOracle).isEqualTo(laterOracle).contains("\"List\"", "\"DispatchStrategy\"", "\"int\"").doesNotContain("ArrayList", "Collection", "\"long\"",
                "\"parameters\" : [ \"String\" ]");
        assertThat(firstTests.testNames()).isEqualTo(laterTests.testNames()).containsExactlyInAnyOrder("testClass[ElevatorDispatcher]", "testMethods[ElevatorDispatcher]",
                "testConstructors[ElevatorDispatcher]");
    }

    /** A minimal Ares-compliant Maven pom, matching what the harness-convention gate demands, so the composed test isolates the timeout/annotation check under test. */
    private static final String ARES_POM = """
            <project>
                <dependencies>
                    <dependency>
                        <groupId>de.tum.in.ase</groupId>
                        <artifactId>artemis-java-test-sandbox</artifactId>
                    </dependency>
                </dependencies>
                <build><plugins><plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <configuration><rules><requireFilesDontExist><files>
                        <file>${project.build.outputDirectory}/de/tum/in/test/api/</file>
                        <file>${project.build.outputDirectory}/org/junit/</file>
                    </files></requireFilesDontExist></rules></configuration>
                </plugin></plugins></build>
            </project>
            """;

    @Test
    void seededStructuralTestClasses_passTheJavaAresConventionIntegrityGate() throws Exception {
        // Production composes this seeder with ExerciseIntegrityGate: the seeded classes carry @StrictTimeout(10), so the gate must not reject the seed it is composed with.
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort implements Sorter {\n    public int[] sort(int[] a){ return a; }\n}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter { int[] sort(int[] a); }");
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting;\nclass SortTest {}");

        ApprovedSpecRegistry approvedSpecs = approvedSpec("MergeSort", """
                public class MergeSort implements Sorter {
                    public int[] sort(int[] a);
                }
                """);
        ProgrammingExercise exercise = javaExercise();
        exercise.setPackageName("sorting");
        seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", exercise);

        ArgumentCaptor<InputStream> tarCaptor = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tarCaptor.capture());
        Map<String, String> seeded = readTar(tarCaptor.getValue());

        // Re-key from workspace-relative ("tests/test/sorting/ClassTest.java") to tests-repo-relative ("test/sorting/ClassTest.java"), as the gate expects.
        String workspaceTestsPrefix = GenerationWorkspaceService.directoryFor(RepositoryType.TESTS) + "/";
        Map<String, String> producedTestsFiles = new LinkedHashMap<>();
        producedTestsFiles.put("pom.xml", ARES_POM);
        seeded.forEach((path, content) -> {
            if (path.startsWith(workspaceTestsPrefix)) {
                producedTestsFiles.put(path.substring(workspaceTestsPrefix.length()), content);
            }
        });
        assertThat(producedTestsFiles).containsKeys("test/sorting/ClassTest.java", "test/sorting/MethodTest.java", "test/sorting/ConstructorTest.java")
                .doesNotContainKeys("test/sorting/AttributeTest.java");

        assertThat(ExerciseIntegrityGate.javaAresConventionReasons(producedTestsFiles))
                .as("the seeder's own @StrictTimeout(10) structural test classes must pass the integrity gate they are composed with in production").isEmpty();
    }

    @Test
    void seedsNothing_whenOnlyAPrivateHelperDiffers() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        // The class exists in both; only the solution's PRIVATE helper is absent from the template stub. This must NOT seed structural tests.
        Map<String, String> solution = Map.of("src/roman/RomanNumerals.java",
                "package roman;\npublic class RomanNumerals {\n    public int toInteger(String r){ return 0; }\n    private int valueOf(char c){ return 0; }\n}");
        Map<String, String> template = Map.of("src/roman/RomanNumerals.java", "package roman;\npublic class RomanNumerals {\n    public int toInteger(String r){ return 0; }\n}");
        Map<String, String> tests = Map.of("test/roman/RomanNumeralsTest.java", "package roman;\nclass RomanNumeralsTest {}");

        StructuralOracleSeedingService seeder = seederWith(sandbox, solution, template, tests);
        seeder.captureBaseline("s", tests);
        SeededStructuralTests seededTests = seeder.seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox, never()).copyIn(any(), any(), any());
        assertThat(seededTests.testNames()).as("a behaviour-only diff seeds nothing, so there are no exempt structural names").isEmpty();
    }

    @Test
    void refusesToOverwriteUnmanagedStructuralAssetsForAnApprovedStudentCreatedType() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/MergeSort.java", "package sorting;\npublic class MergeSort {}");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        Map<String, String> tests = Map.of("test/structural/test.json", "[{\"class\":{\"name\":\"Legacy\"}}]", "test/structural/ClassTest.java",
                "package structural; class ClassTest extends ClassTestProvider { void x(){ retrieveStructureOracleJSON(null); } }");
        ApprovedSpecRegistry approvedSpecs = approvedSpec("MergeSort", "public class MergeSort { public void sort(); }");

        assertThatThrownBy(() -> seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise()))
                .isInstanceOf(IllegalStateException.class).hasMessageContaining("Refusing to overwrite").hasMessageContaining("MergeSort");
        verify(sandbox, never()).copyIn(any(), any(), any());
    }

    @Test
    void reseedsAfterTheAgentDeletedTheStructuralClassesThisServiceSeeded() {
        // An earlier attempt seeded test.json plus both provider classes and the agent then deleted the classes; the surviving oracle is this service's own incomplete output,
        // not somebody else's grading harness, so reading it as unmanaged would discard the whole generation.
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), any(String[].class))).thenReturn(new SandboxExecResultDTO(0, "", "", false));
        Map<String, String> solution = Map.of("src/sorting/ScoreProcessor.java", "package sorting;\npublic class ScoreProcessor { public void process() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        Map<String, String> tests = Map.of("test/sorting/ScoreProcessorTest.java", "package sorting; class ScoreProcessorTest {}", "test/sorting/test.json",
                "[{\"class\":{\"name\":\"ScoreProcessor\"}}]");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs = approvedSpec("ScoreProcessor", "public class ScoreProcessor { public void process(); }");

        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise());

        assertThat(seededTests.testNames()).contains("testClass[ScoreProcessor]");
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), any());
    }

    @Test
    void reseedsWhenOnlySomeOfTheSeededStructuralClassesSurvive() {
        // One marked class left behind, the other deleted: the marker identifies ownership, not the completeness of the bundle.
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), any(String[].class))).thenReturn(new SandboxExecResultDTO(0, "", "", false));
        Map<String, String> solution = Map.of("src/sorting/ScoreProcessor.java", "package sorting;\npublic class ScoreProcessor { public void process() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        Map<String, String> tests = Map.of("test/sorting/test.json", "[{\"class\":{\"name\":\"ScoreProcessor\"},\"methods\":[{\"name\":\"process\"}]}]",
                "test/sorting/ClassTest.java", GENERATED_MARKER + "\nclass ClassTest {}");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs = approvedSpec("ScoreProcessor", "public class ScoreProcessor { public void process(); }");

        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise());

        assertThat(seededTests.testNames()).contains("testClass[ScoreProcessor]");
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), any());
    }

    @Test
    void refreshesACompleteManagedBundleWithOnlyApplicableProviders() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), any(String[].class))).thenReturn(new SandboxExecResultDTO(0, "", "", false));
        Map<String, String> solution = Map.of("src/sorting/MergeSort.java", "package sorting;\npublic class MergeSort { public void sort() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        String oracle = "[{\"class\":{\"name\":\"MergeSort\"},\"methods\":[{\"name\":\"sort\"}]}]";
        Map<String, String> tests = Map.of("test/sorting/SortTest.java", "package sorting; class SortTest {}", "test/sorting/test.json", oracle, "test/sorting/ClassTest.java",
                GENERATED_MARKER + "\nclass ClassTest {}", "test/sorting/MethodTest.java", GENERATED_MARKER + "\nclass MethodTest {}");

        ApprovedSpecRegistry approvedSpecs = approvedSpec("MergeSort", "public class MergeSort { public void sort(); }");
        ProgrammingExercise exercise = javaExercise();
        exercise.setPackageName("sorting");
        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, tests, approvedSpecs).seedIfStructuralDiff(sandbox, "s", exercise);

        verify(sandbox).copyIn(eq("s"), eq("/workspace"), any());
        ArgumentCaptor<String[]> cleanupCommand = ArgumentCaptor.forClass(String[].class);
        verify(sandbox).exec(eq("s"), any(), cleanupCommand.capture());
        assertThat(cleanupCommand.getValue()).anyMatch(argument -> argument.contains("ClassTest.java")).anyMatch(argument -> argument.contains("MethodTest.java"))
                .anyMatch(argument -> argument.contains("AttributeTest.java")).anyMatch(argument -> argument.contains("ConstructorTest.java"))
                .anyMatch(argument -> argument.contains("test.json"));
        assertThat(seededTests.testNames()).containsExactlyInAnyOrder("testClass[MergeSort]", "testMethods[MergeSort]", "testConstructors[MergeSort]");
    }

    @Test
    void restoresAnEmptyPreAuthoringBaseline_insteadOfTrustingAgentAuthoredStructuralAssets() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        when(sandbox.exec(eq("s"), any(), any(String[].class))).thenReturn(new SandboxExecResultDTO(0, "", "", false));
        Map<String, String> tests = new LinkedHashMap<>();
        tests.put("test/sorting/BubbleSortTest.java", "package sorting;\nclass BubbleSortTest {}");
        tests.put("test/structural/test.json", "[{\"class\":{\"name\":\"Invented\"}}]");
        for (String className : java.util.List.of("ClassTest.java", "MethodTest.java", "AttributeTest.java", "ConstructorTest.java")) {
            tests.put("test/structural/" + className, GENERATED_MARKER + "\npackage structural;\nclass Test {}");
        }
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), tests);
        seeder.captureBaseline("s", Map.of());
        SeededStructuralTests seededTests = seeder.seedIfStructuralDiff(sandbox, "s", javaExercise());

        verify(sandbox, never()).copyIn(any(), any(), any());
        assertThat(seededTests.testNames()).isEmpty();
        ArgumentCaptor<String[]> cleanupCommand = ArgumentCaptor.forClass(String[].class);
        verify(sandbox).exec(eq("s"), any(), cleanupCommand.capture());
        assertThat(cleanupCommand.getValue()).startsWith("rm", "-f", "--").anyMatch(argument -> argument.contains("/workspace/tests/test/structural/test.json"))
                .anyMatch(argument -> argument.contains("ClassTest.java"));
    }

    @Test
    void preservesOrdinaryTestsWhoseBasenamesOverlapStructuralAssets() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> ordinaryFiles = Map.of("test/helpers/ClassTest.java", "package helpers; class ClassTest {}", "fixtures/test.json",
                "{\"description\":\"ordinary test data\"}");
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), ordinaryFiles);
        seeder.captureBaseline("s", ordinaryFiles);

        assertThat(seeder.seedIfStructuralDiff(sandbox, "s", javaExercise())).isEqualTo(SeededStructuralTests.EMPTY);
        verify(sandbox, never()).exec(any(), any(), any(String[].class));
        verify(sandbox, never()).copyIn(any(), any(), any());
    }

    @Test
    void rejectsMalformedOrIncompletePreAuthoringStructuralBundles() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), Map.of());
        String provider = "class MethodTest extends MethodTestProvider { void load(){ retrieveStructureOracleJSON(null); } }";

        assertThatThrownBy(() -> seeder.captureBaseline("broken", Map.of("test/x/test.json", "not-json", "test/x/MethodTest.java", provider)))
                .isInstanceOf(IllegalStateException.class).hasMessageContaining("incomplete or malformed");
        assertThatThrownBy(() -> seeder.captureBaseline("partial",
                Map.of("test/x/test.json", "[{\"class\":{\"name\":\"X\"},\"methods\":[{\"name\":\"work\"}]}]", "test/x/ClassTest.java",
                        "class ClassTest extends ClassTestProvider { void load(){ retrieveStructureOracleJSON(null); } }")))
                .isInstanceOf(IllegalStateException.class).hasMessageContaining("missing required provider").hasMessageContaining("MethodTest.java");
    }

    @Test
    void preservesAValidRawBaselineByteForByte_andFreezesItOnce() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        String oracle = "[{\"class\":{\"name\":\"X\"}}]";
        String classProvider = "class ClassTest extends ClassTestProvider { String raw = \"${studentWorkingDirectory}\"; void load(){ retrieveStructureOracleJSON(null); } }";
        Map<String, String> baseline = Map.of("test/x/test.json", oracle, "test/x/ClassTest.java", classProvider);
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), baseline);
        seeder.captureBaseline("s", baseline);

        assertThat(seeder.seedIfStructuralDiff(sandbox, "s", javaExercise()).testNames()).containsExactly("testClass[X]");
        verify(sandbox, never()).exec(any(), any(), any(String[].class));
        verify(sandbox, never()).copyIn(any(), any(), any());
        assertThatThrownBy(() -> seeder.captureBaseline("s", Map.of())).isInstanceOf(IllegalStateException.class).hasMessageContaining("already captured");
    }

    @Test
    void restoresADeletedBaselineBundleExactly() throws Exception {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        String oracle = "[{\"class\":{\"name\":\"X\"}}]";
        String classProvider = "class ClassTest extends ClassTestProvider { void load(){ retrieveStructureOracleJSON(null); } }";
        Map<String, String> baseline = Map.of("test/x/test.json", oracle, "test/x/ClassTest.java", classProvider);
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), Map.of());
        seeder.captureBaseline("s", baseline);

        assertThat(seeder.seedIfStructuralDiff(sandbox, "s", javaExercise()).testNames()).containsExactly("testClass[X]");
        ArgumentCaptor<InputStream> tar = ArgumentCaptor.forClass(InputStream.class);
        verify(sandbox).copyIn(eq("s"), eq("/workspace"), tar.capture());
        assertThat(readTar(tar.getValue())).containsEntry("tests/test/x/test.json", oracle).containsEntry("tests/test/x/ClassTest.java", classProvider);
    }

    @Test
    void failsClosedWhenNoPreAuthoringBaselineWasCaptured() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        StructuralOracleSeedingService seeder = seederWith(sandbox, Map.of(), Map.of(), Map.of());

        assertThatThrownBy(() -> seeder.seedIfStructuralDiff(sandbox, "s", javaExercise())).isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("No pre-authoring structural baseline");
    }

    @Test
    void skipsNonJavaLanguages() {
        GenerationWorkspaceService workspace = mock(GenerationWorkspaceService.class);
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        ProgrammingExercise python = new ProgrammingExercise();
        python.setProgrammingLanguage(ProgrammingLanguage.PYTHON);

        SeededStructuralTests seededTests = new StructuralOracleSeedingService(workspace, new TempFileUtilService(tempDir)).seedIfStructuralDiff(sandbox, "s", python);

        verify(sandbox, never()).copyIn(any(), any(), any());
        verify(workspace, never()).extractRepositoryFiles(any(), any(), any());
        assertThat(seededTests.testNames()).isEmpty();
    }

    @Test
    void filterOracle_keepsOnlyCreatedPublicClasses_andStripsPrivateMembers() throws Exception {
        // MergeSort is a public class missing from the template (keep, but drop its private member); BubbleSort exists in the template (drop the whole entry).
        String oracle = """
                [ { "class": { "name": "MergeSort", "package": "sorting" },
                    "methods": [ { "name": "sort", "modifiers": ["public"] }, { "name": "merge", "modifiers": ["private"] } ] },
                  { "class": { "name": "BubbleSort", "package": "sorting" },
                    "methods": [ { "name": "helper", "modifiers": ["private"] } ] } ]
                """;
        Map<String, String> templateFiles = Map.of("src/sorting/BubbleSort.java", "package sorting;\npublic class BubbleSort {}");
        Map<String, String> solutionFiles = Map.of("src/sorting/BubbleSort.java", "package sorting;\npublic class BubbleSort {}", "src/sorting/MergeSort.java",
                "package sorting;\npublic class MergeSort {}");

        String filtered = StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles);

        assertThat(filtered).contains("MergeSort").contains("sort").doesNotContain("BubbleSort").doesNotContain("merge").doesNotContain("helper");
    }

    @Test
    void approvedOwnershipPreventsASolutionOnlyHelperFromBecomingGradedStructure() throws Exception {
        String oracle = """
                [ { "class": { "name": "StudentStrategy", "package": "sorting" }, "methods": [] },
                  { "class": { "name": "SolutionHelper", "package": "sorting" }, "methods": [] } ]
                """;
        Map<String, String> solutionFiles = Map.of("src/sorting/StudentStrategy.java", "package sorting; public class StudentStrategy {}", "src/sorting/SolutionHelper.java",
                "package sorting; public class SolutionHelper {}");

        String filtered = StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, Map.of(), solutionFiles, Set.of("StudentStrategy"));

        assertThat(filtered).contains("StudentStrategy").doesNotContain("SolutionHelper");
    }

    @Test
    void approvedSpecificationWithNoStudentCreatedTypesDoesNotGradeSolutionOnlyHelpers() {
        InteractiveSandbox sandbox = mock(InteractiveSandbox.class);
        Map<String, String> solution = Map.of("src/sorting/SolutionHelper.java", "package sorting;\npublic class SolutionHelper { public void help() {} }");
        Map<String, String> template = Map.of("src/sorting/Sorter.java", "package sorting;\npublic interface Sorter {}");
        ApprovedSpecRegistry approvedSpecs = new ApprovedSpecRegistry();
        approvedSpecs.approve("s", """
                ## Design
                | Type | Role | Template status |
                |---|---|---|
                | Sorter | provided API | given |
                ## Public API
                ```java
                public interface Sorter { void sort(); }
                ```
                """);

        SeededStructuralTests seededTests = seederWith(sandbox, solution, template, Map.of(), approvedSpecs).seedIfStructuralDiff(sandbox, "s", javaExercise());

        assertThat(seededTests.testNames()).isEmpty();
        verify(sandbox, never()).copyIn(any(), any(), any());
    }

    @Test
    void filterOracle_dropsAMissingButNonPublicClass() throws Exception {
        // A package-private helper class missing from the template is an implementation detail, not a contract the student must fulfil — do not enforce it.
        String oracle = "[ { \"class\": { \"name\": \"Helper\", \"package\": \"x\" }, \"methods\": [ { \"name\": \"h\", \"modifiers\": [\"public\"] } ] } ]";
        Map<String, String> templateFiles = Map.of("src/x/Main.java", "package x;\npublic class Main {}");
        Map<String, String> solutionFiles = Map.of("src/x/Helper.java", "package x;\nclass Helper { public void h(){} }");

        assertThat(StructuralOracleSeedingService.filterOracleToCreatedPublicApi(oracle, templateFiles, solutionFiles)).isEqualTo("[]");
    }

    @Test
    void isStructurallyEmpty_recognizesEmptyOracles() {
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[]")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[ ]")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("  ")).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty(null)).isTrue();
        assertThat(StructuralOracleSeedingService.isStructurallyEmpty("[ { \"class\": {} } ]")).isFalse();
    }
}
