/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * CalendarApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { CalendarEvent } from '../model/calendar-event';
import { appendQueryParam } from './query-params';

@Injectable({ providedIn: 'root' })
export class CalendarApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     * @param courseId 
     * @param token 
     * @param filterOptions 
     * @param language 
     */
    getCalendarEventSubscriptionFile(courseId: number, token: string, filterOptions: Array<'LECTURES' | 'TUTORIALS' | 'EXAMS' | 'EXERCISES'>, language: 'ENGLISH' | 'GERMAN'): Observable<string> {
        const queryParams = new URLSearchParams();
        appendQueryParam(queryParams, 'token', token);
        appendQueryParam(queryParams, 'filterOptions', filterOptions);
        appendQueryParam(queryParams, 'language', language);
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/calendar/courses/${courseId}/calendar-events-ics${queryString ? `?${queryString}` : ''}`;
        return this.http.get(url, { responseType: 'text' });
    }

    /**
     * 
     * 
     */
    getCalendarEventSubscriptionToken(): Observable<string> {
        const url = `${this.basePath}/api/calendar/subscription-token`;
        return this.http.get(url, { responseType: 'text' });
    }

    /**
     * Get calendar events grouped by month
     * 
     * @param courseId 
     * @param monthKeys 
     * @param timeZone 
     * @param language 
     */
    getCalendarEventsOverlappingMonths(courseId: number, monthKeys: Array<string>, timeZone: string, language: 'ENGLISH' | 'GERMAN'): Observable<{ [key: string]: Array<CalendarEvent>; }> {
        const queryParams = new URLSearchParams();
        appendQueryParam(queryParams, 'monthKeys', monthKeys);
        appendQueryParam(queryParams, 'timeZone', timeZone);
        appendQueryParam(queryParams, 'language', language);
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/calendar/courses/${courseId}/calendar-events${queryString ? `?${queryString}` : ''}`;
        return this.http.get<{ [key: string]: Array<CalendarEvent>; }>(url);
    }

}
