/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionQuizQuestionGenerationApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { QuizQuestionGenerationResponse } from '../model/quiz-question-generation-response';
import { QuizQuestionGenerationRequest } from '../model/quiz-question-generation-request';
import { QuizQuestionBulkRefinementRequest } from '../model/quiz-question-bulk-refinement-request';
import { QuizQuestionBulkRefinementResponse } from '../model/quiz-question-bulk-refinement-response';
import { QuizQuestionRefinementResponse } from '../model/quiz-question-refinement-response';
import { QuizQuestionRefinementRequest } from '../model/quiz-question-refinement-request';

@Injectable({ providedIn: 'root' })
export class HyperionQuizQuestionGenerationApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param courseId
     * @param quizQuestionGenerationRequest
     */
    generateQuizQuestions(courseId: number, quizQuestionGenerationRequest: QuizQuestionGenerationRequest): Observable<QuizQuestionGenerationResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/quiz-exercises/generate-questions`;
        return this.http.post<QuizQuestionGenerationResponse>(url, quizQuestionGenerationRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param quizQuestionBulkRefinementRequest
     */
    refineAllQuizQuestions(courseId: number, quizQuestionBulkRefinementRequest: QuizQuestionBulkRefinementRequest): Observable<QuizQuestionBulkRefinementResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/quiz-exercises/refine-all-questions`;
        return this.http.post<QuizQuestionBulkRefinementResponse>(url, quizQuestionBulkRefinementRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param quizQuestionRefinementRequest
     */
    refineQuizQuestion(courseId: number, quizQuestionRefinementRequest: QuizQuestionRefinementRequest): Observable<QuizQuestionRefinementResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/quiz-exercises/refine-question`;
        return this.http.post<QuizQuestionRefinementResponse>(url, quizQuestionRefinementRequest);
    }

}
