/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionProblemStatementApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ChecklistAnalysisRequest } from '../model/checklist-analysis-request';
import { ChecklistAnalysisResponse } from '../model/checklist-analysis-response';
import { ChecklistActionRequest } from '../model/checklist-action-request';
import { ChecklistActionResponse } from '../model/checklist-action-response';
import { ConsistencyCheckResponse } from '../model/consistency-check-response';
import { ProblemStatementGenerationRequest } from '../model/problem-statement-generation-request';
import { ProblemStatementGenerationResponse } from '../model/problem-statement-generation-response';
import { ProblemStatementRefinementResponse } from '../model/problem-statement-refinement-response';
import { ProblemStatementGlobalRefinementRequest } from '../model/problem-statement-global-refinement-request';
import { ProblemStatementTargetedRefinementRequest } from '../model/problem-statement-targeted-refinement-request';
import { ProblemStatementRewriteResponse } from '../model/problem-statement-rewrite-response';
import { ProblemStatementRewriteRequest } from '../model/problem-statement-rewrite-request';

@Injectable({ providedIn: 'root' })
export class HyperionProblemStatementApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param courseId
     * @param checklistAnalysisRequest
     */
    analyzeChecklist(courseId: number, checklistAnalysisRequest: ChecklistAnalysisRequest): Observable<ChecklistAnalysisResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/checklist-analysis`;
        return this.http.post<ChecklistAnalysisResponse>(url, checklistAnalysisRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param section
     * @param checklistAnalysisRequest
     */
    analyzeChecklistSection(courseId: number, section: 'COMPETENCIES' | 'DIFFICULTY' | 'QUALITY', checklistAnalysisRequest: ChecklistAnalysisRequest): Observable<ChecklistAnalysisResponse> {
        const sectionPath = encodeURIComponent(String(section));
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/checklist-analysis/sections/${sectionPath}`;
        return this.http.post<ChecklistAnalysisResponse>(url, checklistAnalysisRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param checklistActionRequest
     */
    applyChecklistAction(courseId: number, checklistActionRequest: ChecklistActionRequest): Observable<ChecklistActionResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/checklist-actions`;
        return this.http.post<ChecklistActionResponse>(url, checklistActionRequest);
    }

    /**
     *
     *
     * @param exerciseId
     * @param skipThreadContext
     */
    checkExerciseConsistency(exerciseId: number, skipThreadContext?: boolean): Observable<ConsistencyCheckResponse> {
        const queryParams = new URLSearchParams();
        if (skipThreadContext !== undefined && skipThreadContext !== null) {
            queryParams.set('skipThreadContext', String(skipThreadContext));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/hyperion/programming-exercises/${exerciseId}/consistency-check${queryString ? `?${queryString}` : ''}`;
        return this.http.post<ConsistencyCheckResponse>(url, null);
    }

    /**
     *
     *
     * @param courseId
     * @param problemStatementGenerationRequest
     */
    generateProblemStatement(courseId: number, problemStatementGenerationRequest: ProblemStatementGenerationRequest): Observable<ProblemStatementGenerationResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/problem-statements/generate`;
        return this.http.post<ProblemStatementGenerationResponse>(url, problemStatementGenerationRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param problemStatementGlobalRefinementRequest
     */
    refineProblemStatementGlobally(courseId: number, problemStatementGlobalRefinementRequest: ProblemStatementGlobalRefinementRequest): Observable<ProblemStatementRefinementResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/problem-statements/refine/global`;
        return this.http.post<ProblemStatementRefinementResponse>(url, problemStatementGlobalRefinementRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param problemStatementTargetedRefinementRequest
     */
    refineProblemStatementTargeted(courseId: number, problemStatementTargetedRefinementRequest: ProblemStatementTargetedRefinementRequest): Observable<ProblemStatementRefinementResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/problem-statements/refine/targeted`;
        return this.http.post<ProblemStatementRefinementResponse>(url, problemStatementTargetedRefinementRequest);
    }

    /**
     *
     *
     * @param courseId
     * @param problemStatementRewriteRequest
     */
    rewriteProblemStatement(courseId: number, problemStatementRewriteRequest: ProblemStatementRewriteRequest): Observable<ProblemStatementRewriteResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/problem-statements/rewrite`;
        return this.http.post<ProblemStatementRewriteResponse>(url, problemStatementRewriteRequest);
    }

}
