/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionFaqApi - API service for mutations (POST, PUT, DELETE, PATCH)
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { RewriteFaqRequest } from '../models/rewrite-faq-request';
import { RewriteFaqResponse } from '../models/rewrite-faq-response';

@Injectable({ providedIn: 'root' })
export class HyperionFaqApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     * @param courseId 
     * @param rewriteFaqRequest 
     */
    rewriteFaq(courseId: number, rewriteFaqRequest: RewriteFaqRequest): Observable<RewriteFaqResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/faq/rewrite`;
        return this.http.post<RewriteFaqResponse>(url, rewriteFaqRequest);
    }

}
