/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionCodeGenerationApi - API service for mutations (POST, PUT, DELETE, PATCH)
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { CodeGenerationJobStart } from '../models/code-generation-job-start';
import { CodeGenerationRequest } from '../models/code-generation-request';

@Injectable({ providedIn: 'root' })
export class HyperionCodeGenerationApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     * @param exerciseId 
     * @param codeGenerationRequest 
     */
    generateCode(exerciseId: number, codeGenerationRequest: CodeGenerationRequest): Observable<CodeGenerationJobStart> {
        const url = `${this.basePath}/api/hyperion/programming-exercises/${exerciseId}/generate-code`;
        return this.http.post<CodeGenerationJobStart>(url, codeGenerationRequest);
    }

}
