/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionAssessmentCriteriaGenerationApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { AssessmentCriteriaGenerationRequest } from '../model/assessment-criteria-generation-request';
import { AssessmentCriteriaGenerationResponse } from '../model/assessment-criteria-generation-response';

@Injectable({ providedIn: 'root' })
export class HyperionAssessmentCriteriaGenerationApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param courseId
     * @param assessmentCriteriaGenerationRequest
     */
    generateAssessmentCriteria(courseId: number, assessmentCriteriaGenerationRequest: AssessmentCriteriaGenerationRequest): Observable<AssessmentCriteriaGenerationResponse> {
        const url = `${this.basePath}/api/hyperion/courses/${courseId}/assessment-criteria/generate`;
        return this.http.post<AssessmentCriteriaGenerationResponse>(url, assessmentCriteriaGenerationRequest);
    }

}
