/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * HyperionCodeGenerationApi Resources - Signal-based HTTP resources for GET operations
 * Uses Angular's httpResource for reactive data fetching
 * @generated from OpenAPI specification
 */
import { httpResource, HttpResourceRef } from '@angular/common/http';
import { Signal } from '@angular/core';
import { CodeGenerationJobStart } from '../model/code-generation-job-start';

const BASE_PATH = '';

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param exerciseId 
 */
export function getActiveCodeGenerationJobResource(exerciseId: Signal<number | undefined> | number): HttpResourceRef<CodeGenerationJobStart | undefined> {
    return httpResource<CodeGenerationJobStart>(() => {
        const exerciseIdValue = typeof exerciseId === 'function' ? exerciseId() : exerciseId;
        if (exerciseIdValue === undefined) {
            return undefined;
        }
        return `${BASE_PATH}/api/hyperion/programming-exercises/${exerciseIdValue}/code-generation/active-job`;
    });
}

