/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * IngestionBrowserApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { CourseBrowserData } from '../model/course-browser-data';
import { IndexedEntityRecord } from '../model/indexed-entity-record';
import { IndexedContentObject } from '../model/indexed-content-object';

@Injectable({ providedIn: 'root' })
export class IngestionBrowserApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param courseId
     */
    getCourseBrowserData(courseId: number): Observable<CourseBrowserData> {
        const url = `${this.basePath}/api/global-search/admin/courses/${courseId}/browser`;
        return this.http.get<CourseBrowserData>(url);
    }

    /**
     *
     *
     * @param courseId
     * @param type
     */
    getIndexedEntityRecords(courseId: number, type: string): Observable<Array<IndexedEntityRecord>> {
        const queryParams = new URLSearchParams();
        if (type !== undefined && type !== null) {
            queryParams.set('type', String(type));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/global-search/admin/courses/${courseId}/entities${queryString ? `?${queryString}` : ''}`;
        return this.http.get<Array<IndexedEntityRecord>>(url);
    }

    /**
     *
     *
     * @param courseId
     * @param unitId
     * @param key
     */
    getUnitContent(courseId: number, unitId: number, key: string): Observable<Array<IndexedContentObject>> {
        const queryParams = new URLSearchParams();
        if (key !== undefined && key !== null) {
            queryParams.set('key', String(key));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/global-search/admin/courses/${courseId}/units/${unitId}/content${queryString ? `?${queryString}` : ''}`;
        return this.http.get<Array<IndexedContentObject>>(url);
    }

}
