/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * IngestionCoverageApi Resources - Signal-based HTTP resources for GET operations
 * Uses Angular's httpResource for reactive data fetching
 * @generated from OpenAPI specification
 */
import { httpResource, HttpResourceRef } from '@angular/common/http';
import { Signal } from '@angular/core';
import { IndexOverview } from '../model/index-overview';
import { Pageable } from '../model/pageable';
import { IngestionCoverage } from '../model/ingestion-coverage';
import { appendQueryParam } from './query-params';

const BASE_PATH = '';

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 */
export function getIndexOverviewResource(): HttpResourceRef<IndexOverview | undefined> {
    return httpResource<IndexOverview>(() => {
        return `${BASE_PATH}/api/global-search/admin/index/overview`;
    });
}

/**
 * Query parameters for getLiveCoveragePage
 */
export interface GetLiveCoveragePageParams {
    search?: string;
    pageable: Pageable;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param params Optional signal containing query parameters
 */
export function getLiveCoveragePageResource(params: Signal<GetLiveCoveragePageParams>): HttpResourceRef<Array<IngestionCoverage> | undefined> {
    return httpResource<Array<IngestionCoverage>>(() => {
        const queryParams = params();
        const searchParams = new URLSearchParams();
        appendQueryParam(searchParams, 'search', queryParams.search);
        appendQueryParam(searchParams, 'pageable', queryParams.pageable);
        const query = searchParams.toString();
        return `${BASE_PATH}/api/global-search/admin/coverage/page${query ? `?${query}` : ''}`;
    });
}

/**
 * Query parameters for getStoredCoverage
 */
export interface GetStoredCoverageParams {
    status?: 'COMPLETE' | 'INCOMPLETE' | 'EMPTY';
    active?: boolean;
    search?: string;
    pageable: Pageable;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param params Optional signal containing query parameters
 */
export function getStoredCoverageResource(params: Signal<GetStoredCoverageParams>): HttpResourceRef<Array<IngestionCoverage> | undefined> {
    return httpResource<Array<IngestionCoverage>>(() => {
        const queryParams = params();
        const searchParams = new URLSearchParams();
        appendQueryParam(searchParams, 'status', queryParams.status);
        appendQueryParam(searchParams, 'active', queryParams.active);
        appendQueryParam(searchParams, 'search', queryParams.search);
        appendQueryParam(searchParams, 'pageable', queryParams.pageable);
        const query = searchParams.toString();
        return `${BASE_PATH}/api/global-search/admin/coverage${query ? `?${query}` : ''}`;
    });
}

