/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 9.6
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * QuizTrainingApi - API service for mutations (POST, PUT, DELETE, PATCH)
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { LeaderboardSetting } from '../models/leaderboard-setting';
import { LeaderboardWithCurrentUserEntry } from '../models/leaderboard-with-current-user-entry';
import { QuizQuestionTraining } from '../models/quiz-question-training';
import { SubmittedAnswerAfterEvaluation } from '../models/submitted-answer-after-evaluation';
import { SubmittedAnswerFromLiveClient } from '../models/submitted-answer-from-live-client';

@Injectable({ providedIn: 'root' })
export class QuizTrainingApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     */
    getLeaderboardSettings(): Observable<LeaderboardSetting> {
        const url = `${this.basePath}/api/quiz/leaderboard-settings`;
        return this.http.get<LeaderboardSetting>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param isNewSession 
     * @param requestBody 
     * @param page Zero-based page index (0..N)
     * @param size The size of the page to be returned
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    getQuizQuestionsForPractice(courseId: number, isNewSession: boolean, requestBody: Array<number>, page?: number, size?: number, sort?: Array<string>): Observable<Array<QuizQuestionTraining>> {
        const queryParams: Record<string, string> = {};
        if (page !== undefined && page !== null) {
            queryParams['page'] = String(page);
        }
        if (size !== undefined && size !== null) {
            queryParams['size'] = String(size);
        }
        if (sort !== undefined && sort !== null) {
            queryParams['sort'] = sort.join(',');
        }
        if (isNewSession !== undefined && isNewSession !== null) {
            queryParams['isNewSession'] = String(isNewSession);
        }
        const queryString = new URLSearchParams(queryParams).toString();
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training-questions${queryString ? `?${queryString}` : ''}`;
        return this.http.post<Array<QuizQuestionTraining>>(url, requestBody);
    }

    /**
     * 
     * 
     * @param courseId 
     */
    getQuizTrainingLeaderboard(courseId: number): Observable<LeaderboardWithCurrentUserEntry> {
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training/leaderboard`;
        return this.http.get<LeaderboardWithCurrentUserEntry>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param leaderboardSetting 
     */
    initializeLeaderboardEntry(courseId: number, leaderboardSetting: LeaderboardSetting): Observable<void> {
        const url = `${this.basePath}/api/quiz/courses/${courseId}/leaderboard-entry`;
        return this.http.post<void>(url, leaderboardSetting);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param trainingQuestionId 
     * @param isRated 
     * @param submittedAnswerFromLiveClient 
     */
    submitForTraining(courseId: number, trainingQuestionId: number, isRated: boolean, submittedAnswerFromLiveClient: SubmittedAnswerFromLiveClient): Observable<SubmittedAnswerAfterEvaluation> {
        const queryParams: Record<string, string> = {};
        if (isRated !== undefined && isRated !== null) {
            queryParams['isRated'] = String(isRated);
        }
        const queryString = new URLSearchParams(queryParams).toString();
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training-questions/${trainingQuestionId}/submit${queryString ? `?${queryString}` : ''}`;
        return this.http.post<SubmittedAnswerAfterEvaluation>(url, submittedAnswerFromLiveClient);
    }

    /**
     * 
     * 
     * @param leaderboardSetting 
     */
    updateLeaderboardSettings(leaderboardSetting: LeaderboardSetting): Observable<void> {
        const url = `${this.basePath}/api/quiz/leaderboard-settings`;
        return this.http.put<void>(url, leaderboardSetting);
    }

}
