/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * QuizParticipationApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { StudentQuizParticipation } from '../model/student-quiz-participation';

@Injectable({ providedIn: 'root' })
export class QuizParticipationApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param exerciseId
     * @param participationId
     * @param submissionId
     */
    getParticipationResult(exerciseId: number, participationId: number, submissionId?: number): Observable<StudentQuizParticipation> {
        const queryParams = new URLSearchParams();
        if (submissionId !== undefined && submissionId !== null) {
            queryParams.set('submissionId', String(submissionId));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/quiz/quiz-exercises/${exerciseId}/participations/${participationId}/result${queryString ? `?${queryString}` : ''}`;
        return this.http.get<StudentQuizParticipation>(url);
    }

    /**
     *
     *
     * @param exerciseId
     */
    startParticipation(exerciseId: number): Observable<StudentQuizParticipation> {
        const url = `${this.basePath}/api/quiz/quiz-exercises/${exerciseId}/start-participation`;
        return this.http.post<StudentQuizParticipation>(url, null);
    }

}
