/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * QuizExerciseRetrievalApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { SearchResultPageDTOQuizExerciseForSearch } from '../model/search-result-page-dto-quiz-exercise-for-search';
import { QuizExerciseWithStatistics } from '../model/quiz-exercise-with-statistics';
import { QuizExerciseForStudentResponse } from '../model/quiz-exercise-for-student-response';
import { QuizExerciseForCourse } from '../model/quiz-exercise-for-course';

@Injectable({ providedIn: 'root' })
export class QuizExerciseRetrievalApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param searchTerm
     * @param page
     * @param pageSize
     * @param sortingOrder
     * @param isCourseFilter
     * @param isExamFilter
     */
    getAllExercisesOnPage(searchTerm?: string, page?: number, pageSize?: number, sortingOrder?: 'ASCENDING' | 'DESCENDING', isCourseFilter?: boolean, isExamFilter?: boolean): Observable<SearchResultPageDTOQuizExerciseForSearch> {
        const queryParams = new URLSearchParams();
        if (searchTerm !== undefined && searchTerm !== null) {
            queryParams.set('searchTerm', String(searchTerm));
        }
        if (page !== undefined && page !== null) {
            queryParams.set('page', String(page));
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParams.set('pageSize', String(pageSize));
        }
        if (sortingOrder !== undefined && sortingOrder !== null) {
            queryParams.set('sortingOrder', String(sortingOrder));
        }
        if (isCourseFilter !== undefined && isCourseFilter !== null) {
            queryParams.set('isCourseFilter', String(isCourseFilter));
        }
        if (isExamFilter !== undefined && isExamFilter !== null) {
            queryParams.set('isExamFilter', String(isExamFilter));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/quiz/quiz-exercises${queryString ? `?${queryString}` : ''}`;
        return this.http.get<SearchResultPageDTOQuizExerciseForSearch>(url);
    }

    /**
     *
     *
     * @param quizExerciseId
     */
    getQuizExercise(quizExerciseId: number): Observable<QuizExerciseWithStatistics> {
        const url = `${this.basePath}/api/quiz/quiz-exercises/${quizExerciseId}`;
        return this.http.get<QuizExerciseWithStatistics>(url);
    }

    /**
     *
     *
     * @param quizExerciseId
     */
    getQuizExerciseForStudent(quizExerciseId: number): Observable<QuizExerciseForStudentResponse> {
        const url = `${this.basePath}/api/quiz/quiz-exercises/${quizExerciseId}/for-student`;
        return this.http.get<QuizExerciseForStudentResponse>(url);
    }

    /**
     *
     *
     * @param courseId
     */
    getQuizExercisesForCourse(courseId: number): Observable<Array<QuizExerciseForCourse>> {
        const url = `${this.basePath}/api/quiz/courses/${courseId}/quiz-exercises`;
        return this.http.get<Array<QuizExerciseForCourse>>(url);
    }

    /**
     *
     *
     * @param examId
     */
    getQuizExercisesForExam(examId: number): Observable<Array<QuizExerciseForCourse>> {
        const url = `${this.basePath}/api/quiz/exams/${examId}/quiz-exercises`;
        return this.http.get<Array<QuizExerciseForCourse>>(url);
    }

}
