/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * QuizTrainingApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { LeaderboardSetting } from '../model/leaderboard-setting';
import { QuizQuestionTraining } from '../model/quiz-question-training';
import { LeaderboardWithCurrentUserEntry } from '../model/leaderboard-with-current-user-entry';
import { SubmittedAnswerFromLiveClient } from '../model/submitted-answer-from-live-client';
import { SubmittedAnswerAfterEvaluation } from '../model/submitted-answer-after-evaluation';

@Injectable({ providedIn: 'root' })
export class QuizTrainingApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     */
    getLeaderboardSettings(): Observable<LeaderboardSetting> {
        const url = `${this.basePath}/api/quiz/leaderboard-settings`;
        return this.http.get<LeaderboardSetting>(url);
    }

    /**
     *
     *
     * @param courseId
     * @param isNewSession
     * @param requestBody
     * @param page Zero-based page index (0..N)
     * @param size The size of the page to be returned
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    getQuizQuestionsForPractice(courseId: number, isNewSession: boolean, requestBody: Array<number>, page?: number, size?: number, sort?: Array<string>): Observable<Array<QuizQuestionTraining>> {
        const queryParams = new URLSearchParams();
        if (page !== undefined && page !== null) {
            queryParams.set('page', String(page));
        }
        if (size !== undefined && size !== null) {
            queryParams.set('size', String(size));
        }
        if (sort !== undefined && sort !== null) {
            sort.forEach(item => queryParams.append('sort', String(item)));
        }
        if (isNewSession !== undefined && isNewSession !== null) {
            queryParams.set('isNewSession', String(isNewSession));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training-questions${queryString ? `?${queryString}` : ''}`;
        return this.http.post<Array<QuizQuestionTraining>>(url, requestBody);
    }

    /**
     *
     *
     * @param courseId
     */
    getQuizTrainingLeaderboard(courseId: number): Observable<LeaderboardWithCurrentUserEntry> {
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training/leaderboard`;
        return this.http.get<LeaderboardWithCurrentUserEntry>(url);
    }

    /**
     *
     *
     * @param courseId
     * @param leaderboardSetting
     */
    initializeLeaderboardEntry(courseId: number, leaderboardSetting: LeaderboardSetting): Observable<void> {
        const url = `${this.basePath}/api/quiz/courses/${courseId}/leaderboard-entry`;
        return this.http.post<void>(url, leaderboardSetting);
    }

    /**
     *
     *
     * @param courseId
     * @param trainingQuestionId
     * @param isRated
     * @param submittedAnswerFromLiveClient
     */
    submitForTraining(courseId: number, trainingQuestionId: number, isRated: boolean, submittedAnswerFromLiveClient: SubmittedAnswerFromLiveClient): Observable<SubmittedAnswerAfterEvaluation> {
        const queryParams = new URLSearchParams();
        if (isRated !== undefined && isRated !== null) {
            queryParams.set('isRated', String(isRated));
        }
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/quiz/courses/${courseId}/training-questions/${trainingQuestionId}/submit${queryString ? `?${queryString}` : ''}`;
        return this.http.post<SubmittedAnswerAfterEvaluation>(url, submittedAnswerFromLiveClient);
    }

    /**
     *
     *
     * @param leaderboardSetting
     */
    updateLeaderboardSettings(leaderboardSetting: LeaderboardSetting): Observable<void> {
        const url = `${this.basePath}/api/quiz/leaderboard-settings`;
        return this.http.put<void>(url, leaderboardSetting);
    }

}
