/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * QuizExerciseDeletionApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class QuizExerciseDeletionApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     *
     *
     * @param quizExerciseId
     */
    deleteQuizExercise(quizExerciseId: number): Observable<void> {
        const url = `${this.basePath}/api/quiz/quiz-exercises/${quizExerciseId}`;
        return this.http.delete<void>(url);
    }

}
