/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 8.5.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * TutorialGroupApi - API service for mutations (POST, PUT, DELETE, PATCH)
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Student } from '../models/student';
import { TutorialGroupRegistrationImport } from '../models/tutorial-group-registration-import';

@Injectable({ providedIn: 'root' })
export class TutorialGroupApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupId 
     */
    delete(courseId: number, tutorialGroupId: number): Observable<void> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups/${tutorialGroupId}`;
        return this.http.delete<void>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupId 
     * @param studentLogin 
     */
    deregisterStudent(courseId: number, tutorialGroupId: number, studentLogin: string): Observable<void> {
        const studentLoginPath = encodeURIComponent(String(studentLogin));
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups/${tutorialGroupId}/deregister/${studentLoginPath}`;
        return this.http.delete<void>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupRegistrationImport 
     */
    importRegistrations(courseId: number, tutorialGroupRegistrationImport: Array<TutorialGroupRegistrationImport>): Observable<Array<TutorialGroupRegistrationImport>> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups/import`;
        return this.http.post<Array<TutorialGroupRegistrationImport>>(url, tutorialGroupRegistrationImport);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupId 
     * @param student 
     */
    registerMultipleStudentsToTutorialGroup(courseId: number, tutorialGroupId: number, student: Array<Student>): Observable<Array<Student>> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups/${tutorialGroupId}/register-multiple`;
        return this.http.post<Array<Student>>(url, student);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupId 
     * @param studentLogin 
     */
    registerStudent(courseId: number, tutorialGroupId: number, studentLogin: string): Observable<void> {
        const studentLoginPath = encodeURIComponent(String(studentLogin));
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups/${tutorialGroupId}/register/${studentLoginPath}`;
        return this.http.post<void>(url, null);
    }

}
