/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 8.5.1
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * TutorialGroupApi Resources - Signal-based HTTP resources for GET operations
 * Uses Angular's httpResource for reactive data fetching
 * @generated from OpenAPI specification
 */
import { httpResource, HttpResourceRef } from '@angular/common/http';
import { Signal } from '@angular/core';
import { TutorialGroupDetailGroup } from '../models/tutorial-group-detail-group';
import { TutorialGroupExport } from '../models/tutorial-group-export';

export const BASE_PATH = '';

/**
 * Query parameters for exportTutorialGroupsToCSV
 */
export interface ExportTutorialGroupsToCSVParams {
    fields: Array<string>;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param params Optional signal containing query parameters
 */
export function exportTutorialGroupsToCSVResource(courseId: Signal<number> | number, params?: Signal<ExportTutorialGroupsToCSVParams>): HttpResourceRef<Blob | undefined> {
    return httpResource<Blob>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        const queryParams = (params?.() ?? {}) as ExportTutorialGroupsToCSVParams;
        const searchParams = new URLSearchParams();
        if (queryParams.fields?.length) {
            queryParams.fields.forEach(value => searchParams.append('fields', String(value)));
        }
        const query = searchParams.toString();
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups/export/csv${query ? `?${query}` : ''}`;
    });
}

/**
 * Query parameters for exportTutorialGroupsToJSON
 */
export interface ExportTutorialGroupsToJSONParams {
    fields: Array<string>;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param params Optional signal containing query parameters
 */
export function exportTutorialGroupsToJSONResource(courseId: Signal<number> | number, params?: Signal<ExportTutorialGroupsToJSONParams>): HttpResourceRef<Array<TutorialGroupExport> | undefined> {
    return httpResource<Array<TutorialGroupExport>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        const queryParams = (params?.() ?? {}) as ExportTutorialGroupsToJSONParams;
        const searchParams = new URLSearchParams();
        if (queryParams.fields?.length) {
            queryParams.fields.forEach(value => searchParams.append('fields', String(value)));
        }
        const query = searchParams.toString();
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups/export/json${query ? `?${query}` : ''}`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 */
export function getAllForCourseResource(courseId: Signal<number> | number): HttpResourceRef<Array<any> | undefined> {
    return httpResource<Array<any>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param tutorialGroupId 
 */
export function getTitleResource(tutorialGroupId: Signal<number> | number): HttpResourceRef<string | undefined> {
    return httpResource<string>(() => {
        const tutorialGroupIdValue = typeof tutorialGroupId === 'function' ? tutorialGroupId() : tutorialGroupId;
        return `${BASE_PATH}/api/tutorialgroup/tutorial-groups/${tutorialGroupIdValue}/title`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param tutorialGroupId 
 */
export function getTutorialGroupDetailGroupDTOResource(courseId: Signal<number> | number, tutorialGroupId: Signal<number> | number): HttpResourceRef<TutorialGroupDetailGroup | undefined> {
    return httpResource<TutorialGroupDetailGroup>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        const tutorialGroupIdValue = typeof tutorialGroupId === 'function' ? tutorialGroupId() : tutorialGroupId;
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-group-detail/${tutorialGroupIdValue}`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 */
export function getUniqueCampusValuesResource(courseId: Signal<number> | number): HttpResourceRef<Array<string> | undefined> {
    return httpResource<Array<string>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups/campus-values`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 */
export function getUniqueLanguageValuesResource(courseId: Signal<number> | number): HttpResourceRef<Array<string> | undefined> {
    return httpResource<Array<string>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups/language-values`;
    });
}

export {};
