/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.3
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * TutorialGroupFreePeriodApi Resources - Signal-based HTTP resources for GET operations
 * Uses Angular's httpResource for reactive data fetching
 * @generated from OpenAPI specification
 */
import { httpResource, HttpResourceRef } from '@angular/common/http';
import { Signal } from '@angular/core';
import { TutorialGroupFreePeriod } from '../model/tutorial-group-free-period';
import { TutorialGroupSessionCount } from '../model/tutorial-group-session-count';
import { TutorialGroupFreePeriodSessionCount } from '../model/tutorial-group-free-period-session-count';
import { appendQueryParam } from './query-params';

const BASE_PATH = '';

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param tutorialGroupsConfigurationId 
 * @param tutorialFreePeriodId 
 */
export function getOneOfConfigurationResource(courseId: Signal<number | undefined> | number, tutorialGroupsConfigurationId: Signal<number | undefined> | number, tutorialFreePeriodId: Signal<number | undefined> | number): HttpResourceRef<TutorialGroupFreePeriod | undefined> {
    return httpResource<TutorialGroupFreePeriod>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        if (courseIdValue === undefined) {
            return undefined;
        }
        const tutorialGroupsConfigurationIdValue = typeof tutorialGroupsConfigurationId === 'function' ? tutorialGroupsConfigurationId() : tutorialGroupsConfigurationId;
        if (tutorialGroupsConfigurationIdValue === undefined) {
            return undefined;
        }
        const tutorialFreePeriodIdValue = typeof tutorialFreePeriodId === 'function' ? tutorialFreePeriodId() : tutorialFreePeriodId;
        if (tutorialFreePeriodIdValue === undefined) {
            return undefined;
        }
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-groups-configurations/${tutorialGroupsConfigurationIdValue}/tutorial-free-periods/${tutorialFreePeriodIdValue}`;
    });
}

/**
 * Query parameters for getOverlappingSessionCount
 */
export interface GetOverlappingSessionCountParams {
    from: string;
    to: string;
    editedFreePeriodId?: number;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param params Optional signal containing query parameters
 */
export function getOverlappingSessionCountResource(courseId: Signal<number | undefined> | number, params: Signal<GetOverlappingSessionCountParams>): HttpResourceRef<number | undefined> {
    return httpResource<number>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        if (courseIdValue === undefined) {
            return undefined;
        }
        const queryParams = params();
        const searchParams = new URLSearchParams();
        appendQueryParam(searchParams, 'from', queryParams.from);
        appendQueryParam(searchParams, 'to', queryParams.to);
        appendQueryParam(searchParams, 'editedFreePeriodId', queryParams.editedFreePeriodId);
        const query = searchParams.toString();
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-free-periods/overlapping-session-count${query ? `?${query}` : ''}`;
    });
}

/**
 * Query parameters for getSessionCounts
 */
export interface GetSessionCountsParams {
    from: string;
    to: string;
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 * @param params Optional signal containing query parameters
 */
export function getSessionCountsResource(courseId: Signal<number | undefined> | number, params: Signal<GetSessionCountsParams>): HttpResourceRef<Array<TutorialGroupSessionCount> | undefined> {
    return httpResource<Array<TutorialGroupSessionCount>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        if (courseIdValue === undefined) {
            return undefined;
        }
        const queryParams = params();
        const searchParams = new URLSearchParams();
        appendQueryParam(searchParams, 'from', queryParams.from);
        appendQueryParam(searchParams, 'to', queryParams.to);
        const query = searchParams.toString();
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-free-periods/session-counts${query ? `?${query}` : ''}`;
    });
}

/**
 * 
 * 
 * Creates a reactive HTTP resource that automatically refetches when signals change.
 * @param courseId 
 */
export function getSessionCountsPerFreePeriodResource(courseId: Signal<number | undefined> | number): HttpResourceRef<Array<TutorialGroupFreePeriodSessionCount> | undefined> {
    return httpResource<Array<TutorialGroupFreePeriodSessionCount>>(() => {
        const courseIdValue = typeof courseId === 'function' ? courseId() : courseId;
        if (courseIdValue === undefined) {
            return undefined;
        }
        return `${BASE_PATH}/api/tutorialgroup/courses/${courseIdValue}/tutorial-free-periods/session-counts-per-period`;
    });
}

