/**
 * Artemis Application Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 10.0
 * Contact: krusche@tum.de
 *
 * NOTE: This file is auto-generated. Do not edit manually.
 */

/**
 * TutorialGroupFreePeriodApi - API service
 * @generated from OpenAPI specification
 */
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { TutorialGroupFreePeriod } from '../model/tutorial-group-free-period';
import { TutorialGroupFreePeriodRequest } from '../model/tutorial-group-free-period-request';
import { TutorialGroupSessionCount } from '../model/tutorial-group-session-count';
import { TutorialGroupFreePeriodSessionCount } from '../model/tutorial-group-free-period-session-count';
import { appendQueryParam } from './query-params';

@Injectable({ providedIn: 'root' })
export class TutorialGroupFreePeriodApi {
    private readonly http = inject(HttpClient);
    private readonly basePath = '';

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupsConfigurationId 
     * @param tutorialGroupFreePeriodRequest 
     */
    create(courseId: number, tutorialGroupsConfigurationId: number, tutorialGroupFreePeriodRequest: TutorialGroupFreePeriodRequest): Observable<TutorialGroupFreePeriod> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups-configurations/${tutorialGroupsConfigurationId}/tutorial-free-periods`;
        return this.http.post<TutorialGroupFreePeriod>(url, tutorialGroupFreePeriodRequest);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupsConfigurationId 
     * @param tutorialFreePeriodId 
     */
    delete(courseId: number, tutorialGroupsConfigurationId: number, tutorialFreePeriodId: number): Observable<void> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups-configurations/${tutorialGroupsConfigurationId}/tutorial-free-periods/${tutorialFreePeriodId}`;
        return this.http.delete<void>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupsConfigurationId 
     * @param tutorialFreePeriodId 
     */
    getOneOfConfiguration(courseId: number, tutorialGroupsConfigurationId: number, tutorialFreePeriodId: number): Observable<TutorialGroupFreePeriod> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups-configurations/${tutorialGroupsConfigurationId}/tutorial-free-periods/${tutorialFreePeriodId}`;
        return this.http.get<TutorialGroupFreePeriod>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param from 
     * @param to 
     * @param editedFreePeriodId 
     */
    getOverlappingSessionCount(courseId: number, from: string, to: string, editedFreePeriodId?: number): Observable<number> {
        const queryParams = new URLSearchParams();
        appendQueryParam(queryParams, 'from', from);
        appendQueryParam(queryParams, 'to', to);
        appendQueryParam(queryParams, 'editedFreePeriodId', editedFreePeriodId);
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-free-periods/overlapping-session-count${queryString ? `?${queryString}` : ''}`;
        return this.http.get<number>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param from 
     * @param to 
     */
    getSessionCounts(courseId: number, from: string, to: string): Observable<Array<TutorialGroupSessionCount>> {
        const queryParams = new URLSearchParams();
        appendQueryParam(queryParams, 'from', from);
        appendQueryParam(queryParams, 'to', to);
        const queryString = queryParams.toString();
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-free-periods/session-counts${queryString ? `?${queryString}` : ''}`;
        return this.http.get<Array<TutorialGroupSessionCount>>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     */
    getSessionCountsPerFreePeriod(courseId: number): Observable<Array<TutorialGroupFreePeriodSessionCount>> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-free-periods/session-counts-per-period`;
        return this.http.get<Array<TutorialGroupFreePeriodSessionCount>>(url);
    }

    /**
     * 
     * 
     * @param courseId 
     * @param tutorialGroupsConfigurationId 
     * @param tutorialFreePeriodId 
     * @param tutorialGroupFreePeriodRequest 
     */
    update(courseId: number, tutorialGroupsConfigurationId: number, tutorialFreePeriodId: number, tutorialGroupFreePeriodRequest: TutorialGroupFreePeriodRequest): Observable<TutorialGroupFreePeriod> {
        const url = `${this.basePath}/api/tutorialgroup/courses/${courseId}/tutorial-groups-configurations/${tutorialGroupsConfigurationId}/tutorial-free-periods/${tutorialFreePeriodId}`;
        return this.http.put<TutorialGroupFreePeriod>(url, tutorialGroupFreePeriodRequest);
    }

}
