package de.tum.cit.aet.artemis.iris.domain.message;

/**
 * This enum represents the different senders of Iris messages.
 * <p>
 * USER: A message sent by a user of the system
 * <p>
 * LLM: A message generated by a large language model
 * <p>
 * ARTIFACT: A artifact generated by the system, such as a tutor suggestion
 * <p>
 * CTXSWAP: A system-generated marker message indicating a context switch within an active session.
 * Persisted in the chat history so the LLM can interpret previous messages against the previous context.
 * The stored content is the new context's entity name; the LLM-facing marker prefix is added by Pyris.
 * <p>
 * COMMAND: A marker for a client action Iris performed, such as pointing to a slide page or video timestamp
 * <p>
 * SUMMARY: A summary Iris wrote of the earlier conversation, with the id of the last message it covers. Iris sends it in
 * place of the covered messages. It is hidden in the client, and all original messages stay.
 * <p>
 * The sender column is varchar(8), so new values must have at most 8 characters.
 * <p>
 * Note: The ARTEMIS message sender variant was removed, as its original intent was
 * based on an incomplete understanding of the requirements of the Iris subsystem.
 */
public enum IrisMessageSender {
    USER, LLM, ARTIFACT, CTXSWAP, COMMAND, SUMMARY
}
