{
 "title": "Artemis Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Artemis User - Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(artemis_instance_websocket_users)"
    }
   ]
  },
  {
   "title": "Artemis User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_instance_websocket_users",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Artemis Health - external systems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance_name) (artemis_health)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Artemis-Health per External System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (healthindicator) (artemis_health)",
     "legendFormat": "{{healthindicator}}"
    }
   ]
  }
 ]
}