{
 "title": "Endpoint Monitoring Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topNumberEndpoints",
    "label": "Number Endpoints with Highest Value",
    "query": "20"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Request Duration (ms)",
   "type": "timeseries",
   "description": "Endpoints that have top 20 highest average duration.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($topNumberEndpoints, 1000 * sum(rate (http_server_requests_seconds_sum[$__rate_interval])\n/\nrate(http_server_requests_seconds_count[$__rate_interval])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "Request count per endpoint for the 20 most used endpoints.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk($topNumberEndpoints, sum(increase(http_server_requests_seconds_count[$__rate_interval])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Endpoint Error Rate (%)",
   "type": "timeseries",
   "description": "Error rates for the top 20 endpoints with the highest 4xx error rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topNumberEndpoints, 100 * sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[$__rate_interval])) by (uri)\n/\nsum(rate(http_server_requests_seconds_count[$__rate_interval])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Endpoint Error Rate (%)",
   "type": "timeseries",
   "description": "Top 20 endpoints with the highest 5xx error rate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topNumberEndpoints, 100 * sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[$__rate_interval])) by (uri)\n/\nsum(rate(http_server_requests_seconds_count[$__rate_interval])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}