name: Build Documentation

on:
  workflow_call:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: documentation
        run: npm ci

      - name: Documentation Code Style
        working-directory: documentation
        run: npm run lint

      - name: Build Docusaurus site
        working-directory: documentation
        run: npm run build
