name: Build Documentation

on:
  workflow_call: {}

permissions: {}

env:
  node: 24

jobs:
  build:
    name: Build Docusaurus site
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093  # v6.0.8
        with:
          package_json_file: documentation/package.json
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: '${{ env.node }}'
          cache: 'pnpm'
          cache-dependency-path: documentation/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: documentation
        run: pnpm install --frozen-lockfile

      - name: Documentation Code Style
        working-directory: documentation
        run: pnpm run lint

      - name: Build Docusaurus site
        working-directory: documentation
        run: pnpm run build
