name: Build Documentation

on:
  pull_request:
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'
  push:
    branches:
    - develop
    - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'
  release:
    types:
    - created

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: docs/_build/html/
