name: "Validate Gradle Wrapper"
on:
    push:
        branches:
            - develop
            - main
            - release/*
        paths:
            - '**/gradle/**'
    pull_request:
        branches: [develop]
        paths:
            - '**/gradle/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    validation:
        name: "Gradle Wrapper Validation"
        runs-on: arc-buildkit-ls1intum-theiaprod-amd64
        steps:
            - uses: actions/checkout@v6
            - uses: gradle/actions/wrapper-validation@v6
              with:
                  min-wrapper-count: 6 # 5 in the different gradle templates and 1 for the Artemis project itself
