name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: arc-buildkit-ls1intum-stud-amd64
    steps:
      - uses: MaximilianAnzinger/issue-labeler@1.0.2
        with:
          configuration-path: .github/issue-labeler.yml
          repo-token: ${{ github.token }}
