name: Pull Request Converted to draft
on:
  pull_request:
    types: [reopened]

jobs:
  moveToInProgress:
    runs-on: ubuntu-latest
    steps:
      - name: Move to "In progress" column
        if: github.event.pull_request.draft == true
        uses: alex-page/github-project-automation-plus@v0.1.1
        with:
          project: Artemis Development
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}
