name: Pull Request Ready for Review
on:
  pull_request_target:
    types: [ready_for_review]

permissions:
  pull-requests: write

jobs:
  pullequestReadyForReview:
    runs-on: ubuntu-latest
    steps:
      - name: Label "ready for review"
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready for review']
            })
