name: Pull Request Opened
on:
  pull_request_target:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Pull Request to its Author
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160  # v1.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
